Repository Automattic/sensei, pull requests merged in 2018-06, with the labels that each got.

#2162 Start lesson when eligible user first views lesson page
  includes/class-sensei-lesson.php
  includes/class-sensei-utils.php
  tests/unit-tests/test-class-lesson.php
Labels: [Type] Enhancement

#2163 Fix lesson preview indicator
  assets/css/frontend/sensei.css
  assets/css/frontend/sensei.scss
  assets/css/modules-frontend.css
  assets/css/modules-frontend.scss
  includes/class-sensei-frontend.php
  includes/class-sensei-lesson.php
  templates/single-course/modules.php
Labels: [Status] Needs Documentation

#2185 Add phpcodesniffer to the composer.json file
  composer.json
Labels: [Pri] Low, [Type] Maintenance

#2184 Update Gulp to v4.0.0 + Gulp syntax fixes
  assets/css/frontend/sensei.css
  assets/js/frontend/course-archive.min.js
  gulpfile.js
  package-lock.json
  package.json
Labels: [Type] Maintenance
