Repository Automattic/sensei, pull requests merged in 2019-05, with the labels that each got.

#2672 Add event logging for module creation with base properties
  assets/js/modules-admin.js
  assets/js/modules-admin.min.js
  includes/class-sensei-modules.php
  includes/class-sensei-usage-tracking-data.php
  includes/sensei-functions.php
Labels: Hooks & Filters

#2523 Fix squashed vertical gap for quiz tabs
  CONTRIBUTING.md
  assets/css/settings.css
  assets/css/settings.scss
Labels: Quizzes, UI, [Pri] Low

#2696 Log importing of dummy data
  includes/3rd-party/wordpress-importer.php
  includes/sensei-functions.php
Labels: Hooks & Filters

#2521 Add label and description for a message that is related to a quiz.
  includes/class-sensei-messages.php
Labels: [Type] Bug

#2510 Allow disabling of the redirect after completing lesson behavior
  includes/class-sensei-frontend.php
Labels: Hooks & Filters, [Type] Enhancement
