Repository Automattic/sensei, pull requests merged in 2019-06, with the labels that each got.

#2514 Add "Edit Course" button when in classic editor.
  includes/class-sensei-lesson.php
Labels: Lessons, UI

#2732 Remove unused variables from codebase
  includes/admin/class-sensei-learner-management.php
  includes/class-sensei-admin-rest-api-testharness.php
  includes/class-sensei-admin.php
  includes/class-sensei-analysis-lesson-list-table.php
  includes/class-sensei-analysis-overview-list-table.php
  includes/class-sensei-analysis.php
  includes/class-sensei-course-results.php
  includes/class-sensei-course.php
  includes/class-sensei-emails.php
  includes/class-sensei-frontend.php
  includes/class-sensei-grading.php
  includes/class-sensei-learner-profiles.php
  includes/class-sensei-learner.php
  includes/class-sensei-learners-admin-bulk-actions-controller.php
  includes/class-sensei-learners-main.php
  includes/class-sensei-lesson.php
  includes/class-sensei-list-table.php
  includes/class-sensei-messages.php
  includes/class-sensei-posttypes.php
  includes/class-sensei-question.php
  includes/class-sensei-quiz.php
  includes/class-sensei-settings-api.php
  includes/class-sensei-settings.php
  includes/class-sensei-templates.php
  includes/class-sensei-updates.php
  includes/class-sensei-utils.php
  includes/class-sensei.php
  includes/shortcodes/class-sensei-legacy-shortcodes.php
  includes/template-functions.php
Labels: Deprecation

#2730 Rename event logging JS file to match file naming standards
  assets/js/admin/event-logging.js
  assets/js/admin/event-logging.min.js
  includes/class-sensei-admin.php
Labels: [Pri] Low, [Type] Maintenance

#2743 Fix issue with multiple correct answers being removed from question editor
  includes/class-sensei-lesson.php
Labels: [Pri] High, [Type] Bug

#2744 Fix issue with how we filter allowed CSS attributes on bulk learner
  includes/class-sensei-learners-admin-bulk-actions-view.php
Labels: [Pri] Low, [Type] Bug
