Repository Automattic/sensei, pull requests merged in 2019-02, with the labels that each got.

#2396 Remove "Add to Cart" button
  includes/class-sensei-course.php
Labels: Hooks & Filters

#2405 Extract purchase logic for Course Signup Link on a Lesson
  includes/class-sensei-lesson.php
Labels: Hooks & Filters

#2408 Add filter for course signup on quiz page for logged out users
  includes/class-sensei-utils.php
Labels: Hooks & Filters

#2413 Deprecate sensei_simple_course_price() and introduce new hooks
  includes/class-sensei-course.php
  includes/class-sensei-frontend.php
  includes/shortcodes/class-sensei-legacy-shortcodes.php
  includes/template-functions.php
  widgets/widget-woothemes-sensei-category-courses.php
  widgets/widget-woothemes-sensei-course-component.php
Labels: Hooks & Filters

#2423 Have deprecated WC utility methods throw deprecation notice
  includes/class-sensei-utils.php
Labels: Deprecation

#2427 Remove `[sensei_unpurchased_courses]` shortcode
  includes/shortcodes/class-sensei-shortcode-loader.php
  includes/shortcodes/class-sensei-shortcode-unpurchased-courses.php
Labels: Hooks & Filters

#2419 Deprecate Sensei_Main::check_user_permissions()
  includes/class-sensei.php
Labels: Deprecation

#2429 Remove free/paid course references from the Course Component widget
  widgets/widget-woothemes-sensei-course-component.php
Labels: Hooks & Filters

#2406 Deprecate "Delete Course" buttons
  includes/class-sensei-course.php
  includes/class-sensei-frontend.php
  includes/sensei-wc-stubs.php
Labels: Deprecation

#2447 Adds deprecation notices for WooCommerce related template functions
  includes/template-functions.php
Labels: Deprecation

#2446 Add deprecation notices for WC methods from `Sensei_Main` class
  includes/class-sensei.php
Labels: Deprecation

#2461 Add Classic Editor plugin to usage tracking
  includes/class-sensei-usage-tracking.php
Labels: Usage Tracking
