Repository Automattic/sensei, pull requests merged in 2019-07, with the labels that each got.

#2737 Add a filter for modifying the module title HTML
  includes/class-sensei-modules.php
Labels: Hooks & Filters

#2755 Log product count when a course is published
  includes/class-sensei-course.php
  tests/unit-tests/test-class-course.php
Labels: Logging, [Pri] Normal

#2760 Deprecate rather than remove lesson_add_course function
  includes/class-sensei-lesson.php
Labels: Deprecation
