Repository Automattic/sensei, pull requests merged in 2020-01, with the labels that each got.

#2837 Add PR and issue templates to the repo
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [Pri] Low, [Type] Enhancement

#2838 Add course enrollment indicator to learner management
  assets/css/settings.css
  assets/css/settings.scss
  assets/js/learners-general.js
  assets/js/learners-general.min.js
  includes/admin/class-sensei-learner-management.php
  includes/class-sensei-feature-flags.php
  includes/class-sensei-learners-main.php
Labels: Hooks, [Status] Product Reviewed

#2833 Add clear background to TinyMCE buttons
  includes/class-sensei-utils.php
Labels: [Status] Product Reviewed

#2847 Fix settings deletion on page setup
  includes/class-sensei-settings-api.php
  includes/class-sensei-settings.php
Labels: [Status] Product Reviewed

#2849 Merge pull request #2849 from Automattic/fix/settings-deletion
  includes/class-sensei-settings-api.php
  includes/class-sensei-settings.php
Labels: [Status] Product Reviewed

#2848 Add manual enrollment provider
  assets/css/settings.css
  assets/css/settings.scss
  assets/js/learners-general.js
  assets/js/learners-general.min.js
  includes/admin/class-sensei-learner-management.php
  includes/class-sensei-course-enrolment-manager.php
  includes/class-sensei-course-enrolment-provider-results.php
  includes/class-sensei-course-enrolment.php
  includes/class-sensei-course-manual-enrolment-provider.php
  includes/class-sensei-course.php
  includes/class-sensei-data-cleaner.php
  includes/class-sensei-learners-main.php
  includes/class-sensei-utils.php
  includes/class-sensei.php
  tests/bootstrap.php
  tests/framework/trait-sensei-course-enrolment-manual-test-helpers.php
  tests/unit-tests/test-class-lesson.php
  tests/unit-tests/test-class-sensei-course-enrolment-manager.php
  tests/unit-tests/test-class-sensei-course-enrolment-provider-results.php
  tests/unit-tests/test-class-sensei-course-enrolment.php
  tests/unit-tests/test-class-sensei-course-manual-enrolment-provider.php
Labels: [Status] Product Reviewed

#2854 Manually enrol student on frontend when they sign up for course
  includes/class-sensei-course.php
  includes/class-sensei-frontend.php
  includes/template-functions.php
Labels: [Status] Product Reviewed

#2865 Fix 2858: Apply filter when my-courses page not set
  includes/class-sensei-course.php
Labels: [Status] Product Reviewed

#2840 Fix/issue 2832 Prevent comments from being displayed if user isn't allowed to view lesson
  includes/class-sensei-lesson.php
Labels: [Status] Product Reviewed

#2853 Fix/issue 2825 Append post status to pre-requisite lesson on lessons page
  includes/class-sensei-lesson.php
Labels: [Status] Product Reviewed

#2871 Add missing question ID to hidden question field
  includes/class-sensei-question.php
Labels: [Status] Product Reviewed
