Repository Automattic/sensei, pull requests merged in 2020-12, with the labels that each got.

#3800 Fix saving race condition
  assets/blocks/course-outline/course-block/edit.js
  assets/blocks/course-outline/course-block/save.js
  assets/blocks/course-outline/data.js
  assets/blocks/course-outline/data.test.js
  assets/blocks/course-outline/store.js
  assets/blocks/course-outline/use-block-creator.js
Labels: [Type] Enhancement

#3826 Release 3.6.0 Beta 2
  .travis.yml
  changelog.txt
  lang/sensei-lms.pot
  sensei-lms.php
Labels: [Type] Maintenance

#3836 Add filter to only allow some mime types to quiz file upload answers (3.7)
  includes/class-sensei-quiz.php
Labels: [Type] Maintenance

#3839 Release 3.6.0
  changelog.txt
  lang/sensei-lms.pot
  sensei-lms.php
Labels: [Type] Maintenance

#3565 Use JSDoc format for hooks in Sensei_Lesson
  includes/class-sensei-lesson.php
Labels: [Type] Maintenance

#3569 Use JSDoc format for hooks in Sensei_Question
  includes/class-sensei-question.php
  includes/class-sensei-quiz.php
Labels: [Type] Maintenance

#3475 Remove REST API Test Harness code
  assets/js/admin/testharness.js
  assets/vendor/react/react-dom.min.js
  assets/vendor/react/react.min.js
  includes/class-sensei-admin-rest-api-testharness.php
  includes/class-sensei-feature-flags.php
  includes/class-sensei.php
  webpack.config.js
Labels: Deprecation

#3846 Fix teacher/admin module slug conflicts
  includes/class-sensei-course-structure.php
  tests/unit-tests/test-class-sensei-course-structure.php
Labels: [Type] Bug

#3844 Fix the blocks color styles
  assets/blocks/course-outline/lesson-block/lesson-block.scss
  assets/blocks/course-outline/module-block/block.json
  assets/blocks/course-outline/module-block/module-block.scss
  assets/shared/blocks/settings.js
  includes/blocks/class-sensei-block-helpers.php
  includes/blocks/class-sensei-course-outline-module-block.php
Labels: [Type] Bug

#3857 Add Remove Progress button in Learner Management for lessons
  assets/js/learners-general.js
  includes/admin/class-sensei-learner-management.php
  includes/admin/class-sensei-learners-main.php
Labels: [Type] Enhancement

#3842 Add Tools page and deprecate Data Updates
  includes/admin/class-sensei-tools.php
  includes/admin/tools/class-sensei-tool-ensure-roles.php
  includes/admin/tools/class-sensei-tool-interactive-interface.php
  includes/admin/tools/class-sensei-tool-interface.php
  includes/admin/tools/class-sensei-tool-recalculate-course-enrolment.php
  includes/admin/tools/class-sensei-tool-recalculate-enrolment.php
  includes/admin/tools/class-sensei-tool-remove-deleted-user-data.php
  includes/admin/tools/views/html-recalculate-course-enrolment-form.php
  includes/admin/views/html-admin-page-tools-footer.php
  includes/admin/views/html-admin-page-tools-header.php
  includes/admin/views/html-admin-page-tools.php
  includes/class-sensei-admin.php
  includes/class-sensei-autoloader.php
  includes/class-sensei-updates.php
  includes/class-sensei.php
  tests/unit-tests/admin/tools/test-class-sensei-tool-remove-deleted-user-data.php
  tests/unit-tests/enrolment/test-class-sensei-course-enrolment.php
Labels: Deprecation, Hooks, [Type] Enhancement

#3843 Adds Enrollment Debugger to Sensei Tools
  assets/css/enrolment-debug.scss
  includes/admin/class-sensei-tools.php
  includes/admin/tools/class-sensei-tool-enrolment-debug.php
  includes/admin/tools/views/html-enrolment-debug-form.php
  includes/admin/tools/views/html-enrolment-debug.php
  includes/class-sensei-autoloader.php
  webpack.config.js
Labels: Hooks, [Type] Enhancement

#3855 Remove duplicate progress comments after inserting a new one to mitigate duplication issue
  includes/class-sensei-learner.php
  includes/class-sensei-utils.php
Labels: [Type] Bug
