Repository Automattic/sensei, pull requests merged in 2020-09, with the labels that each got.

#3560 Add course outline basic setup
  assets/block-editor/index.jsx
  assets/blocks/course-outline/course-outline-block.js
  assets/blocks/course-outline/index.js
  assets/blocks/course-outline/lesson-outline-block.js
  assets/blocks/course-outline/module-outline-block.js
  assets/blocks/course-outline/style.scss
  includes/blocks/class-sensei-blocks.php
  includes/blocks/class-sensei-course-outline-block.php
  includes/class-sensei-autoloader.php
  includes/class-sensei-blocks.php
  includes/class-sensei-feature-flags.php
  includes/class-sensei.php
  webpack.config.js
Labels: [Type] Enhancement

#3579 Apply label to Renovate PRs
  renovate.json
Labels: [Type] Maintenance

#3584 Base for course outline content
  assets/blocks/course-outline/course-outline-block.js
  assets/blocks/course-outline/edit.js
  assets/blocks/course-outline/index.js
  assets/blocks/course-outline/lesson-block/edit.js
  assets/blocks/course-outline/lesson-block/edit.test.js
  assets/blocks/course-outline/lesson-block/index.js
  assets/blocks/course-outline/module-block/edit.js
  assets/blocks/course-outline/module-block/edit.test.js
  assets/blocks/course-outline/module-block/index.js
  assets/blocks/course-outline/module-outline-block.js
  assets/blocks/course-outline/single-line-input/index.js
  assets/blocks/course-outline/single-line-input/index.test.js
  assets/blocks/course-outline/style.scss
  assets/blocks/course-outline/use-block-creator.js
  includes/blocks/class-sensei-course-outline-block.php
  package-lock.json
  package.json
Labels: [Type] Enhancement

#3597 Release 3.5.1
  changelog.txt
  includes/class-sensei-course.php
  includes/data-port/class-sensei-data-port-manager.php
  includes/data-port/class-sensei-import-job.php
  includes/rest-api/class-sensei-rest-api-import-controller.php
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
Labels: [Type] Maintenance

#3601 Remove dist folder before the build
  package.json
Labels: [Type] Maintenance

#3605 Sort course filter on Lessons page in alphabetical order
  includes/class-sensei-admin.php
Labels: [Type] Enhancement

#3606 Show scheduled lessons in Prerequisite dropdown
  includes/class-sensei-lesson.php
Labels: [Type] Enhancement

#3609 Show scheduled lessons in Prerequisite dropdown
  includes/class-sensei-lesson.php
Labels: [Type] Enhancement

#3608 Add term object to page imitator
  includes/unsupported-theme-handlers/class-sensei-unsupported-theme-handler-course-archive.php
Labels: [Type] Bug

#3617 Multiple choice question is correct only when all right answers are checked
  assets/js/grading-general.js
  includes/class-sensei-grading.php
Labels: [Type] Bug

#3616 Fix admin teacher check
  includes/class-sensei-teacher.php
Labels: [Type] Bug

#3589 Don't overwrite lesson meta with defaults on update
  includes/class-sensei-lesson.php
Labels: [Type] Bug

#3621 Allow for different context when getting course structure
  assets/blocks/course-outline/store.js
  includes/blocks/class-sensei-course-outline-block.php
  includes/class-sensei-course-structure.php
  includes/class-sensei-course.php
  includes/class-sensei-modules.php
  includes/rest-api/class-sensei-rest-api-course-structure-controller.php
  tests/unit-tests/rest-api/test-class-sensei-rest-api-course-structure-controller.php
  tests/unit-tests/test-class-sensei-course-structure.php
Labels: Deprecation

#3633 Fix deprecated function call
  includes/class-sensei-updates.php
Labels: [Type] Bug

#3632 Fix quiz settings
  includes/class-sensei-admin.php
  includes/class-sensei-lesson.php
Labels: [Type] Bug

#3631 Add filter login required
  includes/class-sensei.php
  includes/sensei-functions.php
Labels: Hooks, [Type] Bug

#3649 Hide modules and lessons meta boxes in course editor when outline is added
  assets/blocks/course-outline/course-block/edit.js
  includes/class-sensei-modules.php
Labels: [Type] Enhancement

#3647 Handle block based and legacy single course frontend rendering
  includes/blocks/class-sensei-course-outline-block.php
  includes/class-sensei-course.php
  includes/class-sensei-messages.php
  includes/class-sensei-modules.php
  includes/class-sensei-posttypes.php
  includes/class-sensei.php
  includes/hooks/template.php
Labels: Hooks

#3654 Stop course duplication on teacher update
  includes/class-sensei-lesson.php
  includes/class-sensei-teacher.php
Labels: [Type] Bug

#3646 Update modules content overflow to auto
  assets/blocks/course-outline/frontend.js
  assets/blocks/course-outline/module-block/edit.js
  assets/blocks/course-outline/style.scss
  includes/blocks/class-sensei-course-outline-block.php
  includes/class-sensei-frontend.php
  package-lock.json
  package.json
Labels: [Type] Bug
