Repository Automattic/sensei, pull requests merged in 2020-05, with the labels that each got.

#3092 Bring 3.0.1 into master and set version to 3.1.0-dev
  changelog.txt
  includes/class-sensei-data-cleaner.php
  includes/class-sensei-settings.php
  includes/class-sensei-updates.php
  includes/class-sensei.php
  includes/enrolment/class-sensei-course-enrolment.php
  lang/sensei-lms.pot
  package.json
  readme.txt
  scripts/linter-ci
  sensei-lms.php
Labels: [Type] Maintenance

#3094 Add Sensei and WCPC version directly in usage stats
  includes/class-sensei-usage-tracking.php
Labels: [Status] Product Reviewed

#3067 Generate hook documentation and publish to GitHub pages
  .github/hookdoc-tmpl/README.md
  .github/hookdoc-tmpl/layout.tmpl
  .github/hookdoc-tmpl/static/styles.css
  .github/workflows/build-docs.yml
  .gitignore
  hookdoc-conf.json
  includes/class-sensei-course.php
  package-lock.json
  package.json
Labels: [Type] Maintenance

#3093 Add help tab on Courses page to re-launch setup wizard
  includes/admin/class-sensei-onboarding.php
  includes/class-sensei.php
  tests/unit-tests/admin/test-class-sensei-onboarding.php
Labels: [Status] Product Reviewed, [Type] Enhancement

#3082 Onboarding Wizard: Add Welcome page
  assets/onboarding/_variables.scss
  assets/onboarding/index.jsx
  assets/onboarding/steps.jsx
  assets/onboarding/style.scss
  assets/onboarding/use-onboarding-api.js
  assets/onboarding/welcome/index.jsx
  assets/onboarding/welcome/usage-modal.jsx
  assets/onboarding/wp-colors.scss
  includes/admin/class-sensei-onboarding-pages.php
  includes/admin/class-sensei-onboarding.php
  includes/class-sensei-admin.php
  includes/class-sensei-assets.php
  includes/class-sensei-autoloader.php
  includes/class-sensei-settings.php
  includes/class-sensei-usage-tracking.php
  includes/class-sensei.php
  package.json
  tests/unit-tests/admin/test-class-sensei-onboarding-api.php
Labels: Deprecation, [Status] Product Reviewed

#3104 Fix Sensei capabilities in the tests
  tests/bootstrap.php
Labels: [Type] Maintenance

#3101 Add Onboarding Wiz. Purpose step
  assets/onboarding/_variables.scss
  assets/onboarding/purpose/index.jsx
  assets/onboarding/steps.jsx
  assets/onboarding/style.scss
  assets/onboarding/wp-colors.scss
Labels: [Status] Product Reviewed

#3103 Fix to show help tab only for sensei manager users
  includes/admin/class-sensei-onboarding.php
  tests/unit-tests/admin/test-class-sensei-onboarding.php
Labels: [Status] Product Reviewed, [Type] Bug

#3096 Add setup wizard notice
  assets/css/activation.scss
  includes/admin/class-sensei-onboarding.php
  includes/class-sensei-data-cleaner.php
  includes/class-sensei.php
  tests/unit-tests/admin/test-class-sensei-onboarding.php
Labels: [Status] Product Reviewed, [Type] Enhancement

#3117 Fix setup wizard navigation naming and documentation
  assets/onboarding/index.jsx
  assets/onboarding/navigation/index.jsx
Labels: [Status] Product Reviewed, [Type] Bug

#3118 Refactor WooCommerce help tab prevention in Sensei pages
  includes/admin/class-sensei-onboarding.php
  tests/unit-tests/admin/test-class-sensei-onboarding.php
Labels: [Status] Product Reviewed, [Type] Bug

#3119 Fix setup wizard page title
  includes/admin/class-sensei-onboarding.php
Labels: [Status] Product Reviewed, [Type] Bug

#3102 Add redirect to setup wizard after plugin activation
  includes/admin/class-sensei-onboarding.php
  includes/class-sensei-data-cleaner.php
  includes/class-sensei.php
  tests/unit-tests/admin/test-class-sensei-onboarding.php
Labels: [Status] Product Reviewed, [Type] Enhancement

#3155 Remove setup notices
  assets/css/activation.scss
  includes/class-sensei-admin.php
  includes/class-sensei-data-cleaner.php
  includes/class-sensei.php
  includes/lib/usage-tracking/class-usage-tracking-base.php
  includes/lib/usage-tracking/tests/test-class-usage-tracking.php
  webpack.config.js
Labels: Deprecation, [Status] Product Reviewed

#3167 Remove mailing list signup modal
  assets/css/admin/email-signup.scss
  assets/js/admin/email-signup.js
  includes/class-sensei-autoloader.php
  includes/class-sensei-data-cleaner.php
  includes/class-sensei.php
  includes/email-signup/class-sensei-email-signup-form.php
  includes/email-signup/template.php
  webpack.config.js
Labels: Deprecation

#3157 Add setup wizard data manager
  assets/onboarding/data/actions.js
  assets/onboarding/data/actions.test.js
  assets/onboarding/data/constants.js
  assets/onboarding/data/controls.js
  assets/onboarding/data/controls.test.js
  assets/onboarding/data/index.js
  assets/onboarding/data/reducer.js
  assets/onboarding/data/reducer.test.js
  assets/onboarding/data/selectors.js
  assets/onboarding/data/selectors.test.js
  assets/onboarding/index.jsx
  assets/onboarding/style.scss
  assets/onboarding/welcome/index.jsx
  package-lock.json
  package.json
Labels: [Type] Enhancement

#3121 Add setup wizard Features step - with mocked data
  assets/onboarding/_variables.scss
  assets/onboarding/features/check-icon.jsx
  assets/onboarding/features/check-icon.test.js
  assets/onboarding/features/confirmation-modal.jsx
  assets/onboarding/features/confirmation-modal.test.js
  assets/onboarding/features/feature-description.jsx
  assets/onboarding/features/feature-description.test.js
  assets/onboarding/features/feature-status.jsx
  assets/onboarding/features/feature-status.test.js
  assets/onboarding/features/features-selection.jsx
  assets/onboarding/features/features-selection.test.js
  assets/onboarding/features/index.jsx
  assets/onboarding/features/index.test.js
  assets/onboarding/features/installation-feedback.jsx
  assets/onboarding/features/installation-feedback.test.js
  assets/onboarding/steps.jsx
  assets/onboarding/style.scss
  assets/onboarding/welcome/index.jsx
  assets/onboarding/wp-colors.scss
  package-lock.json
  package.json
Labels: [Status] Product Reviewed, [Type] Enhancement

#3172 Fix data API URL
  assets/onboarding/data/actions.js
  assets/onboarding/data/actions.test.js
  assets/onboarding/data/constants.js
Labels: [Type] Enhancement

#3175 Update features selection to don't check when it's installed
  assets/onboarding/features/features-selection.jsx
Labels: [Type] Enhancement

#3176 Fetch sensei extensions from sensei site
  assets/onboarding/data/actions.js
  assets/onboarding/data/actions.test.js
  assets/onboarding/data/normalizer.js
  assets/onboarding/data/normalizer.test.js
  assets/onboarding/data/reducer.js
  assets/onboarding/features/confirmation-modal.jsx
  assets/onboarding/features/confirmation-modal.test.js
  assets/onboarding/features/feature-description.jsx
  assets/onboarding/features/feature-description.test.js
  assets/onboarding/features/features-selection.jsx
  assets/onboarding/features/features-selection.test.js
  assets/onboarding/features/index.jsx
  assets/onboarding/features/index.test.js
  assets/onboarding/features/installation-feedback.jsx
  assets/onboarding/features/installation-feedback.test.js
  assets/onboarding/index.jsx
  includes/admin/class-sensei-extensions.php
  includes/admin/class-sensei-onboarding.php
  includes/rest-api/class-sensei-rest-api-setup-wizard-controller.php
  tests/bootstrap.php
  tests/unit-tests/admin/test-class-sensei-onboarding-api.php
  tests/unit-tests/admin/test-class-sensei-onboarding.php
Labels: [Type] Enhancement

#3182 Add filter for enabling/disabling enrolment related background jobs
  includes/enrolment/class-sensei-course-enrolment.php
  includes/enrolment/class-sensei-enrolment-job-scheduler.php
Labels: Hooks

#3184 Add feature submit data flow
  assets/onboarding/data/actions.js
  assets/onboarding/data/actions.test.js
  assets/onboarding/data/use-setup-wizard-step.js
  assets/onboarding/features/confirmation-modal.jsx
  assets/onboarding/features/confirmation-modal.test.js
  assets/onboarding/features/index.jsx
  assets/onboarding/features/index.test.js
  assets/onboarding/purpose/index.jsx
  assets/onboarding/welcome/index.jsx
Labels: [Type] Enhancement

#3116 Add precommit hooks which run linters and JS formatter
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: [Type] Maintenance

#3183 Remove mass database invalidation of enrolment results on course recalculation
  includes/enrolment/class-sensei-course-enrolment.php
  includes/enrolment/class-sensei-enrolment-course-calculation-job.php
  tests/unit-tests/enrolment/test-class-sensei-course-enrolment.php
  tests/unit-tests/enrolment/test-class-sensei-enrolment-course-calculation-job.php
Labels: [Type] Enhancement

#3196 Add pre-commit hook to lint only newer PHP files
  package.json
  scripts/linter-new-php
Labels: [Type] Maintenance

#3156 Add setup Wizard ready step
  assets/onboarding/_variables.scss
  assets/onboarding/data/actions.js
  assets/onboarding/data/reducer.js
  assets/onboarding/features/index.jsx
  assets/onboarding/helpers/format-string.js
  assets/onboarding/ready/index.jsx
  assets/onboarding/ready/index.test.js
  assets/onboarding/ready/mailinglist-signup-form.jsx
  assets/onboarding/steps.jsx
  assets/onboarding/style.scss
  assets/onboarding/wp-colors.scss
  includes/admin/class-sensei-onboarding.php
  includes/rest-api/class-sensei-rest-api-setup-wizard-controller.php
  tests/unit-tests/admin/test-class-sensei-onboarding-api.php
Labels: [Status] Product Reviewed

#3181 Add tracking event for Setup Wizard purpose step
  includes/rest-api/class-sensei-rest-api-setup-wizard-controller.php
  tests/unit-tests/admin/test-class-sensei-onboarding-api.php
Labels: [Status] Product Reviewed

#3064 Add "Date Completed" field to the learner management page
  includes/admin/class-sensei-learners-main.php
Labels: [Status] Product Reviewed
