Repository Automattic/sensei, pull requests merged in 2020-10, with the labels that each got.

#3665 Fix module selector when animation is turned off
  assets/blocks/course-outline/frontend.js
Labels: [Type] Bug

#3652 Log when a course is updated
  includes/class-sensei-course.php
Labels: [Type] Enhancement

#3676 Focus the module title input when adding a new module
  assets/blocks/course-outline/course-block/edit.js
  assets/blocks/course-outline/module-block/edit.js
  assets/blocks/course-outline/use-block-creator.js
Labels: [Type] Enhancement

#3673 Fix max file upload display
  includes/class-sensei-question.php
Labels: [Type] Bug

#3664 Refactor lesson reorder page to use `Sensei_Course_Structure`
  assets/css/admin-custom.css
  assets/js/admin/ordering.js
  includes/class-sensei-admin.php
  includes/class-sensei-course-structure.php
  includes/class-sensei-lesson.php
  tests/unit-tests/test-class-lesson.php
Labels: Deprecation, [Type] Enhancement

#3672 Update module reorder to use Sensei_Course_Structure
  assets/css/modules-admin.css
  assets/js/modules-admin.js
  includes/class-sensei-admin.php
  includes/class-sensei-course-structure.php
  includes/class-sensei-modules.php
  tests/unit-tests/test-class-sensei-course-structure.php
Labels: [Type] Enhancement

#3709 Add validation to post object before logging the course update.
  includes/class-sensei-course.php
Labels: [Type] Bug

#3710 Hide modules description in the frontend when there is no description
  includes/blocks/class-sensei-course-outline-module-block.php
Labels: [Type] Enhancement

#3707 Change outline block error messages
  assets/blocks/course-outline/store.js
  includes/class-sensei-course-structure.php
  tests/unit-tests/test-class-sensei-course-structure.php
Labels: [Type] Enhancement

#3722 Refactor modules collapsing script to use domReady
  assets/blocks/course-outline/frontend.js
  package-lock.json
  package.json
Labels: [Type] Enhancement

#3721 Add a message for course outline block without published content
  includes/blocks/class-sensei-course-outline-course-block.php
  tests/unit-tests/test-class-sensei-course-outline-block.php
Labels: [Type] Enhancement

#3723 Add module link to the course outline block when the module has a description
  assets/blocks/course-outline/module-block/module-block.scss
  includes/blocks/class-sensei-course-outline-module-block.php
  tests/unit-tests/test-class-sensei-course-outline-block.php
Labels: [Type] Bug

#3728 Fix preferred assert method: change to assertSame
  tests/README.md
Labels: [Type] Maintenance

#3727 Add block checks to the `course_update` event log
  includes/class-sensei-course.php
Labels: Logging, [Type] Enhancement

#3734 Add new blocks to the course CPT template
  includes/blocks/class-sensei-course-outline-block.php
Labels: [Type] Enhancement

#3732 Add lesson preview badge to the course outline
  assets/blocks/course-outline/data.js
  assets/blocks/course-outline/data.test.js
  assets/blocks/course-outline/lesson-block/edit.js
  assets/blocks/course-outline/lesson-block/edit.test.js
  assets/blocks/course-outline/lesson-block/lesson-block.scss
  includes/blocks/class-sensei-course-outline-course-block.php
  includes/blocks/class-sensei-course-outline-lesson-block.php
  includes/blocks/class-sensei-course-outline-module-block.php
  includes/class-sensei-course-structure.php
  tests/unit-tests/test-class-sensei-course-outline-block.php
  tests/unit-tests/test-class-sensei-course-structure.php
Labels: [Type] Enhancement
