Repository Automattic/sensei, pull requests merged in 2020-02, with the labels that each got.

#2862 Block frontend manual enrollment if there is a handling provider
  includes/class-sensei-course-enrolment-manager.php
  tests/framework/trait-sensei-course-enrolment-test-helpers.php
  tests/unit-tests/test-class-sensei-course-enrolment-manager.php
Labels: [Status] Product Reviewed

#2899 Add a filter for the course archive page URL
  includes/class-sensei-course.php
Labels: Hooks

#2888 Introduce provider state storage and stored status providers
  includes/class-sensei-data-cleaner.php
  includes/enrolment/class-sensei-course-enrolment-manager.php
  includes/enrolment/class-sensei-course-enrolment-stored-status-provider.php
  includes/enrolment/class-sensei-course-enrolment.php
  includes/enrolment/class-sensei-course-manual-enrolment-provider.php
  includes/enrolment/class-sensei-enrolment-provider-state-store.php
  includes/enrolment/class-sensei-enrolment-provider-state.php
  tests/framework/enrolment-providers/class-sensei-test-enrolment-provider-stateful-initially-false.php
  tests/framework/enrolment-providers/class-sensei-test-enrolment-provider-stateful-initially-true.php
  tests/framework/trait-sensei-course-enrolment-manual-test-helpers.php
  tests/framework/trait-sensei-course-enrolment-test-helpers.php
  tests/unit-tests/enrolment/test-class-sensei-course-enrolment-stored-status-provider.php
  tests/unit-tests/enrolment/test-class-sensei-course-enrolment.php
  tests/unit-tests/enrolment/test-class-sensei-course-manual-enrolment-provider.php
  tests/unit-tests/enrolment/test-class-sensei-enrolment-calculation-scheduler.php
  tests/unit-tests/enrolment/test-class-sensei-enrolment-provider-state-store.php
  tests/unit-tests/enrolment/test-class-sensei-enrolment-provider-state.php
Labels: [Status] Product Reviewed

#2886 Tweaks to question media escaping to fix media output
  includes/class-sensei-question.php
Labels: Questions, [Status] Product Reviewed, [Type] Maintenance

#2883 Test and fix lesson ordering on course duplication
  includes/class-sensei-admin.php
  tests/unit-tests/test-class-admin.php
Labels: [Status] Product Reviewed

#2891 Add file watch & live browser reload options to Gulp
  .gitignore
  gulpfile.js
  package-lock.json
  package.json
Labels: [Status] Product Reviewed

#2911 Override queried_object in $wp_query when rendering a dummy post
  includes/unsupported-theme-handlers/class-sensei-unsupported-theme-handler-page-imitator.php
Labels: [Status] Product Reviewed

#2892 Update gulp-sass so that it doesn't install an outdated node-sass
  assets/css/frontend/sensei.scss
  package-lock.json
  package.json
Labels: [Status] Product Reviewed

#2918 Add module admin scripts on course edit page
  includes/class-sensei-modules.php
Labels: [Status] Product Reviewed

#2920 Don't touch title in the_title hook for quizes when its not a quiz
  includes/class-sensei-quiz.php
Labels: [Status] Product Reviewed

#2919 Set lesson status to ungraded after reset
  assets/js/grading-general.js
  assets/js/grading-general.min.js
  includes/class-sensei-grading.php
Labels: [Status] Product Reviewed

#2910 Replace typeof causing Babel runtime dependency
  assets/js/admin/lesson-quick-edit.js
  assets/js/admin/lesson-quick-edit.min.js
Labels: [Status] Product Reviewed

#2917 Fix lessons bulk editing Sensei properties
  assets/js/admin/lesson-bulk-edit.js
  assets/js/admin/lesson-bulk-edit.min.js
  includes/class-sensei-lesson.php
Labels: [Status] Product Reviewed

#2922 Fix issue with teachers not being able to enrol students
  includes/admin/class-sensei-learner-management.php
Labels: [Status] Product Reviewed

#2898 Remove enrolments on user deletion
  includes/class-sensei-admin.php
  includes/class-sensei-learner.php
  includes/class-sensei-utils.php
  includes/class-sensei.php
  tests/unit-tests/test-class-learner.php
Labels: Deprecation, [Status] Product Reviewed, [Type] Enhancement

#2902 Improve theme support for TwentyTwenty
  assets/css/frontend/sensei.css
  assets/css/frontend/sensei.scss
  assets/css/modules-frontend.css
  assets/css/modules-frontend.scss
  includes/sensei-functions.php
  templates/archive-course.php
Labels: Templates, [Status] Product Reviewed
