Repository Automattic/sensei, pull requests merged in 2020-04, with the labels that each got.

#3005 Fix pot file generation
  gulpfile.js
  package-lock.json
  package.json
Labels: [Type] Maintenance

#3004 Release 3.0.0 Beta 1
  changelog.txt
  includes/class-sensei.php
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
Labels: [Type] Maintenance

#3019 Add failsafes on update version check
  includes/class-sensei.php
  tests/unit-tests/test-class-sensei.php
Labels: Deprecation

#3011 Add filter to side-step Sensei's enrolment functionality
  includes/admin/class-sensei-learners-admin-bulk-actions-controller.php
  includes/admin/class-sensei-learners-admin-bulk-actions-view.php
  includes/admin/class-sensei-learners-main.php
  includes/enrolment/class-sensei-course-enrolment.php
Labels: Hooks, [Type] Enhancement

#3026 Release 3.0.0 Beta 2
  changelog.txt
  gulpfile.js
  includes/class-sensei.php
  lang/sensei-lms.pot
  sensei-lms.php
Labels: [Type] Maintenance

#3029 Update course calculation job to paginate using last calculated user ID
  includes/enrolment/class-sensei-course-enrolment-manager.php
  includes/enrolment/class-sensei-course-enrolment.php
  includes/enrolment/class-sensei-enrolment-course-calculation-job.php
  includes/enrolment/class-sensei-enrolment-job-scheduler.php
  tests/unit-tests/enrolment/test-class-sensei-course-enrolment-manager.php
  tests/unit-tests/enrolment/test-class-sensei-course-enrolment.php
  tests/unit-tests/enrolment/test-class-sensei-enrolment-course-calculation-job.php
Labels: Hooks

#3035 Fire actions on enrolment status change and manual enrolment status change
  includes/enrolment/class-sensei-course-enrolment.php
  includes/enrolment/class-sensei-course-manual-enrolment-provider.php
Labels: Hooks

#3061 Release 3.0.0 Beta 3
  changelog.txt
  includes/class-sensei.php
  lang/sensei-lms.pot
  sensei-lms.php
Labels: [Type] Maintenance

#2864 Set the initial version of the manual provider
  includes/enrolment/class-sensei-course-manual-enrolment-provider.php
Labels: [Status] Product Reviewed

#3068 Release 3.0.0 beta 4
  changelog.txt
  includes/class-sensei.php
  sensei-lms.php
Labels: [Type] Maintenance

#2972 Update the repo templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [Pri] Low, [Type] Maintenance

#3075 Revert release of beta 5
  includes/class-sensei.php
  sensei-lms.php
Labels: [Type] Maintenance

#3081 Update Sensei version to 3.0.0
  changelog.txt
  includes/class-sensei.php
  sensei-lms.php
Labels: [Type] Maintenance

#3008 Update question title when changing question type
  assets/js/lesson-metadata.js
  assets/js/lesson-metadata.min.js
Labels: [Pri] Low, [Type] Bug

#3016 Fix deprecated argument being used by `get_user_question_answer` and `get_user_question_grade` methods
  includes/class-sensei-quiz.php
  tests/unit-tests/test-class-quiz.php
Labels: Quizzes, [Type] Bug

#3088 Build in Travis on release branches
  .travis.yml
Labels: [Type] Maintenance

#3089 Allow for non-master base branches on PHPCS checks
  scripts/linter-ci
Labels: [Type] Maintenance

#3091 Release 3.0.1
  changelog.txt
  lang/sensei-lms.pot
  package.json
  readme.txt
  sensei-lms.php
Labels: [Type] Maintenance

#3085 Add onboarding navigation
  .eslintrc.js
  assets/onboarding/index.jsx
  assets/onboarding/navigation/index.jsx
  assets/onboarding/query-string-router/index.jsx
  assets/onboarding/query-string-router/index.test.js
  assets/onboarding/query-string-router/route.jsx
  assets/onboarding/query-string-router/route.test.js
  assets/onboarding/query-string-router/url-functions.js
  assets/onboarding/query-string-router/url-functions.test.js
  assets/onboarding/steps.jsx
  assets/react-hooks/index.js
  assets/react-hooks/use-event-listener.js
  assets/react-hooks/use-event-listener.test.js
  assets/react-hooks/use-wp-admin-fullscreen.js
  assets/react-hooks/use-wp-admin-fullscreen.test.js
  assets/tests-helper/functions.js
  package-lock.json
  package.json
Labels: [Type] Enhancement
