Repository Automattic/sensei, pull requests merged in 2020-06, with the labels that each got.

#3240 Use rootDir in Jest ignore patterns for Travis CI compatibility
  jest.config.js
  package.json
Labels: [Type] Maintenance

#3238 Fix missing Fontawesome icons
  assets/css/_grid.scss
  assets/css/fontawesome.scss
  assets/css/frontend.scss
  assets/css/settings.scss
  includes/class-sensei-frontend.php
  webpack.config.js
Labels: [Status] Product Reviewed

#3239 Fix features installation
  assets/onboarding/features/feature-status.jsx
  includes/admin/class-sensei-onboarding.php
Labels: [Type] Enhancement

#3211 Add/import file form
  assets/data-port/import.jsx
  assets/data-port/import/upload-level/data.js
  assets/data-port/import/upload-level/index.jsx
  assets/data-port/import/upload-level/index.test.js
  assets/data-port/import/upload/index.jsx
  assets/data-port/import/upload/index.test.js
  assets/data-port/notice.jsx
  assets/data-port/stepper/index.jsx
  assets/data-port/style.scss
  includes/data-port/class-sensei-data-port-job.php
  includes/data-port/class-sensei-import.php
  package-lock.json
  package.json
Labels: [Status] Product Reviewed

#3227 Add exit link to Setup Wizard ready step
  assets/onboarding/ready/index.jsx
  assets/onboarding/style.scss
  assets/onboarding/welcome/index.jsx
  assets/onboarding/wp-colors.scss
Labels: [Status] Product Reviewed

#3198 Integrate store state with stepper navigation
  assets/onboarding/data/actions.js
  assets/onboarding/data/actions.test.js
  assets/onboarding/data/reducer.js
  assets/onboarding/data/reducer.test.js
  assets/onboarding/data/selectors.js
  assets/onboarding/data/selectors.test.js
  assets/onboarding/features/index.test.js
  assets/onboarding/index.jsx
  assets/onboarding/navigation/index.jsx
  assets/onboarding/query-string-router/index.jsx
  assets/onboarding/query-string-router/index.test.js
  assets/onboarding/query-string-router/route.jsx
  assets/onboarding/query-string-router/route.test.js
  assets/onboarding/steps.jsx
  includes/rest-api/class-sensei-rest-api-setup-wizard-controller.php
  tests/unit-tests/admin/test-class-sensei-onboarding-api.php
Labels: [Status] Product Reviewed

#3219 Add scripts to build pot file with PHP and JS texts
  babel.makepot.js
  bin/pot-dist-references.js
  gulpfile.js
  includes/admin/class-sensei-onboarding.php
  package-lock.json
  package.json
Labels: [Type] Maintenance

#3145 Change "Lessons" to "Lesson" if there is only a single lesson in a course
  includes/class-sensei-course.php
  includes/class-sensei-frontend.php
  includes/shortcodes/class-sensei-legacy-shortcodes.php
  includes/template-functions.php
  templates/course-results/lessons.php
  templates/single-course/modules.php
  widgets/class-sensei-category-courses-widget.php
  widgets/class-sensei-course-component-widget.php
Labels: [Status] Product Reviewed

#3241 Filter extensions by dotorg in the Setup Wizard
  includes/admin/class-sensei-extensions.php
  includes/admin/class-sensei-onboarding.php
Labels: [Status] Product Reviewed

#3194 Add usage tracking to features step
  assets/onboarding/data/actions.js
  assets/onboarding/data/actions.test.js
  assets/onboarding/data/constants.js
  assets/onboarding/data/controls.js
  assets/onboarding/features/feature-description.jsx
  assets/onboarding/features/feature-description.test.js
  assets/onboarding/features/features-selection.jsx
  assets/onboarding/features/features-selection.test.js
  assets/onboarding/features/index.jsx
  assets/onboarding/features/index.test.js
  assets/onboarding/features/installation-feedback.jsx
  assets/onboarding/log-event.js
  assets/onboarding/log-event.test.js
  includes/admin/class-sensei-onboarding.php
  tests/unit-tests/admin/test-class-sensei-onboarding-api.php
Labels: [Status] Product Reviewed

#3226 Bundle Wordpress components css
  assets/onboarding/features/feature-description.jsx
  assets/onboarding/style.scss
  assets/onboarding/wp-colors.scss
  assets/shared/styles/_variables.scss
  assets/shared/styles/wc-components.scss
  assets/shared/styles/wp-components.scss
  includes/admin/class-sensei-onboarding.php
  includes/class-sensei-admin.php
  package-lock.json
  package.json
  postcss.config.js
  webpack.config.js
Labels: [Status] Product Reviewed

#3246 Add features installation tracking
  assets/onboarding/features/index.jsx
  assets/onboarding/features/index.test.js
  includes/admin/class-sensei-plugins-installation.php
Labels: [Type] Enhancement

#3263 Clear setup wizard user data option on uninstall
  includes/class-sensei-data-cleaner.php
Labels: Onboarding, [Type] Bug

#3265 Add submit to the ready step
  assets/setup-wizard/data/actions.js
  assets/setup-wizard/data/selectors.js
  assets/setup-wizard/data/selectors.test.js
  assets/setup-wizard/data/use-setup-wizard-step.js
  assets/setup-wizard/features/index.test.js
  assets/setup-wizard/index.jsx
  assets/setup-wizard/ready/index.jsx
  assets/setup-wizard/ready/index.test.js
Labels: Onboarding, [Type] Bug

#3266 Remove support link
  includes/class-sensei.php
Labels: Deprecation, [Type] Maintenance

#3285 Add WooCommerce extensions to setup wizard features
  includes/admin/class-sensei-setup-wizard.php
  includes/class-sensei-feature-flags.php
  tests/unit-tests/admin/test-class-sensei-setup-wizard.php
Labels: Onboarding, [Status] Product Reviewed, [Type] Enhancement

#3291 Importer: Consolidate process_line to parent file process class
  includes/data-port/import-tasks/class-sensei-import-courses.php
  includes/data-port/import-tasks/class-sensei-import-file-process-task.php
  includes/data-port/import-tasks/class-sensei-import-lessons.php
  includes/data-port/import-tasks/class-sensei-import-questions.php
  includes/data-port/models/class-sensei-data-port-model.php
  includes/data-port/models/class-sensei-data-port-question-model.php
  tests/framework/data-port/class-sensei-data-port-model-mock.php
  tests/framework/data-port/class-sensei-import-file-process-task-mock.php
Labels: [Type] Proposal

#3292 Ensure build script continues after tests run
  gulpfile.js
Labels: [Status] Queued, [Type] Maintenance

#3248 Deprecate sensei_the_excerpt function
  includes/template-functions.php
Labels: Deprecation, [Status] Product Reviewed

#3274 Fix incorrect parameter being passed to has_term function
  includes/class-sensei-modules.php
Labels: [Status] Product Reviewed

#3296 Remove source assets from package
  gulpfile.js
Labels: [Type] Maintenance

#3293 Add features installation feedback URL
  assets/setup-wizard/features/index.js
  assets/setup-wizard/features/index.test.js
  assets/setup-wizard/query-string-router/index.js
  assets/setup-wizard/query-string-router/url-functions.js
  assets/setup-wizard/query-string-router/url-functions.test.js
Labels: Onboarding, [Type] Enhancement

#3271 Use semantic heading structure on course results page
  assets/css/frontend.scss
  templates/course-results/lessons.php
Labels: Templates, [Status] Product Reviewed

#3275 Add "sensei" CSS class to all Sensei LMS pages
  includes/class-sensei-utils.php
  includes/sensei-functions.php
Labels: [Status] Product Reviewed

#3300 Fix duplicated translations with different translators
  includes/admin/class-sensei-learners-admin-bulk-actions-view.php
  includes/class-sensei-course.php
  includes/class-sensei-frontend.php
  includes/class-sensei-grading-user-quiz.php
  includes/class-sensei-lesson.php
  includes/class-sensei-messages.php
  includes/sensei-functions.php
  includes/shortcodes/class-sensei-legacy-shortcodes.php
  templates/course-results/lessons.php
  templates/emails/teacher-completed-course.php
Labels: [Type] Maintenance

#3297 Add woocommerce auto-installation for some features from Setup Wizard
  assets/setup-wizard/data/actions.test.js
  assets/setup-wizard/data/normalizer.js
  assets/setup-wizard/data/normalizer.test.js
  assets/setup-wizard/features/confirmation-modal.js
  assets/setup-wizard/features/confirmation-modal.test.js
  assets/setup-wizard/features/feature-description-utils.js
  assets/setup-wizard/features/feature-description-utils.test.js
  assets/setup-wizard/features/feature-description.js
  assets/setup-wizard/features/feature-description.test.js
  assets/setup-wizard/features/features-selection.js
  assets/setup-wizard/features/features-selection.test.js
  assets/setup-wizard/features/index.js
  assets/setup-wizard/features/index.test.js
  assets/setup-wizard/features/installation-feedback.js
  assets/setup-wizard/style.scss
  includes/admin/class-sensei-plugins-installation.php
  includes/admin/class-sensei-setup-wizard.php
  tests/unit-tests/admin/test-class-sensei-setup-wizard-api.php
  tests/unit-tests/admin/test-class-sensei-setup-wizard.php
Labels: Onboarding, [Type] Enhancement

#3304 Remove screenshot uploads of e2e failed tests
  .travis.yml
  tests/e2e/bin/upload-screenshots.sh
Labels: [Type] Maintenance

#3294 Add attachment utilies tests
  tests/unit-tests/data-port/test-class-sensei-data-port-utilites.php
Labels: [Type] Maintenance

#3080 Enable admins and lesson author to view quiz for lesson with a prerequisite
  includes/class-sensei-lesson.php
Labels: [Status] Product Reviewed

#3335 Release 3.2.0
  changelog.txt
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
Labels: [Type] Maintenance
