Repository Automattic/sensei, pull requests merged in 2020-08, with the labels that each got.

#3493 Add a script to add automatically the dist references to the pot file
  bin/pot-dist-references.js
  package-lock.json
  package.json
  scripts/pot-dist-references.js
  scripts/webpack/generate-chunks-map-plugin.js
  webpack.config.js
Labels: [Type] Maintenance

#3516 Change export cancel link to button
  assets/data-port/export/export-progress-page.js
Labels: Import / Export

#3513 Export lessons CSV
  includes/class-sensei-modules.php
  includes/class-sensei-utils.php
  includes/data-port/class-sensei-data-port-utilities.php
  includes/data-port/class-sensei-export-job.php
  includes/data-port/export-tasks/class-sensei-export-courses.php
  includes/data-port/export-tasks/class-sensei-export-lessons.php
  includes/data-port/export-tasks/class-sensei-export-questions.php
  includes/data-port/export-tasks/class-sensei-export-task.php
  tests/framework/data-port/trait-sensei-export-task-tests.php
  tests/framework/factories/class-sensei-factory.php
  tests/unit-tests/data-port/export-tasks/test-class-sensei-export-courses.php
  tests/unit-tests/data-port/export-tasks/test-class-sensei-export-lessons.php
  tests/unit-tests/data-port/test-class-sensei-data-port-utilites.php
Labels: Import / Export

#3521 Merge data port model with import model
  includes/data-port/import-tasks/class-sensei-import-file-process-task.php
  includes/data-port/models/class-sensei-data-port-model.php
  includes/data-port/models/class-sensei-import-model.php
  tests/framework/data-port/class-sensei-import-model-mock.php
  tests/unit-tests/data-port/models/test-class-sensei-import-model.php
Labels: Import / Export

#3537 Export the correct order when lessons belong to modules
  includes/class-sensei-modules.php
  includes/data-port/export-tasks/class-sensei-export-courses.php
  tests/unit-tests/data-port/export-tasks/test-class-sensei-export-courses.php
Labels: Import / Export

#3533 Add a return to the setup wizard post
  includes/rest-api/class-sensei-rest-api-setup-wizard-controller.php
Labels: [Type] Bug

#3538 Fix duplicated importing
  includes/data-port/class-sensei-data-port-job.php
  includes/data-port/class-sensei-data-port-manager.php
Labels: Import / Export, [Type] Bug

#3547 Bump WP versions for travis tests
  .travis.yml
Labels: [Type] Maintenance

#3543 Reverse the exported value of notifications
  includes/data-port/export-tasks/class-sensei-export-courses.php
  includes/data-port/models/class-sensei-data-port-course-schema.php
  sample-data/courses.csv
  tests/unit-tests/data-port/export-tasks/test-class-sensei-export-courses.php
Labels: Import / Export, [Status] Product Reviewed

#3555 Allow draft course prerequisites
  includes/class-sensei-course.php
Labels: Import / Export

#3551 Fix export question media
  includes/data-port/export-tasks/class-sensei-export-questions.php
  tests/unit-tests/data-port/export-tasks/test-class-sensei-export-questions.php
Labels: Import / Export, [Type] Bug

#3544 Remove test which enables tracking
  tests/e2e/specs/activate-and-setup/setup-wizard.test.js
Labels: [Type] Maintenance

#3550 Fix export question randomise
  includes/data-port/export-tasks/class-sensei-export-questions.php
  tests/unit-tests/data-port/export-tasks/test-class-sensei-export-questions.php
Labels: Import / Export, [Type] Bug

#3559 Make the error more descriptive when the attachment fetch request fails
  includes/data-port/class-sensei-data-port-utilities.php
Labels: Import / Export, [Pri] Low

#3558 Fix export answers order
  includes/class-sensei-lesson.php
  includes/class-sensei-question.php
  includes/data-port/export-tasks/class-sensei-export-questions.php
  tests/unit-tests/data-port/export-tasks/test-class-sensei-export-questions.php
Labels: Import / Export, [Status] Product Reviewed, [Type] Bug

#3563 Add prettier configuration
  .prettierrc.js
  package.json
Labels: [Type] Maintenance

#3572 Add eslint jsdoc alignment plugin
  .eslintrc.js
  assets/data-port/export/export-page.js
  assets/data-port/export/export-progress-page.js
  assets/data-port/export/store/actions.js
  assets/data-port/import/data/actions.js
  assets/data-port/import/data/controls.js
  assets/data-port/import/data/normalizer.js
  assets/data-port/import/data/reducer.js
  assets/data-port/import/data/selectors.js
  assets/data-port/import/done/done-page.js
  assets/data-port/import/done/import-log.js
  assets/data-port/import/done/import-success-results.js
  assets/data-port/import/import-progress/import-progress-page.js
  assets/data-port/import/upload-level/upload-level.js
  assets/data-port/import/upload/upload-page.js
  assets/data-port/notice.js
  assets/data-port/stepper/index.js
  assets/js/grading-general.js
  assets/js/lesson-metadata.js
  assets/setup-wizard/data/actions.js
  assets/setup-wizard/data/controls.js
  assets/setup-wizard/data/reducer.js
  assets/setup-wizard/data/selectors.js
  assets/setup-wizard/features/index.js
  assets/setup-wizard/features/installation-feedback.js
  assets/setup-wizard/log-event.js
  assets/setup-wizard/navigation/index.js
  assets/setup-wizard/query-string-router/index.js
  assets/setup-wizard/query-string-router/route.js
  assets/setup-wizard/query-string-router/url-functions.js
  assets/shared/helpers/format-string.js
  package-lock.json
  package.json
Labels: [Type] Maintenance
