Repository Automattic/sensei, pull requests merged in 2020-11, with the labels that each got.

#3726 Change course outline styling to distinguish lessons that belong to a module and lessons that do not
  assets/blocks/course-outline/course-block/block.json
  assets/blocks/course-outline/course-block/course-block.scss
  assets/blocks/course-outline/module-block/index.js
  assets/blocks/course-outline/module-block/module-block.scss
  assets/blocks/course-outline/style.editor.scss
Labels: [Type] Enhancement

#3754 Remove the temporary feature flag for the Course Outline features
  includes/blocks/class-sensei-blocks.php
  includes/blocks/class-sensei-course-blocks.php
  includes/class-sensei-course.php
  includes/class-sensei-feature-flags.php
Labels: [Type] Enhancement

#3757 Add Sensei block spacings
  assets/blocks/button/button.scss
  assets/blocks/contact-teacher/contact-teacher.scss
  assets/blocks/single-course.scss
  assets/blocks/take-course/take-course.scss
  assets/shared/styles/blocks.scss
  includes/blocks/class-sensei-block-contact-teacher.php
  includes/blocks/class-sensei-block-take-course.php
  includes/blocks/class-sensei-course-outline-course-block.php
  includes/blocks/class-sensei-course-progress-block.php
Labels: [Type] Enhancement

#3756 Update outline block editor to reflect the frontend
  assets/blocks/course-outline/style.editor.scss
Labels: [Type] Enhancement

#3762 Add custom filter for take course expansion
  includes/blocks/class-sensei-block-take-course.php
Labels: Hooks

#3781 Update default border radius in the progress bar
  assets/blocks/course-progress/settings.js
  assets/blocks/course-progress/style.scss
Labels: [Type] Enhancement

#3782 Add sensei blocks args filter
  includes/blocks/class-sensei-block-contact-teacher.php
  includes/blocks/class-sensei-block-take-course.php
  includes/blocks/class-sensei-blocks.php
  includes/blocks/class-sensei-course-outline-block.php
  includes/blocks/class-sensei-course-progress-block.php
Labels: [Type] Enhancement

#3783 Update block alignment component
  assets/blocks/button/settings-button.js
Labels: [Type] Enhancement

#3779 Hide course video meta box for new courses
  assets/js/admin/course-edit.js
Labels: [Type] Enhancement

#3766 Fix messages alignment in TwentyTwenty theme
  assets/css/frontend.scss
Labels: [Type] Enhancement

#3770 Fix readonly button
  assets/blocks/button/button-props.js
  assets/blocks/button/edit-button.js
  assets/blocks/button/save-button.js
Labels: [Type] Bug

#3789 Fix filter documentation
  includes/blocks/class-sensei-blocks.php
Labels: Hooks

#3791 Remove optional templates feature flag
  includes/class-sensei-feature-flags.php
  includes/class-sensei-templates.php
  includes/class-sensei-unsupported-themes.php
Labels: [Type] Enhancement

#3804 Move contact block up in the course post template
  includes/blocks/class-sensei-course-outline-block.php
Labels: [Type] Enhancement

#3812 Release 3.6.0 Beta 1
  changelog.txt
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
Labels: [Type] Maintenance

#3741 Add default theme colors to Course Outline Block
  assets/blocks/course-outline/module-block/block.json
  assets/blocks/course-outline/module-block/edit.js
  assets/blocks/course-outline/module-block/module-block.scss
  assets/blocks/course-outline/style.editor.scss
  assets/blocks/course-progress/block.json
  assets/blocks/course-progress/edit.js
  assets/react-hooks/probe-styles.js
  assets/react-hooks/probe-styles.test.js
  assets/shared/blocks/settings.js
  assets/shared/helpers/colors.js
  assets/shared/helpers/colors.test.js
  includes/blocks/class-sensei-block-helpers.php
  includes/blocks/class-sensei-course-outline-module-block.php
Labels: [Type] Enhancement

#3805 Add default theme color in the module border
  assets/blocks/course-outline/module-block/block.json
  assets/blocks/course-outline/module-block/edit.js
  assets/blocks/course-outline/module-block/module-block.scss
  includes/blocks/class-sensei-course-outline-module-block.php
Labels: [Type] Enhancement
