Repository Automattic/sensei, pull requests merged in 2020-03, with the labels that each got.

#2935 Update and clean up some build dependencies
  assets/css/activation.css
  assets/css/frontend/sensei.css
  assets/css/modules-frontend.css
  assets/css/settings.css
  gulpfile.js
  package-lock.json
  package.json
Labels: [Status] Product Reviewed

#2946 Update enrolled courses queries to use learner term
  includes/class-sensei-course.php
  includes/class-sensei-learner.php
  includes/enrolment/class-sensei-course-enrolment-manager.php
  includes/shortcodes/class-sensei-shortcode-courses.php
  includes/shortcodes/class-sensei-shortcode-featured-courses.php
  includes/shortcodes/class-sensei-shortcode-user-courses.php
  tests/unit-tests/test-class-learner.php
  widgets/class-sensei-course-component-widget.php
Labels: Deprecation

#2951 Remove usages of Sensei_Utils::user_started_course in templates
  includes/class-sensei-templates.php
  includes/class-sensei.php
  includes/hooks/template.php
  includes/template-functions.php
  templates/course-results.php
  templates/single-course/modules.php
Labels: Deprecation

#2958 Update usage tracking for enrolment count
  includes/class-sensei-usage-tracking-data.php
  tests/unit-tests/test-class-sensei-usage-tracking-data.php
Labels: [Status] Product Reviewed

#2967 Run plugin update checker and tasks on every request
  includes/class-sensei.php
Labels: Deprecation, [Status] Product Reviewed

#2952 Block access to module when not signed up
  includes/class-sensei-course.php
  includes/class-sensei-modules.php
  includes/class-sensei-posttypes.php
  includes/class-sensei-settings.php
  includes/hooks/template.php
  includes/sensei-functions.php
  includes/template-functions.php
  tests/bootstrap.php
  tests/unit-tests/enrolment/test-class-sensei-course-enrolment-manager.php
  tests/unit-tests/enrolment/test-class-sensei-course-enrolment-stored-status-provider.php
  tests/unit-tests/enrolment/test-class-sensei-course-enrolment.php
  tests/unit-tests/enrolment/test-class-sensei-enrolment-learner-calculation-job.php
  tests/unit-tests/enrolment/test-class-sensei-enrolment-provider-state-store.php
  tests/unit-tests/enrolment/test-class-sensei-enrolment-provider-state.php
  tests/unit-tests/test-class-course.php
  tests/unit-tests/test-class-learner.php
Labels: Hooks, [Status] Product Reviewed

#2971 Update version for templates modified in #2951
  templates/course-results.php
  templates/single-course/modules.php
Labels: [Type] Maintenance

#2953 Remove usages of Sensei_Utils::user_started_course from Lessons code
  includes/class-sensei-frontend.php
  includes/class-sensei-lesson.php
  includes/class-sensei-utils.php
  includes/hooks/template.php
  templates/course-results.php
Labels: Deprecation

#2965 Change/enrol users bulk management
  assets/vendor/jquery-modal-0.8.0/jquery.modal.css
  assets/vendor/jquery-modal-0.8.0/jquery.modal.min.css
  assets/vendor/jquery-modal-0.8.0/jquery.modal.min.js
  assets/vendor/jquery-modal-0.9.1/CHANGELOG.md
  assets/vendor/jquery-modal-0.9.1/LICENSE
  assets/vendor/jquery-modal-0.9.1/README.md
  assets/vendor/jquery-modal-0.9.1/jquery.modal.css
  assets/vendor/jquery-modal-0.9.1/jquery.modal.js
  assets/vendor/jquery-modal-0.9.1/jquery.modal.min.css
  assets/vendor/jquery-modal-0.9.1/jquery.modal.min.js
  includes/admin/class-sensei-learners-admin-bulk-actions-controller.php
  includes/admin/class-sensei-learners-admin-bulk-actions-view.php
  includes/class-sensei-admin.php
  includes/class-sensei-autoloader.php
  includes/class-sensei-db-query-learners.php
  includes/class-sensei-learners-admin-bulk-actions-controller.php
  includes/email-signup/class-sensei-email-signup-form.php
  tests/unit-tests/test-class-sensei-learners-admin-bulk-actions-controller.php
  tests/unit-tests/test-class-sensei-usage-tracking-data.php
Labels: Deprecation

#2974 Add missing deprecation notices
  includes/admin/class-sensei-learner-management.php
  includes/class-sensei-frontend.php
  includes/class-sensei-utils.php
  includes/template-functions.php
Labels: Deprecation

#2978 Fix Sensei_Utils::has_started_course call in template
  templates/course-results.php
Labels: [Status] Product Reviewed

#2985 Rename "Remove progress" bulk learner action
  includes/admin/class-sensei-learners-admin-bulk-actions-controller.php
Labels: [Status] Product Reviewed

#2981 Add/learner management enrol filter
  includes/admin/class-sensei-learner-management.php
  includes/admin/class-sensei-learners-main.php
  includes/class-sensei-autoloader.php
Labels: Deprecation

#2988 Fix hook replacement name
  includes/admin/class-sensei-learners-main.php
Labels: [Status] Product Reviewed

#2987 Add learner management filter for manually enrolled users
  includes/admin/class-sensei-learners-main.php
Labels: [Status] Product Reviewed

#2986 Add deprecation warning to user_started_course
  includes/class-sensei-utils.php
Labels: [Type] Maintenance

#2979 Deprecate filters used only by legacy WCPC memberships
  includes/class-sensei-course.php
Labels: Deprecation

#2996 Learner Management: Fix learner filters when no users should be returned
  includes/admin/class-sensei-learners-main.php
Labels: [Status] Product Reviewed

#2882 Only enqueue user-dashboard.js where required.
  includes/class-sensei-frontend.php
  includes/class-sensei-learner-profiles.php
  includes/shortcodes/class-sensei-legacy-shortcodes.php
Labels: [Status] Product Reviewed

#2999 Add new contributors to Sensei
  readme.txt
Labels: [Type] Maintenance

#2973 Allow frontend enrolment form to be handled elsewhere
  includes/class-sensei-frontend.php
  includes/enrolment/class-sensei-enrolment-provider-state.php
  includes/template-functions.php
Labels: Hooks, [Status] Product Reviewed

#2991 Split scheduler to seperate classes for easier testing
  includes/background-jobs/class-sensei-background-job-interface.php
  includes/background-jobs/class-sensei-scheduler-action-scheduler.php
  includes/background-jobs/class-sensei-scheduler-interface.php
  includes/background-jobs/class-sensei-scheduler-wp-cron.php
  includes/background-jobs/class-sensei-scheduler.php
  includes/class-sensei-autoloader.php
  includes/class-sensei.php
  includes/enrolment/class-sensei-enrolment-course-calculation-job.php
  includes/enrolment/class-sensei-enrolment-job-scheduler.php
  includes/enrolment/class-sensei-enrolment-learner-calculation-job.php
  phpcs.xml.dist
  tests/bootstrap.php
  tests/framework/actionscheduler-mocks.php
  tests/framework/class-sensei-background-job-stub.php
  tests/framework/class-sensei-scheduler-shim.php
  tests/framework/trait-sensei-scheduler-test-helpers.php
  tests/unit-tests/background-jobs/test-class-sensei-scheduler-action-scheduler.php
  tests/unit-tests/background-jobs/test-class-sensei-scheduler-wp-cron.php
  tests/unit-tests/background-jobs/test-class-sensei-scheduler.php
  tests/unit-tests/enrolment/test-class-sensei-course-enrolment-manager.php
  tests/unit-tests/enrolment/test-class-sensei-course-enrolment.php
  tests/unit-tests/enrolment/test-class-sensei-enrolment-course-calculation-job.php
  tests/unit-tests/enrolment/test-class-sensei-enrolment-job-scheduler.php
Labels: Hooks
