Repository Automattic/sensei, pull requests merged in 2020-07, with the labels that each got.

#3333 Fix lessons classes
  includes/class-sensei-lesson.php
  includes/hooks/template.php
  includes/template-functions.php
Labels: [Type] Bug

#3342 Add passmark range validation
  includes/data-port/models/class-sensei-data-port-lesson-schema.php
  tests/unit-tests/data-port/models/test-class-sensei-data-port-lesson-model.php
Labels: [Type] Enhancement

#3340 Add importer link in the setup wizard
  assets/setup-wizard/ready/index.js
Labels: [Type] Enhancement

#3349 Add assets js files to the package
  gulpfile.js
Labels: [Type] Enhancement

#3344 Fix upload levels notice style
  assets/data-port/import/upload-level/upload-level.js
  assets/data-port/import/upload/upload-page.scss
  assets/data-port/style.scss
Labels: [Type] Bug

#3354 Fix lesson passmark test
  tests/unit-tests/data-port/models/test-class-sensei-data-port-lesson-model.php
Labels: [Type] Bug

#3350 Update event name on import button from setup wizard
  assets/setup-wizard/ready/index.js
Labels: [Type] Enhancement

#3356 Fix import PHPDocs
  includes/data-port/class-sensei-data-port-job.php
  includes/data-port/class-sensei-data-port-task.php
  includes/data-port/class-sensei-import-job.php
  includes/rest-api/class-sensei-rest-api-data-port-controller.php
Labels: [Type] Maintenance

#3348 Add import submenu tracking
  assets/js/admin/event-logging.js
  includes/class-sensei-admin.php
Labels: [Status] Product Reviewed, [Type] Enhancement

#3345 Update phpunit docs
  tests/README.md
Labels: [Type] Maintenance

#3358 Add import attachments validation
  includes/data-port/class-sensei-data-port-utilities.php
  includes/data-port/class-sensei-import-job.php
  includes/data-port/models/class-sensei-data-port-course-schema.php
  includes/data-port/models/class-sensei-data-port-lesson-schema.php
  includes/data-port/models/class-sensei-data-port-question-schema.php
  includes/data-port/models/class-sensei-data-port-schema.php
  includes/data-port/models/class-sensei-import-model.php
  includes/data-port/models/class-sensei-import-question-model.php
  tests/unit-tests/data-port/test-class-sensei-data-port-utilites.php
Labels: [Type] Enhancement

#3347 Add/filter for user courses
  includes/class-sensei-learner.php
Labels: Hooks

#3369 Update filter name for consistency
  includes/class-sensei-learner.php
Labels: Hooks

#3365 Add BOM removal
  includes/data-port/class-sensei-import-csv-reader.php
  tests/framework/data-port/data-files/test_csv_reader_with_bom.csv
  tests/unit-tests/data-port/test-class-sensei-import-csv-reader.php
Labels: [Type] Enhancement

#3377 Log when an import job completes
  includes/data-port/class-sensei-data-port-job.php
  includes/data-port/class-sensei-data-port-manager.php
  tests/unit-tests/data-port/test-class-sensei-data-port-manager.php
Labels: Hooks

#3366 Log when the Continue button is clicked on the Import Content page
  assets/data-port/import/data/selectors.js
  assets/data-port/import/data/selectors.test.js
  assets/data-port/import/upload/index.js
Labels: Logging, [Type] Enhancement

#3364 Add delimiter detection
  includes/data-port/class-sensei-import-csv-reader.php
  tests/framework/data-port/data-files/test_csv_reader_tabs.csv
  tests/unit-tests/data-port/test-class-sensei-import-csv-reader.php
Labels: Hooks, [Type] Enhancement

#3379 Separate notices and errors in the Done page.
  assets/data-port/import/data/actions.js
  assets/data-port/import/data/actions.test.js
  assets/data-port/import/data/constants.js
  assets/data-port/import/data/index.js
  assets/data-port/import/data/reducer.js
  assets/data-port/import/data/reducer.test.js
  assets/data-port/import/data/resolvers.js
  assets/data-port/import/data/resolvers.test.js
  assets/data-port/import/data/selectors.js
  assets/data-port/import/data/selectors.test.js
  assets/data-port/import/done/done-page.js
  assets/data-port/import/done/done-page.test.js
  assets/data-port/import/done/import-done.scss
  assets/data-port/import/done/import-log.js
  assets/data-port/import/done/import-results.js
  assets/data-port/import/done/import-success-results.js
  assets/data-port/import/done/index.js
  assets/data-port/style.scss
  assets/shared/data/store-helpers.js
Labels: [Type] Enhancement

#3359 Fix/add random string quiz upload
  includes/class-sensei-grading-user-quiz.php
  includes/class-sensei-grading.php
  includes/class-sensei-question.php
  includes/class-sensei-utils.php
Labels: Deprecation

#3396 Hide import counters when nothing is imported
  assets/data-port/import/data/selectors.js
  assets/data-port/import/data/selectors.test.js
  assets/data-port/import/done/done-page.js
  assets/data-port/import/done/done-page.test.js
Labels: [Type] Enhancement

#3403 Add title and link to the import logs
  assets/data-port/import/done/done-page.test.js
  assets/data-port/import/done/import-log.js
  includes/data-port/import-tasks/class-sensei-import-file-process-task.php
  includes/data-port/import-tasks/class-sensei-import-prerequisite-trait.php
  includes/data-port/models/class-sensei-import-course-model.php
  includes/data-port/models/class-sensei-import-lesson-model.php
  includes/rest-api/class-sensei-rest-api-data-port-controller.php
  tests/unit-tests/data-port/import-tasks/test-class-sensei-import-courses.php
  tests/unit-tests/data-port/import-tasks/test-class-sensei-import-lessons.php
  tests/unit-tests/rest-api/test-class-sensei-rest-api-import-controller.php
Labels: [Type] Enhancement

#3397 Add validation to multiple choice questions without a right answer.
  includes/data-port/models/class-sensei-import-question-model.php
  tests/unit-tests/data-port/models/test-class-sensei-data-port-question-model.php
Labels: [Type] Bug

#3362 Add E2E tests for Setup Wizard
  tests/e2e/bin/wp-cli.sh
  tests/e2e/specs/activate-and-setup/setup-wizard.test.js
  tests/e2e/utils/flows.js
  tests/e2e/utils/helpers.js
Labels: [Type] Maintenance

#3407 Change import done step
  assets/data-port/import/data/selectors.js
  assets/data-port/import/data/selectors.test.js
  assets/data-port/import/done/done-page.test.js
  assets/data-port/import/done/import-log.js
Labels: Import / Export, [Status] Product Reviewed, [Type] Enhancement

#3402 Add meta handler for remove/restore learner
  includes/enrolment/class-sensei-course-enrolment.php
  tests/unit-tests/enrolment/test-class-sensei-course-enrolment.php
Labels: [Type] Enhancement

#3404 Change learner management actions UI
  assets/css/settings.scss
  includes/admin/class-sensei-learners-main.php
Labels: Learner Management, UI, [Status] Product Reviewed, [Type] Enhancement

#3408 Adjust importer menu position
  includes/data-port/class-sensei-import.php
Labels: [Status] Product Reviewed

#3406 Update importer visuals
  assets/data-port/import/import-progress/import-progress-page.scss
  assets/data-port/import/upload-level/upload-level.js
  assets/data-port/import/upload/upload-page.scss
  assets/data-port/notice.js
  assets/data-port/style.scss
  assets/setup-wizard/wp-colors.scss
Labels: [Status] Product Reviewed

#3409 Add Exporter page
  assets/data-port/export.js
  assets/data-port/import.js
  assets/data-port/style.scss
  assets/react-hooks/use-sensei-color-theme.js
  assets/react-hooks/use-sensei-color-theme.test.js
  assets/setup-wizard/index.js
  includes/class-sensei.php
  includes/data-port/class-sensei-export.php
  webpack.config.js
Labels: [Status] Product Reviewed

#3412 Exporter - Add select content type to export page
  assets/data-port/export.js
  assets/data-port/export/export-select-content-page.js
  assets/data-port/export/export-select-content-page.test.js
  assets/data-port/export/export.scss
  assets/data-port/import/done/import-log.js
  assets/data-port/style.scss
  assets/shared/helpers/labels.js
Labels: [Status] Product Reviewed

#3419 Fix not found when there is no jobId
  assets/data-port/import/data/resolvers.js
  assets/data-port/import/data/resolvers.test.js
Labels: Import / Export, [Type] Bug

#3410 Change learner management actions
  includes/admin/class-sensei-learner-management.php
  includes/admin/class-sensei-learners-main.php
  includes/enrolment/class-sensei-course-enrolment.php
  tests/unit-tests/enrolment/test-class-sensei-course-enrolment.php
Labels: Learner Management, [Type] Enhancement

#3418 Fix eslint issues
  assets/react-hooks/use-event-listener.js
  assets/react-hooks/use-wp-admin-fullscreen.js
Labels: [Type] Maintenance

#3423 Fix title in the import logs
  includes/data-port/models/class-sensei-data-port-model.php
Labels: Import / Export, [Type] Bug

#3424 Update default right answer to true
  includes/data-port/models/class-sensei-import-question-model.php
Labels: Import / Export, [Type] Bug

#3425 Fix validation for question type method
  includes/data-port/models/class-sensei-data-port-question-schema.php
Labels: Import / Export, [Type] Bug

#3430 Fix import CSV with HTML content
  includes/data-port/class-sensei-import-job.php
Labels: Import / Export, [Type] Bug

#3438 Add lesson length validation
  includes/data-port/models/class-sensei-import-lesson-model.php
  tests/unit-tests/data-port/models/test-class-sensei-data-port-lesson-model.php
Labels: Import / Export, [Type] Bug

#3443 Defer warnings until post is created and add warnings in sanitation
  includes/data-port/import-tasks/class-sensei-import-file-process-task.php
  includes/data-port/models/class-sensei-import-lesson-model.php
  includes/data-port/models/class-sensei-import-model.php
  tests/framework/data-port/class-sensei-data-port-schema-mock.php
  tests/unit-tests/data-port/models/test-class-sensei-data-port-course-model.php
  tests/unit-tests/data-port/models/test-class-sensei-data-port-lesson-model.php
  tests/unit-tests/data-port/models/test-class-sensei-data-port-model.php
Labels: Import / Export, [Type] Bug

#3449 Add number of questions validation
  includes/data-port/models/class-sensei-data-port-lesson-schema.php
  includes/data-port/models/class-sensei-import-lesson-model.php
  tests/unit-tests/data-port/models/test-class-sensei-data-port-course-model.php
  tests/unit-tests/data-port/models/test-class-sensei-data-port-lesson-model.php
Labels: Import / Export, [Type] Bug

#3454 Release 3.3.0
  changelog.txt
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
Labels: [Type] Maintenance

#3460 Commit changes to package-lock.json
  package-lock.json
  package.json
Labels: [Type] Maintenance

#3456 Fix learner management alerts
  assets/js/learners-general.js
  includes/admin/class-sensei-learner-management.php
  includes/admin/class-sensei-learners-main.php
Labels: [Type] Enhancement

#3468 Fix hookdoc configurations
  hookdoc-conf.json
Labels: [Type] Maintenance

#3476 Update learner management tables alignment
  assets/css/settings.scss
Labels: Learner Management, [Type] Bug

#3473 Add bulk remove/restore enrollments
  includes/admin/class-sensei-learners-admin-bulk-actions-controller.php
  includes/admin/class-sensei-learners-admin-bulk-actions-view.php
  includes/enrolment/class-sensei-course-enrolment.php
  tests/unit-tests/test-class-sensei-learners-admin-bulk-actions-controller.php
Labels: [Status] Product Reviewed, [Type] Enhancement

#3466 Update learner management messages to be more generic
  includes/admin/class-sensei-learner-management.php
Labels: [Type] Enhancement

#3481 Exclude files in tests-helper directory from build
  gulpfile.js
Labels: [Type] Maintenance

#3434 Configure Renovate to create separate PRs for non-dev dependency updates
  renovate.json
Labels: [Type] Maintenance

#3474 Remove all references to ApiGen
  .eslintignore
  apigen.neon
  apigen/hook-docs.php
  apigen/theme-sensei/404.latte
  apigen/theme-sensei/@elementlist.latte
  apigen/theme-sensei/@layout.latte
  apigen/theme-sensei/annotation-group.latte
  apigen/theme-sensei/class.latte
  apigen/theme-sensei/combined.js.latte
  apigen/theme-sensei/config.neon
  apigen/theme-sensei/constant.latte
  apigen/theme-sensei/deprecated.latte
  apigen/theme-sensei/elementlist.js.latte
  apigen/theme-sensei/function.latte
  apigen/theme-sensei/js/jquery.autocomplete.js
  apigen/theme-sensei/js/jquery.cookie.js
  apigen/theme-sensei/js/jquery.min.js
  apigen/theme-sensei/js/jquery.sortElements.js
  apigen/theme-sensei/js/jquery.sprintf.js
  apigen/theme-sensei/js/main.js
  apigen/theme-sensei/namespace.latte
  apigen/theme-sensei/opensearch.xml.latte
  apigen/theme-sensei/overview.latte
  apigen/theme-sensei/package.latte
  apigen/theme-sensei/resources/collapsed.png
  apigen/theme-sensei/resources/inherit.png
  apigen/theme-sensei/resources/resize.png
  apigen/theme-sensei/resources/sort.png
  apigen/theme-sensei/resources/style.css
  apigen/theme-sensei/resources/tree-cleaner.png
  apigen/theme-sensei/resources/tree-hasnext.png
  apigen/theme-sensei/resources/tree-last.png
  apigen/theme-sensei/resources/tree-vertical.png
  apigen/theme-sensei/robots.txt.latte
  apigen/theme-sensei/sitemap.xml.latte
  apigen/theme-sensei/source.latte
  apigen/theme-sensei/todo.latte
  apigen/theme-sensei/tree.latte
  composer.json
  composer.lock
  phpcs.xml.dist
  phpunit.xml
  wpcom-phpcs.xml
Labels: [Type] Maintenance

#3486 Add warning for invalid slug on importer
  includes/data-port/models/class-sensei-import-model.php
  tests/unit-tests/data-port/models/test-class-sensei-data-port-model.php
Labels: Import / Export, [Type] Enhancement

#3465 Log on learner management actions
  assets/js/learners-general.js
  includes/admin/class-sensei-learner-management.php
  includes/admin/class-sensei-learners-main.php
Labels: [Type] Enhancement

#3488 Merge 3.3.1 release branch
  .travis.yml
  assets/vendor/gutenberg/api-fetch.js
  assets/vendor/gutenberg/api-fetch.min.js
  assets/vendor/gutenberg/components.js
  assets/vendor/gutenberg/components.min.js
  assets/vendor/gutenberg/compose.js
  assets/vendor/gutenberg/compose.min.js
  assets/vendor/gutenberg/data.js
  assets/vendor/gutenberg/data.min.js
  assets/vendor/gutenberg/element.js
  assets/vendor/gutenberg/element.min.js
  assets/vendor/gutenberg/primitives.js
  assets/vendor/gutenberg/primitives.min.js
  assets/vendor/gutenberg/priority-queue.js
  assets/vendor/gutenberg/priority-queue.min.js
  assets/vendor/gutenberg/react-dom.js
  assets/vendor/gutenberg/react-dom.min.js
  assets/vendor/gutenberg/react.js
  assets/vendor/gutenberg/react.min.js
  assets/vendor/gutenberg/redux-routine.js
  assets/vendor/gutenberg/redux-routine.min.js
  assets/vendor/gutenberg/warning.js
  assets/vendor/gutenberg/warning.min.js
  assets/vendor/gutenberg/wp-polyfill.js
  assets/vendor/gutenberg/wp-polyfill.min.js
  changelog.txt
  docker-compose.yaml
  includes/admin/class-sensei-setup-wizard.php
  includes/class-sensei-assets.php
  includes/data-port/class-sensei-import.php
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
  tests/e2e/docker/wordpress/Dockerfile
  tests/e2e/specs/activate-and-setup/setup-wizard.test.js
Labels: [Type] Maintenance

#3485 Change importer progress bar to be full only when it's complete
  includes/data-port/class-sensei-data-port-job.php
  tests/unit-tests/data-port/test-class-sensei-data-port-job.php
Labels: Import / Export, [Type] Bug

#3492 Release 3.4.0 Beta 1
  changelog.txt
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
Labels: [Type] Maintenance
