Repository Automattic/sensei, pull requests merged in 2021-01, with the labels that each got.

#3861 Add comment table indexes on upgrade
  includes/class-sensei-updates.php
  includes/class-sensei.php
Labels: Hooks

#3862 Fix renaming modules issue
  includes/admin/class-sensei-tools.php
  includes/admin/tools/class-sensei-tool-module-slugs-mismatch.php
  includes/class-sensei-autoloader.php
  includes/class-sensei-course-structure.php
  tests/unit-tests/admin/tools/test-class-sensei-tool-module-slugs-mismatch.php
  tests/unit-tests/rest-api/test-class-sensei-rest-api-course-structure-controller.php
  tests/unit-tests/test-class-sensei-course-structure.php
Labels: [Type] Bug

#3874 Merge 3.6.1 release into master
  assets/admin/exit-survey/index.js
  changelog.txt
  includes/blocks/class-sensei-block-contact-teacher.php
  includes/blocks/class-sensei-block-take-course.php
  includes/blocks/class-sensei-course-outline-block.php
  includes/blocks/class-sensei-course-outline-course-block.php
  lang/sensei-lms.pot
  package-lock.json
  readme.txt
Labels: [Type] Maintenance

#3876 Add WCPC installation notice
  assets/css/admin-custom.css
  includes/admin/class-sensei-plugins-installation.php
  includes/admin/class-sensei-setup-wizard.php
  includes/admin/class-sensei-wcpc-prompt.php
  includes/class-sensei-autoloader.php
  includes/class-sensei-data-cleaner.php
  includes/class-sensei-utils.php
  includes/class-sensei.php
  includes/rest-api/class-sensei-rest-api-setup-wizard-controller.php
  includes/sensei-functions.php
  tests/unit-tests/admin/test-class-sensei-setup-wizard-api.php
  tests/unit-tests/admin/test-class-sensei-setup-wizard.php
  tests/unit-tests/admin/test-class-sensei-wcpc-prompt.php
  tests/unit-tests/test-class-sensei-usage-tracking.php
Labels: Deprecation, [Type] Enhancement

#3879 Fix module lessons order
  includes/class-sensei-modules.php
Labels: [Type] Bug

#3884 Add sample course check to show notice to install WooCommerce Paid Courses
  includes/admin/class-sensei-wcpc-prompt.php
  includes/class-sensei-course.php
  includes/data-port/class-sensei-data-port-manager.php
  tests/unit-tests/admin/test-class-sensei-wcpc-prompt.php
Labels: [Type] Enhancement

#3869 Add refresh modules button after changing course teacher
  assets/js/modules-admin.js
Labels: [Type] Bug

#3892 Release 3.7.0 Beta 1
  changelog.txt
  includes/class-sensei-updates.php
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
Labels: [Type] Maintenance

#3885 Isolate course blocks
  assets/blocks/button/edit-button.js
  assets/blocks/button/index.js
  assets/blocks/contact-teacher/index.js
  assets/blocks/course-outline/course-block/edit.js
  assets/blocks/course-progress/edit.js
  assets/blocks/register-sensei-blocks.js
  assets/blocks/sensei-single-course-blocks.js
  assets/blocks/take-course/index.js
  assets/blocks/toggle-legacy-course-metaboxes-wrapper.js
  assets/blocks/use-toggle-legacy-metaboxes.js
  assets/icons/progress-icon.js
  includes/blocks/class-sensei-blocks.php
  includes/blocks/class-sensei-course-blocks.php
  includes/class-sensei.php
  webpack.config.js
Labels: [Type] Enhancement

#3886 Add lesson actions block setup
  assets/blocks/lesson-actions/complete-lesson-block/index.js
  assets/blocks/lesson-actions/index.js
  assets/blocks/lesson-actions/lesson-actions-block/block.json
  assets/blocks/lesson-actions/lesson-actions-block/edit.js
  assets/blocks/lesson-actions/lesson-actions-block/index.js
  assets/blocks/lesson-actions/lesson-actions-block/save.js
  assets/blocks/lesson-actions/next-lesson-block/index.js
  assets/blocks/lesson-actions/reset-lesson-block/index.js
  assets/blocks/sensei-single-lesson-blocks.js
  includes/blocks/class-sensei-blocks.php
  includes/blocks/class-sensei-lesson-blocks.php
  webpack.config.js
Labels: [Type] Enhancement

#3895 Fix lesson action buttons alignment
  assets/blocks/button/button.scss
  assets/blocks/button/index.js
  assets/blocks/button/save-button.js
  assets/blocks/lesson-actions/lesson-actions-block/edit.js
  assets/blocks/lesson-actions/lesson-actions-block/save.js
  assets/blocks/single-lesson.editor.scss
  assets/blocks/single-lesson.scss
  includes/blocks/class-sensei-lesson-blocks.php
  webpack.config.js
Labels: [Type] Enhancement

#3887 Add lesson actions block settings
  assets/blocks/lesson-actions/lesson-actions-block/block.json
  assets/blocks/lesson-actions/lesson-actions-block/edit.js
  assets/blocks/lesson-actions/lesson-actions-block/settings.js
Labels: [Type] Enhancement

#3907 Fix components toggle
  assets/blocks/lesson-actions/lesson-actions-block/edit.js
Labels: [Type] Bug

#3908 Add sensei block category to lesson post type
  includes/blocks/class-sensei-blocks.php
Labels: [Type] Enhancement

#3904 Add toolbar dropdown component for the editor
  assets/blocks/editor-components/styles.scss
  assets/blocks/editor-components/toolbar-dropdown/index.js
  assets/blocks/editor-components/toolbar-dropdown/styles.scss
  webpack.config.js
Labels: [Type] Enhancement

#3903 Add lesson actions preview
  assets/blocks/button/button.editor.scss
  assets/blocks/button/index.js
  assets/blocks/button/save-button.js
  assets/blocks/editor-components/style.scss
  assets/blocks/editor-components/styles.scss
  assets/blocks/editor-components/toolbar-dropdown/style.scss
  assets/blocks/lesson-actions/lesson-actions-block/constants.js
  assets/blocks/lesson-actions/lesson-actions-block/edit.js
  assets/blocks/lesson-actions/lesson-actions-block/settings.js
  assets/blocks/lesson-actions/lesson-actions-block/style.editor.scss
  assets/blocks/lesson-actions/lesson-actions-block/style.scss
  assets/blocks/lesson-actions/lesson-actions-block/use-preview-state.js
  assets/blocks/lesson-actions/lesson-actions-block/use-toggle-blocks.js
  assets/blocks/single-lesson.editor.scss
  assets/blocks/single-lesson.scss
  includes/blocks/class-sensei-lesson-blocks.php
  webpack.config.js
Labels: [Type] Enhancement

#3913 Fix/lesson actions alignment
  assets/blocks/button/button.scss
Labels: [Type] Bug

#3849 Add restricted content blocks
  assets/blocks/restricted-content/block.json
  assets/blocks/restricted-content/edit.js
  assets/blocks/restricted-content/index.js
  assets/blocks/restricted-content/save.js
  assets/blocks/restricted-content/settings.js
  assets/blocks/sensei-single-course-blocks.js
  includes/blocks/class-sensei-block-contact-teacher.php
  includes/blocks/class-sensei-block-take-course.php
  includes/blocks/class-sensei-course-blocks.php
  includes/blocks/class-sensei-course-outline-block.php
  includes/blocks/class-sensei-course-progress-block.php
  includes/blocks/class-sensei-restricted-content-block.php
  includes/class-sensei-course.php
  tests/unit-tests/blocks/sample-data/outline-block-post-content.html
  tests/unit-tests/blocks/test-class-sensei-block-take-course.php
  tests/unit-tests/blocks/test-class-sensei-contact-teacher-block.php
  tests/unit-tests/blocks/test-class-sensei-course-outline-block.php
Labels: [Type] Enhancement

#3919 Add some missing button i18n
  assets/blocks/contact-teacher/index.js
  assets/blocks/lesson-actions/complete-lesson-block/index.js
  assets/blocks/lesson-actions/next-lesson-block/index.js
  assets/blocks/lesson-actions/reset-lesson-block/index.js
  assets/blocks/lesson-actions/view-quiz-block/index.js
  assets/blocks/take-course/index.js
Labels: [Type] Bug

#3920 Log when lessons are updated
  includes/class-sensei-lesson.php
Labels: [Type] Enhancement

#3926 Switch to GitHub Actions for CI
  .github/workflows/e2e.yml
  .github/workflows/js.yml
  .github/workflows/php.yml
  .travis.yml
  README.md
  scripts/linter-ci
  tests/bin/run-wp-unit-tests.sh
Labels: [Type] Maintenance

#3932 Fix preview opacity
  assets/blocks/lesson-actions/lesson-actions-block/style.editor.scss
Labels: [Type] Bug

#3933 Add the e2e reporter configurations for screenshots
  .github/workflows/e2e.yml
Labels: [Type] Maintenance

#3883 Fix filter hook docs
  includes/class-sensei-course.php
  includes/class-sensei-learner.php
  includes/class-sensei-quiz.php
  includes/data-port/class-sensei-import-csv-reader.php
  includes/sensei-functions.php
Labels: [Type] Maintenance
