Repository Automattic/sensei, pull requests merged in 2021-08, with the labels that each got.

#4271 Update Ubuntu version to 18.04
  .github/workflows/e2e.yml
  .github/workflows/js.yml
  .github/workflows/php.yml
Labels: [Type] Maintenance

#4270 Update View Results button link
  includes/blocks/class-sensei-block-view-results.php
  includes/class-sensei-course.php
  includes/class-sensei-frontend.php
  tests/unit-tests/test-class-course.php
Labels: Hooks

#4266 Add Course Completed Actions block
  assets/blocks/course-completed-actions/index.js
  assets/blocks/single-page.js
  includes/blocks/class-sensei-blocks.php
  includes/blocks/class-sensei-course-completed-actions-block.php
  includes/blocks/class-sensei-page-blocks.php
Labels: Hooks

#4281 Add blocks template to completed course page
  assets/blocks/course-results-block/course-results.scss
  includes/admin/class-sensei-setup-wizard-pages.php
Labels: [Type] Enhancement

#4286 Update "Course Completed Actions" variation
  assets/blocks/course-completed-actions/index.js
  includes/admin/class-sensei-setup-wizard-pages.php
Labels: [Type] Enhancement, Hooks

#4290 Update page template filter names
  includes/admin/class-sensei-setup-wizard-pages.php
Labels: Hooks

#4291 Update Learner Courses block styles
  assets/blocks/learner-courses-block/learner-courses-editor.scss
  assets/blocks/learner-courses-block/learner-courses-mixins.scss
  assets/blocks/learner-courses-block/learner-courses.scss
  templates/content-course.php
Labels: Templates

#4289 Fix color selector issue
  assets/blocks/learner-courses-block/block.json
  assets/blocks/learner-courses-block/learner-courses-settings.js
Labels: [Type] Bug
