Repository Automattic/sensei, pull requests merged in 2021-12, with the labels that each got.

#4491 Fix invalid type issue when questions options empty
  includes/class-sensei-question.php
Labels: [Type] Bug

#4492 Implement the quiz pagination backend
  includes/class-sensei-quiz.php
  includes/template-functions.php
  tests/unit-tests/test-class-quiz.php
Labels: [Type] Enhancement

#4497 Update tests readme with information about svn
  tests/README.md
Labels: [Type] Maintenance

#4490 Lesson actions block
  assets/css/sensei-course-theme.scss
  assets/css/sensei-course-theme/buttons.scss
  assets/css/sensei-course-theme/lesson-actions.scss
  includes/blocks/course-theme/class-complete-lesson.php
  includes/blocks/course-theme/class-course-theme.php
  includes/blocks/course-theme/class-lesson-actions.php
  includes/blocks/course-theme/class-quiz-button.php
  includes/class-sensei-autoloader.php
  templates/course-theme/single-lesson.php
  tests/unit-tests/blocks/course-theme/test-class-course-progress-bar.php
  tests/unit-tests/blocks/course-theme/test-class-lesson-actions.php
  tests/unit-tests/course-theme/test-class-complete-lesson.php
Labels: [Type] Enhancement

#4509 Add locked lesson states
  assets/css/sensei-course-theme/notices.scss
  assets/images/lock.svg
  includes/blocks/course-theme/class-notices.php
  includes/class-sensei-assets.php
  includes/class-sensei-context-notices.php
  includes/course-theme/class-sensei-course-theme-lesson.php
  templates/course-theme/lesson-quiz-notice.php
  templates/course-theme/locked-lesson-notice.php
  tests/unit-tests/course-theme/test-class-sensei-course-theme-lesson.php
Labels: [Type] Enhancement

#4507 Improve wording of the lessons prerequisite metabox
  includes/class-sensei-lesson.php
Labels: Messages, i18n, UI

#4515 Add locked lesson free course notices
  assets/css/sensei-course-theme/base.scss
  assets/css/sensei-course-theme/buttons.scss
  includes/blocks/class-sensei-block-take-course.php
  includes/class-sensei-context-notices.php
  includes/class-sensei-course.php
  includes/class-sensei-frontend.php
  includes/class-sensei-teacher.php
  includes/course-theme/class-sensei-course-theme-lesson.php
  includes/sensei-functions.php
  templates/course-theme/lesson-quiz-notice.php
  templates/course-theme/locked-lesson-notice.php
  tests/unit-tests/course-theme/test-class-sensei-course-theme-lesson.php
  tests/unit-tests/test-class-sensei-context-notices.php
  tests/unit-tests/test-sensei-functions.php
Labels: [Type] Enhancement, Hooks, Deprecation

#4415 Grading display filter for custom question types
  includes/class-sensei-grading-user-quiz.php
Labels: Hooks

#4421 Refresh the module selection after changing the course
  assets/js/admin/blocks-toggling-control.js
  assets/js/admin/lesson-edit.js
  assets/js/modules-admin.js
  includes/class-sensei-modules.php
Labels: [Type] Enhancement, Deprecation

#4535 Show prerequisite notice as priority notice for logged out users
  includes/course-theme/class-sensei-course-theme-lesson.php
  tests/unit-tests/course-theme/test-class-sensei-course-theme-lesson.php
Labels: [Type] Enhancement

#4501 Renamed learner -> student in all user-facing occurrences
  assets/blocks/course-completed-actions/index.js
  assets/blocks/course-outline/status-preview/status-control/index.js
  assets/blocks/course-results-block/index.js
  assets/blocks/learner-courses-block/index.js
  assets/blocks/learner-messages-button-block/index.js
  assets/blocks/learner-messages-button-block/messages-disabled-notice.js
  assets/blocks/lesson-actions/complete-lesson-block/index.js
  assets/blocks/lesson-actions/lesson-actions-block/index.js
  assets/blocks/lesson-actions/next-lesson-block/index.js
  assets/blocks/lesson-actions/reset-lesson-block/index.js
  assets/blocks/lesson-actions/view-quiz-block/index.js
  assets/blocks/quiz/question-block/single-question.js
  assets/blocks/quiz/quiz-block/quiz-settings.js
  assets/blocks/quiz/quiz-block/quiz-validation.js
  assets/blocks/view-results-block/index.js
  includes/admin/class-sensei-learner-management.php
  includes/admin/class-sensei-learners-admin-bulk-actions-controller.php
  includes/admin/class-sensei-learners-admin-bulk-actions-view.php
  includes/admin/class-sensei-learners-main.php
  includes/admin/class-sensei-status.php
  includes/admin/tools/class-sensei-tool-enrolment-debug.php
  includes/admin/tools/views/html-enrolment-debug.php
  includes/blocks/class-sensei-course-outline-course-block.php
  includes/class-sensei-analysis-course-list-table.php
  includes/class-sensei-analysis-lesson-list-table.php
  includes/class-sensei-analysis-overview-list-table.php
  includes/class-sensei-course.php
  includes/class-sensei-grading-main.php
  includes/class-sensei-learner.php
  includes/class-sensei-lesson.php
  includes/class-sensei-messages.php
  includes/class-sensei-settings.php
  includes/enrolment/class-sensei-course-enrolment-manager.php
  includes/enrolment/class-sensei-course-manual-enrolment-provider.php
  lang/sensei-lms.pot
  templates/emails/teacher-completed-course.php
  templates/emails/teacher-completed-lesson.php
  templates/emails/teacher-started-course.php
  tests/unit-tests/enrolment/test-class-sensei-course-manual-enrolment-provider.php
  tests/unit-tests/test-class-sensei-learners-main.php
Labels: [Type] Enhancement, i18n, UI

#4502 Implement the quiz pagination frontend
  assets/css/_mixins.scss
  assets/css/frontend.scss
  includes/class-sensei-quiz.php
  includes/hooks/template.php
  includes/template-functions.php
  templates/single-quiz.php
  templates/single-quiz/pagination.php
  tests/unit-tests/test-class-quiz.php
Labels: [Type] Enhancement, Hooks, Templates

#4519 Add Video-Based Course Progression settings
  assets/js/admin/course-edit.js
  assets/js/admin/course-theme-sidebar.js
  assets/js/admin/course-video-sidebar.js
  assets/react-hooks/use-course-meta.js
  includes/class-sensei-autoloader.php
  includes/class-sensei-data-cleaner.php
  includes/class-sensei-feature-flags.php
  includes/class-sensei.php
  includes/course-video/class-sensei-course-video-settings.php
  tests/unit-tests/course-video/test-class-sensei-course-video-settings.php
  tests/unit-tests/test-class-sensei-data-cleaner.php
Labels: [Type] Enhancement

#4545 Fix complete lesson form in the quiz page
  includes/blocks/course-theme/class-lesson-actions.php
Labels: [Type] Bug

#4534 Adding "by default" sort order to Courses archive page.
  includes/class-sensei-course.php
  tests/unit-tests/test-class-course.php
Labels: Courses, UI, Deprecation

#4539 Completion lesson transitions
  assets/course-theme/complete-lesson-button.js
  assets/course-theme/course-theme.js
  assets/css/sensei-course-theme.scss
  assets/css/sensei-course-theme/focus-mode.scss
  assets/css/sensei-course-theme/layout.scss
  assets/css/sensei-course-theme/lesson-complete-transition.scss
  assets/css/sensei-course-theme/mobile.scss
  includes/blocks/class-sensei-course-progress-block.php
  includes/blocks/course-theme/class-course-progress-bar.php
  includes/blocks/course-theme/class-lesson-actions.php
Labels: [Type] Enhancement

#4553 Add `/themes` folder to the build package
  composer.json
Labels: [Type] Bug

#4559 Add complete lesson attributes
  assets/course-theme/complete-lesson-button.js
  includes/blocks/class-sensei-complete-lesson-block.php
  includes/class-sensei-frontend.php
Labels: [Type] Enhancement

#4557 Fix Lesson template when creating a new lesson through WP-admin menu
  includes/rest-api/class-sensei-rest-api-lessons-controller.php
Labels: [Type] Bug

#4558 Tweak Lesson blocks template when associated with a course with Learning Mode enabled.
  includes/blocks/class-sensei-lesson-blocks.php
  includes/course-theme/class-sensei-course-theme-option.php
Labels: [Type] Enhancement

#4546 Extend standard YouTube embed block
  assets/js/frontend/course-video/youtube-extension.js
  includes/class-sensei-autoloader.php
  includes/class-sensei-frontend.php
  includes/course-video/blocks/class-sensei-course-video-blocks-youtube-extension.php
  includes/course-video/class-sensei-course-video-settings.php
  tests/unit-tests/course-video/blocks/test-class-sensei-course-video-blocks-youtube-extension.php
  webpack.config.js
Labels: [Type] Enhancement

#4543 Hide incomplete questions from the frontend (Preview)
  includes/class-sensei-lesson.php
  includes/class-sensei-quiz.php
  tests/framework/factories/class-wp-unittest-factory-for-question.php
  tests/unit-tests/test-class-quiz.php
Labels: [Pri] Normal, Lessons, UI, Questions

#4538 Implement Course Theme Quiz_Graded block.
  assets/css/sensei-course-theme.scss
  assets/css/sensei-course-theme/buttons.scss
  assets/css/sensei-course-theme/contact-teacher.scss
  assets/css/sensei-course-theme/quiz-graded.scss
  includes/blocks/course-theme/class-notices.php
  includes/class-sensei-autoloader.php
  includes/course-theme/class-sensei-course-theme-option.php
  includes/course-theme/class-sensei-course-theme-quiz.php
  templates/course-theme/locked-lesson-notice.php
  templates/course-theme/quiz-grade-notice.php
Labels: [Type] Enhancement

#4568 Tweak link style in lesson quiz notice
  assets/css/sensei-course-theme/buttons.scss
  assets/css/sensei-course-theme/notices.scss
  templates/course-theme/lesson-quiz-notice.php
Labels: [Type] Enhancement

#4562 Extend standard video block
  assets/js/frontend/course-video/video-blocks-extension.js
  assets/js/frontend/course-video/youtube-extension.js
  includes/class-sensei-frontend.php
  includes/class-sensei.php
  includes/course-video/blocks/class-sensei-course-video-blocks-embed-extension.php
  includes/course-video/blocks/class-sensei-course-video-blocks-video-extension.php
  includes/course-video/blocks/class-sensei-course-video-blocks-youtube-extension.php
  includes/course-video/class-sensei-course-video-settings.php
  tests/unit-tests/course-video/blocks/test-class-sensei-course-video-blocks-video-extension.php
  tests/unit-tests/course-video/blocks/test-class-sensei-course-video-blocks-youtube-extension.php
  webpack.config.js
Labels: [Type] Enhancement

#4561 Extend standard Vimeo video embed
  assets/js/frontend/course-video/video-blocks-extension.js
  includes/course-video/blocks/class-sensei-course-video-blocks-vimeo-extension.php
  includes/course-video/class-sensei-course-video-settings.php
  tests/unit-tests/course-video/blocks/test-class-sensei-course-video-blocks-vimeo-extension.php
Labels: [Type] Enhancement

#4533 Allow only before or after text on the gap question
  assets/blocks/quiz/answer-blocks/index.js
Labels: [Pri] Normal, Messages, Questions
