Repository Automattic/sensei, pull requests merged in 2021-07, with the labels that each got.

#4238 Update @wordpress/scripts and JSDoc alignments
  .eslintrc.js
  assets/data-port/import/data/normalizer.js
  assets/data-port/import/data/reducer.js
  assets/js/grading-general.js
  assets/js/modules-admin.js
  assets/setup-wizard/data/reducer.js
  package-lock.json
  package.json
Labels: [Type] Maintenance

#4236 Fix structure ordering cache
  includes/class-sensei-admin.php
  includes/class-sensei-course-structure.php
  includes/rest-api/class-sensei-rest-api-course-structure-controller.php
Labels: [Type] Bug

#4245 Add Prettier plugin JSDoc
  .editorconfig
  .github/workflows/build-docs.yml
  .github/workflows/e2e.yml
  .github/workflows/js.yml
  .github/workflows/php.yml
  .prettierignore
  .prettierrc.js
  .scrutinizer.yml
  assets/js/admin/meta-box-quiz-editor.js
  docker-compose.yaml
  package.json
  scripts/prettier/prettier-plugin-jsdoc.js
Labels: [Type] Maintenance

#4246 Adds a notice when adding the first Sensei block or removing the last one from a Course or Lesson.
  assets/blocks/contact-teacher-block/index.js
  assets/blocks/course-outline/outline-block/outline-edit.js
  assets/blocks/course-progress-block/course-progress-edit.js
  assets/blocks/lesson-actions/lesson-actions-block/lesson-actions-edit.js
  assets/blocks/lesson-properties/lesson-properties-edit.js
  assets/blocks/take-course-block/index.js
  assets/blocks/toggle-legacy-course-metaboxes-wrapper.js
  assets/blocks/toggle-legacy-lesson-metaboxes-wrapper.js
  assets/blocks/toggle-legacy-metaboxes-wrapper.js
  assets/blocks/view-results-block/index.js
  assets/js/admin/course-edit.js
  assets/js/admin/lesson-edit.js
  assets/js/admin/post-edit.js
Labels: [Type] Enhancement

#4248 Release 3.12.0
  changelog.txt
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
Labels: [Type] Maintenance
