Repository Automattic/sensei, pull requests merged in 2021-02, with the labels that each got.

#3937 Add a default template to the lesson editor
  assets/blocks/lesson-actions/lesson-actions-block/lesson-actions-edit.js
  assets/blocks/shared.js
  assets/blocks/single-lesson.js
  includes/blocks/class-sensei-lesson-blocks.php
  includes/class-sensei-course-structure.php
  includes/class-sensei-posttypes.php
Labels: [Type] Enhancement

#3940 Add question type selector
  assets/blocks/editor-components/toolbar-dropdown/index.js
  assets/blocks/editor-components/toolbar-dropdown/toolbar-dropdown.scss
  assets/blocks/quiz/answer-blocks/index.js
  assets/blocks/quiz/question-block/block.json
  assets/blocks/quiz/question-block/question-edit.js
  assets/blocks/quiz/question-block/question-type-toolbar.js
  assets/blocks/quiz/quiz.editor.scss
Labels: Hooks

#3956 Release 3.8.0 Beta 1
  changelog.txt
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
Labels: [Type] Maintenance

#3962 Fix block translations
  includes/admin/class-sensei-exit-survey.php
  includes/admin/class-sensei-setup-wizard.php
  includes/class-sensei-assets.php
  includes/data-port/class-sensei-export.php
  includes/data-port/class-sensei-import.php
Labels: Deprecation, [Type] Bug

#3968 Release 3.8.0
  changelog.txt
  lang/sensei-lms.pot
  sensei-lms.php
Labels: [Type] Maintenance

#3970 Merge 3.8.0 release into master
  assets/blocks/button/button-edit.js
  assets/blocks/button/button-save.js
  assets/blocks/button/index.js
  assets/blocks/lesson-actions/complete-lesson-block/index.js
  assets/blocks/lesson-actions/next-lesson-block/index.js
  assets/blocks/lesson-actions/reset-lesson-block/index.js
  assets/blocks/lesson-actions/view-quiz-block/index.js
  changelog.txt
  includes/admin/class-sensei-exit-survey.php
  includes/admin/class-sensei-setup-wizard.php
  includes/blocks/class-sensei-complete-lesson-block.php
  includes/blocks/class-sensei-lesson-blocks.php
  includes/blocks/class-sensei-next-lesson-block.php
  includes/blocks/class-sensei-reset-lesson-block.php
  includes/blocks/class-sensei-view-quiz-block.php
  includes/class-sensei-assets.php
  includes/data-port/class-sensei-export.php
  includes/data-port/class-sensei-import.php
  lang/sensei-lms.pot
  sensei-lms.php
Labels: [Type] Maintenance

#3963 Question blocks: Add single line, multi line answer boxes
  assets/blocks/quiz/answer-blocks/index.js
  assets/blocks/quiz/answer-blocks/multi-line.js
  assets/blocks/quiz/answer-blocks/single-line.js
  assets/blocks/quiz/question-block/question-block.editor.scss
  assets/blocks/quiz/quiz-block/index.js
  assets/blocks/quiz/quiz-block/quiz-edit.js
  assets/blocks/quiz/quiz.editor.scss
  assets/blocks/single-lesson-style-editor.scss
Labels: [Status] Needs Design Review

#3985 Allow template field to be edited by teachers
  includes/blocks/class-sensei-lesson-blocks.php
Labels: [Type] Bug

#3990 Merge 3.8.1 into master
  assets/js/lesson-metadata.js
  changelog.txt
  includes/admin/class-sensei-learners-admin-bulk-actions-controller.php
  includes/admin/class-sensei-learners-main.php
  includes/blocks/class-sensei-lesson-blocks.php
  includes/class-sensei-analysis-course-list-table.php
  includes/class-sensei-analysis.php
  includes/class-sensei-messages.php
  includes/class-sensei-modules.php
  includes/class-sensei-posttypes.php
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
  tests/unit-tests/rest-api/test-sensei-rest-api.php
  tests/unit-tests/test-class-sensei-data-cleaner.php
  tests/unit-tests/test-class-sensei-learners-admin-bulk-actions-controller.php
  tests/unit-tests/test-class-sensei-learners-main.php
  tests/unit-tests/test-class-sensei-messages.php
Labels: [Type] Maintenance

#3992 Update default answers to empty string instead of null
  assets/blocks/quiz/answer-blocks/multiple-choice.js
Labels: [Type] Bug

#3987 Add quiz settings
  assets/blocks/editor-components/editor-components-style.scss
  assets/blocks/editor-components/number-control/index.js
  assets/blocks/editor-components/number-control/index.test.js
  assets/blocks/editor-components/number-control/number-control.scss
  assets/blocks/quiz/quiz-block/quiz-edit.js
  assets/blocks/quiz/quiz-block/quiz-settings.js
  assets/blocks/quiz/quiz-block/quiz-settings.test.js
Labels: [Type] Enhancement

#3996 Add quiz options attribute normalizer
  assets/blocks/quiz/data.js
  assets/blocks/quiz/quiz-store.js
Labels: [Type] Enhancement

#3993 REST API: Set up questions CPT
  includes/class-sensei-posttypes.php
  includes/rest-api/class-sensei-rest-api-questions-controller.php
  tests/framework/factories/class-wp-unittest-factory-for-question.php
  tests/unit-tests/rest-api/test-class-sensei-rest-api-questions-controller.php
Labels: [Type] Enhancement

#3983 Restrict one quiz per lesson
  assets/blocks/quiz/quiz-block/block.json
  assets/blocks/quiz/quiz-block/quiz-edit.js
  includes/blocks/class-sensei-lesson-blocks.php
Labels: [Type] Enhancement

#4003 Add existing questions modal
  assets/blocks/editor-components/editor-components-style.scss
  assets/blocks/editor-components/input-control/index.js
  assets/blocks/editor-components/input-control/index.test.js
  assets/blocks/editor-components/input-control/input-control.scss
  assets/blocks/editor-components/number-control/index.js
  assets/blocks/quiz/quiz-block/questions-modal/actions.js
  assets/blocks/quiz/quiz-block/questions-modal/filter.js
  assets/blocks/quiz/quiz-block/questions-modal/index.js
  assets/blocks/quiz/quiz-block/questions-modal/questions-modal-style.scss
  assets/blocks/quiz/quiz-block/questions-modal/questions.js
  assets/blocks/quiz/quiz-block/quiz-edit.js
  assets/blocks/quiz/quiz.editor.scss
Labels: [Type] Enhancement

#4009 Add filter to disable block based quiz editor
  assets/css/meta-box-quiz-editor.scss
  assets/css/settings.scss
  assets/js/admin/lesson-edit.js
  assets/js/admin/meta-box-quiz-editor.js
  includes/blocks/class-sensei-blocks.php
  includes/blocks/class-sensei-lesson-blocks.php
  includes/blocks/class-sensei-quiz-blocks.php
  includes/class-sensei-feature-flags.php
  includes/class-sensei-lesson.php
  includes/class-sensei-question.php
  includes/class-sensei-quiz.php
  webpack.config.js
Labels: Hooks, [Type] Enhancement

#4013 REST API: Retrieve individual question options
  includes/rest-api/class-sensei-rest-api-internal.php
  includes/rest-api/class-sensei-rest-api-lesson-quiz-controller.php
  includes/rest-api/class-sensei-rest-api-question-helpers-trait.php
  includes/rest-api/class-sensei-rest-api-question-options-controller.php
  tests/unit-tests/rest-api/test-class-sensei-rest-api-question-options-controller.php
Labels: Hooks, [Type] Enhancement
