Repository Automattic/sensei, pull requests merged in 2021-04, with the labels that each got.

#4152 Add 3.9.1 changes
  .eslintrc.js
  assets/blocks/conditional-content-block/index.js
  assets/blocks/course-outline/course-outline-store.js
  assets/blocks/course-outline/module-block/module-edit.js
  assets/blocks/course-outline/outline-block/outline-edit.js
  assets/blocks/course-progress-block/course-progress-edit.js
  assets/blocks/course-progress-block/index.js
  assets/blocks/editor-components/number-control/index.js
  assets/blocks/editor-components/number-control/number-control.scss
  assets/blocks/learner-courses-block/index.js
  assets/blocks/quiz/answer-blocks/gap-fill.js
  assets/blocks/quiz/category-question-block/category-question-edit.js
  assets/blocks/quiz/category-question-block/category-question-settings.js
  assets/blocks/quiz/category-question-block/category-question-validation.js
  assets/blocks/quiz/category-question-block/index.js
  assets/blocks/quiz/question-block/question-block-helpers.js
  assets/blocks/quiz/question-block/question-edit.js
  assets/blocks/quiz/question-block/question-grade-control.js
  assets/blocks/quiz/question-block/question-grade-toolbar.js
  assets/blocks/quiz/question-block/question-grade-toolbar.scss
  assets/blocks/quiz/question-block/settings/question-grade-settings.js
  assets/blocks/quiz/question-block/single-question.js
  assets/blocks/quiz/question-number.js
  assets/blocks/quiz/quiz-block/quiz-edit.js
  changelog.txt
  includes/admin/class-sensei-extensions.php
  includes/admin/views/html-admin-page-extensions-messages.php
  includes/blocks/class-sensei-course-progress-block.php
  includes/class-sensei-data-cleaner.php
  includes/class-sensei-lesson.php
  includes/class-sensei-usage-tracking.php
  includes/lib/usage-tracking/class-usage-tracking-base.php
  includes/lib/usage-tracking/tests/support/class-usage-tracking-test-subclass.php
  includes/lib/usage-tracking/tests/test-class-usage-tracking.php
  includes/rest-api/class-sensei-rest-api-question-helpers-trait.php
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
Labels: [Type] Maintenance

#4138 Add progress bar settings to the Learner Courses block
  assets/blocks/course-progress-block/course-progress-edit.js
  assets/blocks/course-progress-block/course-progress.scss
  assets/blocks/editor-components/course-progress-settings/course-progress-settings.scss
  assets/blocks/editor-components/course-progress-settings/index.js
  assets/blocks/editor-components/editor-components-style.scss
  assets/blocks/learner-courses-block/block.json
  assets/blocks/learner-courses-block/learner-courses-edit.js
  assets/blocks/learner-courses-block/learner-courses-settings.js
  assets/blocks/learner-courses-block/learner-courses-settings.test.js
  assets/blocks/learner-courses-block/learner-courses.scss
  includes/blocks/class-sensei-page-blocks.php
Labels: [Type] Enhancement

#4133 Add bundle analyzer script
  package.json
Labels: [Type] Maintenance

#4142 Add color settings to Learner Courses block
  assets/blocks/learner-courses-block/block.json
  assets/blocks/learner-courses-block/learner-courses-edit.js
  assets/blocks/learner-courses-block/learner-courses-settings.js
  assets/blocks/learner-courses-block/learner-courses-settings.test.js
  assets/blocks/learner-courses-block/learner-courses.scss
Labels: [Type] Enhancement

#4148 Show teacher's questions only when using category questions
  assets/blocks/quiz/category-question-block/category-question-settings.js
  includes/class-sensei-frontend.php
  includes/class-sensei-lesson.php
  includes/class-sensei-quiz.php
  includes/template-functions.php
Labels: Hooks

#4158 Activate learner courses example
  assets/blocks/learner-courses-block/index.js
Labels: [Type] Enhancement

#4149 Refactor Learner Courses block to use the same bar from Course Progress block
  assets/blocks/course-progress-block/course-progress-edit.js
  assets/blocks/course-progress-block/course-progress-editor.scss
  assets/blocks/course-progress-block/course-progress.scss
  assets/blocks/editor-components/editor-components-style.scss
  assets/blocks/learner-courses-block/course-progress.js
  assets/blocks/learner-courses-block/course-progress.test.js
  assets/blocks/learner-courses-block/learner-courses-edit.js
  assets/blocks/learner-courses-block/learner-courses-editor.scss
  assets/blocks/learner-courses-block/learner-courses-settings.js
  assets/blocks/learner-courses-block/learner-courses.scss
  assets/blocks/single-course-style-editor.scss
  assets/blocks/single-page-style-editor.scss
  assets/shared/blocks/course-progress/course-progress-settings.js
  assets/shared/blocks/course-progress/course-progress-settings.scss
  assets/shared/blocks/course-progress/course-progress.js
  assets/shared/blocks/course-progress/course-progress.scss
  assets/shared/blocks/course-progress/course-progress.test.js
  assets/shared/blocks/course-progress/index.js
  includes/blocks/class-sensei-course-progress-block.php
  includes/blocks/class-sensei-page-blocks.php
  webpack.config.js
Labels: [Type] Enhancement

#4156 Add extensions update counter
  includes/admin/class-sensei-extensions.php
  includes/class-sensei-feature-flags.php
  tests/unit-tests/admin/test-class-sensei-extensions.php
Labels: [Type] Enhancement

#4162 Add extensions page structure
  assets/extensions/card.js
  assets/extensions/extension-actions.js
  assets/extensions/extensions.js
  assets/extensions/extensions.scss
  assets/extensions/header.js
  assets/extensions/index.js
  assets/extensions/main.js
  assets/extensions/tabs.js
  assets/extensions/update-notification.js
  assets/shared/styles/_variables.scss
  assets/shared/styles/wp-admin.scss
  includes/admin/class-sensei-extensions.php
  webpack.config.js
Labels: [Type] Enhancement

#4174 Change Github workflows to run for every branch
  .github/workflows/e2e.yml
  .github/workflows/php.yml
Labels: [Type] Maintenance

#4163 Improve extensions page responsive styles
  assets/extensions/extensions.js
  assets/extensions/extensions.scss
Labels: [Type] Enhancement

#4164 Add extensions page tabs
  assets/extensions/all-extensions.js
  assets/extensions/extensions.scss
  assets/extensions/filtered-extensions.js
  assets/extensions/main.js
  assets/extensions/tabs.js
  assets/setup-wizard/features/index.js
  assets/setup-wizard/features/index.test.js
  assets/setup-wizard/index.js
  assets/setup-wizard/navigation/index.js
  assets/setup-wizard/purpose/index.js
  assets/setup-wizard/welcome/index.js
  assets/shared/query-string-router/index.js
  assets/shared/query-string-router/index.test.js
  assets/shared/query-string-router/route.js
  assets/shared/query-string-router/route.test.js
  assets/shared/query-string-router/url-functions.js
  assets/shared/query-string-router/url-functions.test.js
Labels: [Type] Enhancement

#4167 Add extensions update banner
  assets/extensions/card.js
  assets/extensions/extension-actions.js
  assets/extensions/extensions.scss
  assets/extensions/main.js
  assets/extensions/update-notification.js
  assets/extensions/update-notification/index.js
  assets/extensions/update-notification/multiple.js
  assets/extensions/update-notification/single.js
  assets/icons/index.js
  assets/icons/update-icon.js
Labels: [Type] Enhancement

#4179 Dev env fixes (.cache and Husky)
  .gitignore
  .husky/.gitignore
  .husky/post-commit
  .husky/pre-commit
  package.json
Labels: [Type] Maintenance

#4186 Temporarily comment grid view feature
  assets/blocks/learner-courses-block/learner-courses-settings.js
  assets/blocks/learner-courses-block/learner-courses-settings.test.js
Labels: [Type] Enhancement

#4184 Change featured image enabled logic
  includes/class-sensei-course.php
  includes/class-sensei-settings.php
  includes/shortcodes/class-sensei-shortcode-user-courses.php
Labels: [Type] Enhancement

#4180 Add extension card logic
  assets/extensions/all-extensions.js
  assets/extensions/card.js
  assets/extensions/extension-actions.js
  assets/extensions/extensions.scss
  assets/extensions/update-notification/single.js
  assets/shared/styles/_variables.scss
Labels: [Type] Enhancement

#4197 [POC] Dynamic extensions page
  assets/extensions/_TEMP.json
  assets/extensions/all-extensions.js
  assets/extensions/card.js
  assets/extensions/extension-actions.js
  assets/extensions/extensions.scss
  assets/extensions/filtered-extensions.js
  assets/extensions/grid.js
  assets/extensions/main.js
  assets/extensions/tabs.js
  assets/extensions/update-notification/index.js
  assets/extensions/update-notification/multiple.js
  assets/extensions/update-notification/single.js
Labels: [Type] Enhancement

#4198 Add sensei_duplicate_post_args filter
  includes/class-sensei-admin.php
Labels: Hooks, [Type] Enhancement

#4203 Add extension update endpoint
  assets/extensions/main.js
  includes/admin/class-sensei-extensions.php
  includes/rest-api/class-sensei-rest-api-extensions-controller.php
Labels: [Type] Enhancement
