Repository Automattic/sensei, pull requests merged in 2021-11, with the labels that each got.

#4398 Add course navigation base class
  includes/class-sensei-course-navigation.php
  includes/class-sensei-feature-flags.php
  includes/class-sensei.php
  tests/unit-tests/test-class-sensei-course-navigation.php
Labels: [Type] Enhancement

#4403 Fix PHP linter throws an error when the project folder has spaces
  scripts/linter-new-php
Labels: [Type] Maintenance

#4400 Add course navigation template setting
  .github/workflows/php.yml
  assets/js/admin/course-edit.js
  assets/js/admin/course-navigation-template-sidebar.js
  includes/class-sensei-course-navigation.php
Labels: [Type] Enhancement

#4411 Update "Course Navigation" naming to "Course Theme"
  assets/js/admin/course-edit.js
  assets/js/admin/course-theme-sidebar.js
  includes/class-sensei-course-theme.php
  includes/class-sensei-feature-flags.php
  includes/class-sensei.php
  tests/unit-tests/test-class-sensei-course-navigation.php
  tests/unit-tests/test-class-sensei-course-theme.php
Labels: [Type] Enhancement

#4423 Update readme.txt with new description content
  readme.txt
Labels: [Type] Maintenance

#4425 Fix course complete emails not being sent
  includes/class-sensei-frontend.php
Labels: [Type] Bug

#4413 Add course theme templates
  assets/css/fonts/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa0ZL7W0Q5n-wU.woff2
  assets/css/fonts/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7W0Q5nw.woff2
  assets/css/fonts/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1pL7W0Q5n-wU.woff2
  assets/css/fonts/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa25L7W0Q5n-wU.woff2
  assets/css/fonts/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2JL7W0Q5n-wU.woff2
  assets/css/fonts/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2ZL7W0Q5n-wU.woff2
  assets/css/fonts/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2pL7W0Q5n-wU.woff2
  assets/css/sensei-course-theme.scss
  assets/css/sensei-course-theme/fonts.scss
  includes/class-sensei-course-theme.php
  templates/course-theme/index.php
  templates/course-theme/single-lesson.php
  templates/course-theme/single-quiz.php
Labels: [Type] Enhancement, Templates

#4408 Re-style answer feedback frontend
  assets/blocks/quiz/question-block/question.scss
  assets/css/frontend.scss
  includes/class-sensei-question.php
  includes/class-sensei-quiz.php
  includes/hooks/template.php
  templates/single-quiz.php
Labels: Hooks, Deprecation

#4436 Improve sensei theme check to use existing function
  includes/class-sensei-course-theme.php
Labels: [Type] Enhancement

#4433 Add quiz back to lesson block
  assets/css/sensei-course-theme.scss
  assets/css/sensei-course-theme/fonts.scss
  assets/css/sensei-course-theme/quiz-back-to-lesson.scss
  assets/css/sensei-course-theme/sensei-course-theme.scss
  includes/blocks/class-sensei-blocks-initializer.php
  includes/blocks/course-theme/class-course-theme.php
  includes/blocks/course-theme/class-quiz-back-to-lesson.php
  includes/class-sensei-autoloader.php
  includes/class-sensei-course-theme.php
  templates/course-theme/single-quiz.php
  tests/unit-tests/blocks/course-theme/test-class-quiz-back-to-lesson.php
  webpack.config.js
Labels: [Type] Enhancement

#4437 Add quiz button block
  assets/css/sensei-course-theme/buttons.scss
  assets/css/sensei-course-theme/sensei-course-theme.scss
  includes/blocks/class-sensei-view-quiz-block.php
  includes/blocks/course-theme/class-course-theme.php
  includes/blocks/course-theme/class-quiz-button.php
  includes/class-sensei-autoloader.php
  includes/class-sensei-lesson.php
  templates/course-theme/single-lesson.php
  tests/framework/factories/class-sensei-factory.php
  tests/unit-tests/test-class-lesson.php
Labels: [Type] Enhancement

#4410 Make the lesson prerequisite metabox dropdown show lessons from the selected course
  assets/js/admin/lesson-edit.js
  includes/class-sensei-course.php
  includes/class-sensei-lesson.php
  includes/class-sensei-modules.php
  tests/unit-tests/test-class-lesson.php
Labels: [Type] Enhancement

#4452 Restrict the order lessons menu to teachers, authors, and above
  includes/class-sensei-admin.php
Labels: [Type] Bug, [Pri] Normal

#4471 Fix/sidebar icon
  assets/css/fonts/sensei/sensei.eot
  assets/css/fonts/sensei/sensei.svg
  assets/css/fonts/sensei/sensei.ttf
  assets/css/fonts/sensei/sensei.woff
  assets/css/fonts/sensei/sensei.woff2
  assets/css/global.scss
Labels: [Type] Bug

#4474 Tweak wording for incomplete quiz question warning
  assets/blocks/quiz/quiz-block/quiz-validation.js
Labels: [Pri] Low

#4475 Add check so that Authors can only order their own lessons.
  includes/class-sensei-admin.php
Labels: [Type] Bug

#4477 Add new context notices class and submitted quiz notice
  assets/css/frontend.scss
  assets/css/notices.scss
  assets/css/sensei-course-theme/buttons.scss
  assets/css/sensei-course-theme/notices.scss
  assets/css/sensei-course-theme/sensei-course-theme.scss
  includes/blocks/course-theme/class-course-theme.php
  includes/blocks/course-theme/class-notices.php
  includes/blocks/course-theme/class-quiz-back-to-lesson.php
  includes/class-sensei-autoloader.php
  includes/class-sensei-context-notices.php
  includes/course-theme/class-sensei-course-theme-lesson.php
  includes/course-theme/class-sensei-course-theme.php
  templates/course-theme/lesson-quiz-notice.php
  templates/course-theme/single-lesson.php
  tests/unit-tests/course-theme/test-class-sensei-course-theme.php
  tests/unit-tests/test-class-sensei-context-notices.php
Labels: [Type] Enhancement, Hooks
