Repository Automattic/sensei, pull requests merged in 2021-03, with the labels that each got.

#4011 Integrate REST api during saving
  assets/blocks/course-outline/course-outline-store.js
  assets/blocks/quiz/answer-blocks/gap-fill.js
  assets/blocks/quiz/answer-blocks/index.js
  assets/blocks/quiz/answer-blocks/multiple-choice.js
  assets/blocks/quiz/data.js
  assets/blocks/quiz/question-block/question-block-attributes.js
  assets/blocks/quiz/question-block/settings/question-multiple-choice-settings.js
  assets/blocks/quiz/quiz-store.js
  assets/shared/blocks/use-auto-inserter.js
  assets/shared/blocks/use-auto-inserter.test.js
  assets/shared/structure/structure-store.js
  assets/shared/structure/structure-store.test.js
  includes/rest-api/class-sensei-rest-api-lesson-quiz-controller.php
  includes/rest-api/class-sensei-rest-api-question-helpers-trait.php
Labels: Hooks, [Type] Enhancement

#4027 Fix course structure infinite loop
  assets/blocks/course-outline/course-outline-store.js
  assets/shared/structure/structure-store.js
Labels: [Type] Bug

#4018 Add the quiz block when the quiz is enabled for lesson
  includes/class-sensei-posttypes.php
  includes/rest-api/class-sensei-rest-api-lessons-controller.php
Labels: [Type] Enhancement

#4029 Synchronize question API and block attribute schema
  assets/blocks/quiz/answer-blocks/gap-fill.js
  assets/blocks/quiz/answer-blocks/multiple-choice-answer-option.js
  assets/blocks/quiz/answer-blocks/multiple-choice.js
  assets/blocks/quiz/answer-blocks/true-false.js
  assets/blocks/quiz/data.js
  assets/blocks/quiz/question-block/question-block-attributes.js
  assets/blocks/quiz/quiz-store.js
  includes/rest-api/class-sensei-rest-api-question-helpers-trait.php
  tests/unit-tests/rest-api/test-class-sensei-rest-api-lesson-quiz-controller.php
Labels: Hooks

#4006 Fix fatal error when `post_password_required` is called early
  includes/class-sensei-posttypes.php
Labels: [Type] Bug

#4026 Filter the block templates
  includes/blocks/class-sensei-course-blocks.php
  includes/blocks/class-sensei-lesson-blocks.php
Labels: Hooks

#4023 Use block button styles for quiz actions
  assets/css/frontend.scss
  includes/blocks/class-sensei-blocks.php
  includes/blocks/class-sensei-course-blocks.php
  includes/class-sensei-course.php
  includes/class-sensei-messages.php
  includes/class-sensei-notices.php
  includes/class-sensei-quiz.php
Labels: Templates

#4033 Handle quiz status based on block presence and question count
  assets/blocks/quiz/quiz-block/quiz-edit.js
  assets/blocks/quiz/quiz-block/use-has-questions.js
  includes/rest-api/class-sensei-rest-api-lessons-controller.php
Labels: [Type] Enhancement

#4070 Fix texarea with null value
  assets/blocks/quiz/question-block/settings/question-answer-feedback-settings.js
  assets/blocks/quiz/question-block/settings/question-grading-notes-settings.js
Labels: [Type] Bug

#4075 Fix log event plugin updated minor test break
  tests/unit-tests/test-class-sensei-updates.php
Labels: [Type] Maintenance

#4069 Fix existing questions filter in WP 5.7
  assets/blocks/quiz/quiz-block/questions-modal/questions.js
Labels: [Type] Bug

#4079 Fix some question filters in API docs
  includes/class-sensei-question.php
  includes/rest-api/class-sensei-rest-api-question-helpers-trait.php
Labels: [Type] Maintenance

#4076 Allow draft questions if they are not in a quiz
  includes/blocks/class-sensei-blocks.php
  includes/class-sensei-quiz.php
  includes/rest-api/class-sensei-rest-api-question-helpers-trait.php
  includes/rest-api/class-sensei-rest-api-questions-controller.php
  tests/unit-tests/rest-api/test-class-sensei-rest-api-questions-controller.php
Labels: [Type] Enhancement

#4084 Fix existing questions modal autoclosed
  assets/blocks/quiz/quiz-block/questions-modal/actions.js
  assets/blocks/quiz/quiz-block/questions-modal/index.js
  assets/blocks/quiz/quiz-block/quiz-appender.js
  assets/blocks/quiz/quiz-block/quiz-edit.js
Labels: [Type] Bug

#4086 Avoid overriding non-editable question
  assets/blocks/quiz/quiz-store.js
Labels: [Type] Bug

#4090 Add categories to the calc of maximum number of questions in a quiz
  assets/blocks/quiz/quiz-block/quiz-settings.js
  assets/blocks/quiz/quiz-block/quiz-settings.test.js
Labels: [Type] Enhancement

#4094 Removes user filter temporarily, while running preload queries
  includes/class-sensei-assets.php
Labels: [Type] Bug

#4093 Fix editable check
  assets/blocks/quiz/quiz-store.js
Labels: [Type] Bug

#4085 Merge changes from sensei-audit repo
  assets/css/meta-box-quiz-editor.scss
  includes/class-sensei-analysis-user-profile-list-table.php
  includes/class-sensei-analysis.php
  includes/class-sensei-grading.php
  includes/class-sensei-lesson.php
  includes/class-sensei-quiz.php
  includes/class-sensei-teacher.php
Labels: [Type] Maintenance

#4096 Add a temporary solution to a React error in the quiz appender
  assets/blocks/quiz/quiz-block/quiz-edit.js
Labels: [Type] Bug

#4098 Rename quiz appender component
  assets/blocks/quiz/quiz-block/quiz-edit.js
Labels: [Type] Enhancement

#4099 Release 3.9.0 Beta 1
  changelog.txt
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
Labels: [Type] Maintenance

#4100 Fix page "dancing" while clicking on quiz appender
  assets/blocks/quiz/quiz-block/quiz-appender.js
Labels: [Type] Bug

#4109 Update existing questions modal to not show already added questions
  assets/blocks/quiz/quiz-block/questions-modal/index.js
  assets/blocks/quiz/quiz-block/questions-modal/questions.js
Labels: [Type] Enhancement

#4112 Add Sensei block category on the top of the categories list
  includes/blocks/class-sensei-blocks.php
Labels: [Type] Enhancement

#4124 Release 3.9.0
  changelog.txt
  lang/sensei-lms.pot
  readme.txt
  sensei-lms.php
Labels: [Type] Maintenance

#4122 Add learner courses block
  assets/blocks/learner-courses-block/block.json
  assets/blocks/learner-courses-block/index.js
  assets/blocks/learner-courses-block/learner-courses-edit.js
  assets/blocks/learner-courses-block/learner-courses-settings.js
  assets/blocks/learner-courses-block/learner-courses-settings.test.js
  assets/blocks/learner-courses-block/learner-courses.scss
  assets/blocks/shared.js
  assets/blocks/single-page-style.scss
  assets/blocks/single-page.js
  assets/icons/index.js
  assets/icons/learner-courses-icon.js
  includes/blocks/class-sensei-blocks-initializer.php
  includes/blocks/class-sensei-blocks.php
  includes/blocks/class-sensei-learner-courses-block.php
  includes/blocks/class-sensei-page-blocks.php
  package-lock.json
  package.json
  webpack.config.js
Labels: [Type] Enhancement

#4132 Remove compat gutenberg
  assets/vendor/gutenberg/api-fetch.js
  assets/vendor/gutenberg/api-fetch.min.js
  assets/vendor/gutenberg/components.js
  assets/vendor/gutenberg/components.min.js
  assets/vendor/gutenberg/compose.js
  assets/vendor/gutenberg/compose.min.js
  assets/vendor/gutenberg/data.js
  assets/vendor/gutenberg/data.min.js
  assets/vendor/gutenberg/element.js
  assets/vendor/gutenberg/element.min.js
  assets/vendor/gutenberg/primitives.js
  assets/vendor/gutenberg/primitives.min.js
  assets/vendor/gutenberg/priority-queue.js
  assets/vendor/gutenberg/priority-queue.min.js
  assets/vendor/gutenberg/react-dom.js
  assets/vendor/gutenberg/react-dom.min.js
  assets/vendor/gutenberg/react.js
  assets/vendor/gutenberg/react.min.js
  assets/vendor/gutenberg/redux-routine.js
  assets/vendor/gutenberg/redux-routine.min.js
  assets/vendor/gutenberg/warning.js
  assets/vendor/gutenberg/warning.min.js
  assets/vendor/gutenberg/wp-polyfill.js
  assets/vendor/gutenberg/wp-polyfill.min.js
  includes/admin/class-sensei-setup-wizard.php
  includes/class-sensei-assets.php
  includes/data-port/class-sensei-import.php
Labels: [Type] Maintenance

#4139 Add notice when messages are disabled and Learner Messages Button block is used
  assets/blocks/learner-messages-button-block/index.js
  assets/blocks/learner-messages-button-block/messages-disabled-notice.js
  includes/blocks/class-sensei-learner-messages-button-block.php
Labels: [Type] Enhancement

#4150 Release 3.9.1
  changelog.txt
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
Labels: [Type] Maintenance
