Repository Automattic/sensei, pull requests merged in 2022-11, with the labels that each got.

#6010 Fix Course List buttons extending outside container
  assets/blocks/button/button.scss
Labels: Course List Block

#6034 Fix some issues with author names getting appended to module names
  includes/class-sensei-modules.php
Labels: [Type] Bug

#6080 Avoid defining already defined constants
  sensei-lms.php
Labels: [Type] Bug

#6058 Fix contact teacher block check
  includes/blocks/class-sensei-block-contact-teacher.php
  includes/blocks/class-sensei-lesson-blocks.php
Labels: [Type] Bug

#5894 Add student progress tables based repository
  includes/class-sensei-autoloader.php
  includes/internal/quiz-submission/submission/repositories/class-comments-based-submission-repository.php
  includes/internal/student-progress/course-progress/repositories/class-aggregate-course-progress-repository.php
  includes/internal/student-progress/course-progress/repositories/class-course-progress-repository-factory.php
  includes/internal/student-progress/course-progress/repositories/class-tables-based-course-progress-repository.php
  includes/internal/student-progress/lesson-progress/repositories/class-aggregate-lesson-progress-repository.php
  includes/internal/student-progress/lesson-progress/repositories/class-lesson-progress-repository-factory.php
  includes/internal/student-progress/lesson-progress/repositories/class-tables-based-lesson-progress-repository.php
  includes/internal/student-progress/quiz-progress/repositories/class-aggregate-quiz-progress-repository.php
  includes/internal/student-progress/quiz-progress/repositories/class-quiz-progress-repository-factory.php
  includes/internal/student-progress/quiz-progress/repositories/class-tables-based-quiz-progress-repository.php
  tests/unit-tests/internal/student-progress/course-progress/repositories/test-class-aggregate-course-progress-repository.php
  tests/unit-tests/internal/student-progress/course-progress/repositories/test-class-course-progress-repository-factory.php
  tests/unit-tests/internal/student-progress/course-progress/repositories/test-class-tables-based-course-progress-repository.php
  tests/unit-tests/internal/student-progress/lesson-progress/repositories/test-class-aggregate-lesson-progress-repository.php
  tests/unit-tests/internal/student-progress/lesson-progress/repositories/test-class-lesson-progress-repository-factory.php
  tests/unit-tests/internal/student-progress/lesson-progress/repositories/test-class-tables-based-lesson-progress-repository.php
  tests/unit-tests/internal/student-progress/quiz-progress/repositories/test-class-aggregate-quiz-progress-repository.php
  tests/unit-tests/internal/student-progress/quiz-progress/repositories/test-class-quiz-progress-repository-factory.php
  tests/unit-tests/internal/student-progress/quiz-progress/repositories/test-class-tables-based-quiz-progress-repository.php
Labels: [Type] Maintenance

#6076 Cleanup student progress when course/lesson/quiz/user deleted
  includes/class-sensei-autoloader.php
  includes/class-sensei.php
  includes/internal/student-progress/course-progress/repositories/class-aggregate-course-progress-repository.php
  includes/internal/student-progress/course-progress/repositories/class-comments-based-course-progress-repository.php
  includes/internal/student-progress/course-progress/repositories/class-course-progress-repository-interface.php
  includes/internal/student-progress/course-progress/repositories/class-tables-based-course-progress-repository.php
  includes/internal/student-progress/lesson-progress/repositories/class-aggregate-lesson-progress-repository.php
  includes/internal/student-progress/lesson-progress/repositories/class-comments-based-lesson-progress-repository.php
  includes/internal/student-progress/lesson-progress/repositories/class-lesson-progress-repository-interface.php
  includes/internal/student-progress/lesson-progress/repositories/class-tables-based-lesson-progress-repository.php
  includes/internal/student-progress/quiz-progress/repositories/class-aggregate-quiz-progress-repository.php
  includes/internal/student-progress/quiz-progress/repositories/class-comments-based-quiz-progress-repository.php
  includes/internal/student-progress/quiz-progress/repositories/class-quiz-progress-repository-interface.php
  includes/internal/student-progress/quiz-progress/repositories/class-tables-based-quiz-progress-repository.php
  includes/internal/student-progress/services/class-course-deleted-handler.php
  includes/internal/student-progress/services/class-lesson-deleted-handler.php
  includes/internal/student-progress/services/class-quiz-deleted-handler.php
  includes/internal/student-progress/services/class-user-deleted-handler.php
  tests/unit-tests/internal/student-progress/course-progress/repositories/test-class-aggregate-course-progress-repository.php
  tests/unit-tests/internal/student-progress/course-progress/repositories/test-class-comments-based-course-progress-repository.php
  tests/unit-tests/internal/student-progress/course-progress/repositories/test-class-tables-based-course-progress-repository.php
  tests/unit-tests/internal/student-progress/lesson-progress/repositories/test-class-aggregate-lesson-progress-repository.php
  tests/unit-tests/internal/student-progress/lesson-progress/repositories/test-class-comments-based-lesson-progress-repository.php
  tests/unit-tests/internal/student-progress/lesson-progress/repositories/test-class-tables-based-lesson-progress-repository.php
  tests/unit-tests/internal/student-progress/quiz-progress/repositories/test-class-aggregate-quiz-progress-repository.php
  tests/unit-tests/internal/student-progress/quiz-progress/repositories/test-class-comments-based-quiz-progress-repository.php
  tests/unit-tests/internal/student-progress/quiz-progress/repositories/test-class-tables-based-quiz-progress-repository.php
  tests/unit-tests/internal/student-progress/services/test-class-course-deleted-handler.php
  tests/unit-tests/internal/student-progress/services/test-class-lesson-deleted-handler.php
  tests/unit-tests/internal/student-progress/services/test-class-quiz-deleted-handler.php
  tests/unit-tests/internal/student-progress/services/test-class-user-deleted-handler.php
Labels: [Type] Maintenance

#6098 Fix issue with outdated NodeJS versions being used on Github Actions
  .github/workflows/build-docs.yml
  .github/workflows/build.yml
  .github/workflows/code-coverage.yml
  .github/workflows/e2e-playwright.yml
  .github/workflows/js.yml
  .github/workflows/php.yml
  .github/workflows/report-build.yml
Labels: [Type] Maintenance

#5376 Fix module teacher name not showing for modules added to course in legacy way
  includes/class-sensei-modules.php
  tests/unit-tests/test-class-modules.php
Labels: Modules, Legacy

#6115 Add/coteachers metabox hook
  assets/css/admin-custom.scss
  includes/class-sensei-modules.php
  includes/class-sensei-teacher.php
  includes/rest-api/class-sensei-rest-api-lesson-quiz-controller.php
Labels: Hooks

#6117 Fix issue with YouTube adapter's setCurrentTime
  assets/shared/helpers/player/youtube-adapter.js
Labels: [Type] Bug

#6132 Make Last Activity column non-sortable
  includes/admin/class-sensei-learners-admin-bulk-actions-view.php
  tests/unit-tests/admin/test-class-sensei-learners-admin-bulk-actions-view.php
Labels: [Type] Bug

#6130 Load persisted notices on user metas only when printing them
  includes/class-sensei-notices.php
Labels: [Type] Bug

#6084 Update Featured label and course categories block styles
  assets/blocks/course-categories-block/course-categories-edit.js
  assets/blocks/course-categories-block/course-categories-edit.test.js
  assets/blocks/course-categories-block/course-categories-editor.scss
  assets/blocks/course-categories-block/course-categories.scss
  assets/blocks/course-list-block/course-list.scss
  assets/blocks/course-list-block/featured-label/index.js
  assets/blocks/global-blocks-style-editor.scss
  includes/blocks/class-sensei-course-categories-block.php
  includes/blocks/class-sensei-page-blocks.php
Labels: Theme

#6085 Fix Question Category admin page to display intended post_type
  includes/class-sensei-question.php
Labels: [Type] Bug

#6127 Make the view quiz button behave as a complete lesson button when watching a video is required
  includes/blocks/class-sensei-view-quiz-block.php
Labels: [Type] Enhancement

#6129 Ensure quiz author is set correctly when the quiz is initially created
  includes/class-sensei-quiz.php
  tests/unit-tests/test-class-quiz.php
Labels: Co-Teachers

#6070 Enable customize the lesson status icons
  includes/blocks/course-theme/class-course-navigation.php
Labels: Theme

#6153 Add compatibility for WP < 6.0 on quiz author fix
  includes/class-sensei-quiz.php
Labels: Co-Teachers

#6139 Fix home styles
  assets/home/home.shared.scss
  assets/home/tasks-section/style.scss
Labels: [Type] Bug

#6066 Skip opinionated styles when the active theme supports learning mode ui customizations
  assets/css/learning-mode-compat.scss
  assets/css/learning-mode.4-0-2.scss
  assets/css/learning-mode.scss
  assets/css/sensei-course-theme/base.scss
  assets/css/sensei-course-theme/blocks/course-title.scss
  assets/css/sensei-course-theme/blocks/lesson-actions.scss
  assets/css/sensei-course-theme/blocks/lesson-module.scss
  includes/blocks/class-sensei-blocks.php
  includes/course-theme/class-sensei-course-theme.php
  themes/sensei-course-theme/templates/default/lesson.html
  webpack.config.js
Labels: Theme

#6157 Prepare grading to support co-teachers.
  includes/class-sensei-grading-main.php
  includes/class-sensei-grading.php
  includes/class-sensei-teacher.php
  includes/class-sensei-utils.php
Labels: Hooks

#6140 Avoid quiz check when it's in a preview
  assets/blocks/quiz/quiz-block/use-update-quiz-has-questions-meta.js
  includes/class-sensei-lesson.php
Labels: [Type] Bug

#6134 Fix SQL performance issue on the student reports page
  includes/reports/overview/data-provider/class-sensei-reports-overview-data-provider-students.php
Labels: [Type] Bug

#6167 Fix some issues with the teacher's Students view
  assets/admin/students/student-modal/course-list.js
  includes/admin/class-sensei-learners-admin-bulk-actions-view.php
  includes/class-sensei-learner.php
  tests/unit-tests/admin/test-class-sensei-learners-admin-bulk-actions-view.php
Labels: [Type] Bug, Co-Teachers

#6164 Add quiz appender filter
  assets/blocks/quiz/quiz-block/quiz-appender.js
Labels: Hooks, Co-Teachers

#6169 Add landing page patterns
  assets/blocks/course-categories-block/block.json
  assets/blocks/course-list-block/course-list.scss
  assets/css/page-block-patterns.scss
  assets/images/testimonial.png
  includes/block-patterns/class-sensei-block-patterns.php
  includes/block-patterns/course-list/class-sensei-course-list-block-patterns.php
  includes/block-patterns/page/landing-page-grid.php
  includes/block-patterns/page/landing-page-list.php
  includes/block-patterns/page/templates/landing-page-grid.php
  includes/block-patterns/page/templates/landing-page-list.php
  webpack.config.js
Labels: Theme

#6068 Enable to customize sidebar-width and header-height via css variables
  assets/css/sensei-course-theme/4-0-2/layout.scss
  assets/css/sensei-course-theme/4-0-2/mobile.scss
  assets/css/sensei-course-theme/editor.scss
  assets/css/sensei-course-theme/fixed-sidebar.scss
  assets/css/sensei-course-theme/focus-mode.scss
  assets/css/sensei-course-theme/layout.scss
  assets/css/sensei-course-theme/theme-fixes.scss
  assets/css/sensei-course-theme/ui-blocks.scss
  assets/css/sensei-course-theme/video-container.scss
Labels: Theme

#6182 Add onboarding theme step
  assets/images/onboarding-theme-learning-mode-1.webp
  assets/images/onboarding-theme-learning-mode-2.webp
  assets/images/onboarding-theme-learning-mode-3.webp
  assets/images/onboarding-theme-main.webp
  assets/images/onboarding-theme-mobile-1.webp
  assets/images/onboarding-theme-mobile-2.webp
  assets/images/onboarding-theme-mobile-3.webp
  assets/images/onboarding-theme-mobile-4.webp
  assets/images/onboarding-theme-mobile-5.webp
  assets/images/onboarding-theme-quote-author.webp
  assets/images/onboarding-theme-small-mobile-1.webp
  assets/images/onboarding-theme-small-mobile-2.webp
  assets/images/onboarding-theme-small-mobile-3.webp
  assets/react-hooks/index.js
  assets/react-hooks/use-dragging.js
  assets/setup-wizard/fullscreen.scss
  assets/setup-wizard/index.js
  assets/setup-wizard/purpose/index.js
  assets/setup-wizard/steps.js
  assets/setup-wizard/style.scss
  assets/setup-wizard/theme/big-screen.js
  assets/setup-wizard/theme/carousel.js
  assets/setup-wizard/theme/carousel.scss
  assets/setup-wizard/theme/index.js
  assets/setup-wizard/theme/small-screen.js
  assets/setup-wizard/theme/style.scss
  includes/class-sensei-admin.php
  tests/e2e-playwright/specs/admin/students/setup-wizard.spec.js
  webpack.config.js
Labels: New Onboarding Wizard

#6193 Move usage tracking for purpose step to usage tracking save
  includes/rest-api/class-sensei-rest-api-setup-wizard-controller.php
  tests/unit-tests/admin/test-class-sensei-setup-wizard-api.php
Labels: Logging, New Onboarding Wizard

#6186 Fix YouTube embed handling on some environments
  assets/shared/helpers/player/use-editor-player.js
  includes/course-video/class-sensei-course-video-settings.php
Labels: [Type] Enhancement

#6162 Feature coteachers.
  assets/admin/students/student-modal/course-list.js
  assets/blocks/quiz/quiz-block/quiz-appender.js
  assets/css/admin-custom.scss
  assets/js/admin/course-general-sidebar.js
  includes/admin/class-sensei-learners-admin-bulk-actions-view.php
  includes/class-sensei-grading-main.php
  includes/class-sensei-grading.php
  includes/class-sensei-learner.php
  includes/class-sensei-modules.php
  includes/class-sensei-teacher.php
  includes/class-sensei-utils.php
  includes/rest-api/class-sensei-rest-api-lesson-quiz-controller.php
  sensei-lms.php
  tests/unit-tests/admin/test-class-sensei-learners-admin-bulk-actions-view.php
Labels: Hooks

#6168 Fix double query when calling `WP_Query::get_posts`
  includes/admin/tools/class-sensei-tool-enrolment-debug.php
  includes/class-sensei-lesson.php
  includes/data-port/export-tasks/class-sensei-export-courses.php
Labels: [Type] Bug, [Pri] Low
