Repository Automattic/sensei, pull requests merged in 2022-01, with the labels that each got.

#4577 Add course navigation extra icons
  assets/blocks/contact-teacher-block/contact-teacher.scss
  assets/course-theme/complete-lesson-button.js
  assets/css/global.scss
  assets/css/inter-font.scss
  assets/css/sensei-course-theme/course-navigation.scss
  assets/css/sensei-course-theme/lesson-complete-transition.scss
  assets/css/sensei-course-theme/notices.scss
  assets/images/svg-icons/README.md
  assets/images/svg-icons/check-circle.svg
  assets/images/svg-icons/check-filled-circle.svg
  assets/images/svg-icons/circle.svg
  assets/images/svg-icons/close.svg
  assets/images/svg-icons/eye.svg
  assets/images/svg-icons/half-filled-circle.svg
  assets/images/svg-icons/lesson-status-completed.svg
  assets/images/svg-icons/lesson-status-in-progress.svg
  assets/images/svg-icons/lesson-status-not-started.svg
  assets/images/svg-icons/lock.svg
  assets/images/svg-icons/sensei.svg
  includes/blocks/class-sensei-course-navigation-block.php
  includes/course-theme/class-sensei-course-theme-quiz.php
  includes/course-theme/class-sensei-course-theme.php
Labels: [Type] Enhancement

#4578 Change icons folder
  assets/blocks/conditional-content-block/index.js
  assets/blocks/course-outline/lesson-block/index.js
  assets/blocks/course-outline/module-block/index.js
  assets/blocks/course-outline/outline-block/index.js
  assets/blocks/course-outline/outline-block/outline-appender.js
  assets/blocks/course-progress-block/index.js
  assets/blocks/course-results-block/index.js
  assets/blocks/learner-courses-block/index.js
  assets/blocks/lesson-actions/lesson-actions-block/index.js
  assets/blocks/lesson-properties/index.js
  assets/blocks/quiz/answer-feedback-block/index.js
  assets/blocks/quiz/category-question-block/index.js
  assets/blocks/quiz/question-answers-block/index.js
  assets/blocks/quiz/question-block/index.js
  assets/blocks/quiz/question-block/question-block-helpers.js
  assets/blocks/quiz/question-description-block/index.js
  assets/blocks/quiz/quiz-block/index.js
  assets/blocks/quiz/quiz-block/quiz-appender.js
  assets/blocks/register-sensei-blocks.js
  assets/extensions/extension-actions.js
  assets/extensions/update-notification/index.js
  assets/extensions/update-notification/update-available.js
  assets/icons/README.md
  assets/icons/alert.svg
  assets/icons/buttons.svg
  assets/icons/check-circle.svg
  assets/icons/check-filled-circle.svg
  assets/icons/checked.svg
  assets/icons/chevron-left.svg
  assets/icons/chevron-right.svg
  assets/icons/chevron-up.svg
  assets/icons/circle.svg
  assets/icons/close.svg
  assets/icons/conditional-content.svg
  assets/icons/course.svg
  assets/icons/eye.svg
  assets/icons/half-filled-circle.svg
  assets/icons/learner-courses.svg
  assets/icons/lesson-properties.svg
  assets/icons/lesson.svg
  assets/icons/lock.svg
  assets/icons/menu.svg
  assets/icons/module.svg
  assets/icons/progress.svg
  assets/icons/question.svg
  assets/icons/quiz.svg
  assets/icons/sensei.svg
  assets/icons/update.svg
  includes/class-sensei-assets.php
  webpack.config.js
Labels: [Type] Enhancement

#4594 Add filters and actions to support quiz timer
  assets/blocks/quiz/quiz-store.js
  includes/rest-api/class-sensei-rest-api-lesson-quiz-controller.php
Labels: Hooks

#4580 Fix course theme start lesson
  includes/class-sensei-lesson.php
Labels: [Type] Bug

#4598 Remove quizStructureStore filter
  assets/blocks/quiz/quiz-store.js
Labels: [Type] Maintenance

#4521 Save the quiz pagination form state between pages
  assets/css/_mixins.scss
  assets/css/frontend.scss
  includes/class-sensei-question.php
  includes/class-sensei-quiz.php
  includes/hooks/template.php
  templates/single-quiz.php
  templates/single-quiz/pagination.php
  tests/unit-tests/test-class-quiz.php
Labels: [Type] Enhancement

#4597 Add a button to the quiz block that opens the quiz settings
  assets/blocks/quiz/quiz-block/quiz-settings.js
  assets/blocks/quiz/quiz-block/quiz-settings.test.js
  assets/blocks/quiz/quiz-block/use-open-quiz-settings.js
  assets/blocks/quiz/quiz.editor.scss
  assets/icons/cog.svg
Labels: [Type] Enhancement

#4579 Make the quiz buttons consistent
  assets/css/frontend.scss
  includes/class-sensei-quiz.php
  templates/single-quiz/pagination.php
Labels: [Type] Enhancement

#4572 Rename CourseProgress to more generic ProgressBar
  assets/blocks/course-progress-block/course-progress-edit.js
  assets/blocks/course-progress-block/course-progress-editor.scss
  assets/blocks/course-progress-block/course-progress.scss
  assets/blocks/learner-courses-block/learner-courses-edit.js
  assets/blocks/learner-courses-block/learner-courses-editor.scss
  assets/blocks/learner-courses-block/learner-courses-settings.js
  assets/blocks/learner-courses-block/learner-courses.scss
  assets/shared/blocks/course-progress/index.js
  assets/shared/blocks/progress-bar/index.js
  assets/shared/blocks/progress-bar/progress-bar-settings.js
  assets/shared/blocks/progress-bar/progress-bar-settings.scss
  assets/shared/blocks/progress-bar/progress-bar.js
  assets/shared/blocks/progress-bar/progress-bar.scss
  assets/shared/blocks/progress-bar/progress-bar.test.js
  includes/blocks/class-sensei-course-progress-block.php
Labels: Courses, Blocks

#4604 Fix edge case where the quiz status doesn't exist
  includes/course-theme/class-sensei-course-theme-quiz.php
Labels: [Type] Bug

#4609 Fix comments pagination on lesson page
  includes/renderers/class-sensei-renderer-single-post.php
Labels: [Type] Bug

#4602 Fix grade message with decimals
  includes/class-sensei-utils.php
  includes/course-theme/class-sensei-course-theme-lesson.php
  includes/course-theme/class-sensei-course-theme-quiz.php
  tests/unit-tests/course-theme/test-class-sensei-course-theme-lesson.php
Labels: [Type] Bug

#4611 Add a 3-second delay before autocompleting the lesson
  assets/js/frontend/course-video/video-blocks-extension.js
Labels: [Type] Enhancement

#4613 Course Theme sidebar UX improvements
  assets/css/sensei-course-theme/focus-mode.scss
  assets/icons/double-chevron-right.svg
  includes/blocks/class-sensei-course-navigation-block.php
  includes/blocks/course-theme/class-focus-mode.php
  themes/sensei-course-theme/single.php
Labels: [Type] Enhancement

#4616 Add course theme notice
  assets/css/global.scss
  includes/admin/class-sensei-admin-notices.php
  includes/admin/class-sensei-wccom-connect-notice.php
  includes/admin/class-sensei-wcpc-prompt.php
  includes/class-sensei-assets.php
  includes/course-theme/class-sensei-course-theme-option.php
  templates/course-theme/lesson-quiz-notice.php
  templates/course-theme/locked-lesson-notice.php
Labels: [Type] Enhancement, Hooks

#4617 Update module button to have the collapsible action
  assets/css/sensei-course-theme/course-navigation.scss
  includes/blocks/class-sensei-course-navigation-block.php
Labels: [Type] Enhancement

#4599 Add course theme onboarding
  assets/css/course-editor.scss
  assets/images/onboarding-learning-mode-check.jpg
  assets/images/onboarding-learning-mode.jpg
  assets/js/admin/course-edit.js
  assets/js/admin/course-theme/constants.js
  assets/js/admin/course-theme/course-theme-onboarding.js
  assets/js/admin/course-theme/course-theme-sidebar.js
  assets/js/admin/course-theme/guide.js
  assets/js/admin/course-theme/index.js
  includes/class-sensei-course.php
  includes/course-theme/class-sensei-course-theme.php
  package-lock.json
  package.json
  webpack.config.js
Labels: [Type] Enhancement

#4606 Frontend for progress bar related to pagination
  assets/blocks/progress-bar.js
  assets/blocks/quiz/quiz-block/pagination-settings.js
  assets/blocks/shared-style.scss
  assets/blocks/single-course-style-editor.scss
  assets/shared/blocks/progress-bar/progress-bar.js
  includes/class-sensei-frontend.php
  includes/class-sensei-quiz.php
  includes/hooks/template.php
  includes/rest-api/class-sensei-rest-api-lesson-quiz-controller.php
  templates/globals/progress-bar.php
  tests/unit-tests/rest-api/test-class-sensei-rest-api-lesson-quiz-controller.php
  webpack.config.js
Labels: Hooks, UI

#4612 Add styles for the disabled button in the lesson template
  assets/css/frontend.scss
Labels: [Type] Enhancement

#4626 Change since version from 4.0.0 to 3.15.0
  includes/course-video/blocks/class-sensei-course-video-blocks-embed-extension.php
  includes/course-video/blocks/class-sensei-course-video-blocks-video-extension.php
  includes/course-video/blocks/class-sensei-course-video-blocks-vimeo-extension.php
  includes/course-video/blocks/class-sensei-course-video-blocks-youtube-extension.php
  includes/course-video/class-sensei-course-video-settings.php
Labels: [Type] Maintenance

#4628 Check pause method exists for given object
  assets/js/frontend/course-video/video-blocks-extension.js
Labels: [Type] Bug

#4618 Update menu structure
  assets/css/global.scss
  includes/admin/class-sensei-admin-notices.php
  includes/admin/class-sensei-extensions.php
  includes/admin/class-sensei-learner-management.php
  includes/admin/class-sensei-tools.php
  includes/admin/views/html-admin-page-tools-header.php
  includes/class-sensei-admin.php
  includes/class-sensei-analysis.php
  includes/class-sensei-grading.php
  includes/class-sensei-messages.php
  includes/class-sensei-modules.php
  includes/class-sensei-posttypes.php
  includes/class-sensei-settings-api.php
  includes/class-sensei-settings.php
  includes/class-sensei.php
  includes/data-port/class-sensei-export.php
  includes/data-port/class-sensei-import.php
  tests/unit-tests/admin/test-class-sensei-extensions.php
Labels: Deprecation

#4565 Learner mode settings
  assets/js/admin/course-theme/constants.js
  assets/js/admin/course-theme/course-theme-sidebar.js
  assets/js/settings.js
  includes/class-sensei-course.php
  includes/class-sensei-settings.php
  includes/course-theme/class-sensei-course-theme-option.php
  includes/course-theme/class-sensei-course-theme.php
  tests/unit-tests/course-theme/test-class-sensei-course-theme-option.php
  tests/unit-tests/course-theme/test-class-sensei-course-theme.php
Labels: [Type] Enhancement, Hooks, [Status] Needs Design

#4637 Fix lesson course metabox request infinite loop
  includes/rest-api/class-sensei-rest-api-lesson-quiz-controller.php
Labels: [Type] Bug

#4620 Update design of progress bar
  assets/blocks/course-progress-block/course-progress-edit.js
  assets/blocks/learner-courses-block/learner-courses-edit.js
  assets/blocks/progress-bar.js
  assets/blocks/quiz/quiz-block/quiz-edit.js
  assets/blocks/quiz/quiz-block/quiz-progress-bar-edit.js
  assets/blocks/quiz/quiz-block/quiz-progress-bar-edit.test.js
  assets/blocks/quiz/quiz.editor.scss
  assets/shared/blocks/progress-bar/progress-bar.js
  assets/shared/blocks/progress-bar/progress-bar.scss
  assets/shared/blocks/progress-bar/progress-bar.test.js
  includes/blocks/class-sensei-course-progress-block.php
  templates/globals/progress-bar.php
Labels: UI

#4629 Add quiz button color settings
  assets/blocks/quiz/quiz-block/block.json
  assets/blocks/quiz/quiz-block/pagination-settings.js
  assets/blocks/quiz/quiz-block/quiz-settings.js
  includes/class-sensei-quiz.php
  includes/rest-api/class-sensei-rest-api-lesson-quiz-controller.php
  templates/single-quiz/pagination.php
  tests/unit-tests/rest-api/test-class-sensei-rest-api-lesson-quiz-controller.php
Labels: [Type] Enhancement

#4624 Add Video settings panel to the lesson sidebar
  includes/class-sensei-lesson.php
Labels: [Type] Enhancement

#4632 Add quiz progress notice on Lesson page
  includes/course-theme/class-sensei-course-theme-lesson.php
  includes/course-theme/class-sensei-course-theme-option.php
  tests/unit-tests/course-theme/test-class-sensei-course-theme-lesson.php
Labels: [Type] Enhancement

#4641 Return wp_nonce_field result instead of output it immediately
  includes/blocks/class-sensei-block-contact-teacher.php
Labels: [Type] Bug

#4649 Hide Lesson Actions block when learning mode is enabled
  assets/blocks/lesson-actions/lesson-actions-block/lesson-actions-edit.js
  assets/blocks/lesson-actions/lesson-actions-block/lesson-actions-editor.scss
  includes/blocks/class-sensei-lesson-actions-block.php
  includes/blocks/class-sensei-lesson-blocks.php
  includes/class-sensei-course.php
  tests/unit-tests/course-theme/test-class-sensei-course-theme-option.php
Labels: [Type] Enhancement

#4653 Fix PHP 7.0 compatibility
  includes/class-sensei-messages.php
  includes/rest-api/class-sensei-rest-api-send-message-controller.php
Labels: [Type] Bug

#4656 Fix JSON named exports
  assets/js/admin/course-theme/course-theme-sidebar.js
Labels: [Type] Bug

#4657 Fix the quiz block not rendering
  assets/blocks/quiz/quiz-block/quiz-settings.js
Labels: [Type] Bug

#4661 Release 3.15.2
  changelog.txt
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
Labels: [Type] Maintenance

#4652 Hide admin bar for non editor users on learning mode pages.
  includes/course-theme/class-sensei-course-theme-option.php
  tests/unit-tests/course-theme/test-class-sensei-course-theme-option.php
Labels: [Type] Enhancement

#4660 Add PHP 7.1 and 7.2 versions to PHPUnit tests
  .github/workflows/php.yml
  tests/unit-tests/course-theme/test-class-sensei-course-theme-lesson.php
  tests/unit-tests/test-class-quiz.php
Labels: [Type] Maintenance

#4662 Remove Course Theme feature flag checks
  assets/js/admin/course-edit.js
  includes/blocks/class-sensei-blocks.php
  includes/class-sensei-customizer.php
  includes/class-sensei-feature-flags.php
  includes/class-sensei-settings.php
  includes/class-sensei-usage-tracking-data.php
  includes/class-sensei.php
  includes/course-theme/class-sensei-course-theme-editor.php
  includes/course-theme/class-sensei-course-theme-option.php
  includes/course-theme/class-sensei-course-theme.php
  tests/bootstrap.php
  tests/unit-tests/test-class-sensei-usage-tracking-data.php
Labels: [Type] Maintenance

#4651 Disable PHP 8 unit testing
  .github/workflows/php.yml
Labels: [Type] Maintenance

#4647 Add blocks from quiz template
  assets/course-theme/blocks/blocks.js
  assets/css/frontend.scss
  assets/css/sensei-course-theme/blockbase-ponyfill.scss
  assets/css/sensei-course-theme/buttons.scss
  assets/css/sensei-course-theme/content.scss
  assets/css/sensei-course-theme/lesson-complete-transition.scss
  assets/css/sensei-course-theme/quiz.scss
  includes/blocks/course-theme/class-quiz-actions.php
  includes/blocks/course-theme/class-quiz-back-to-lesson.php
  includes/blocks/course-theme/class-quiz-content.php
  includes/class-sensei-quiz.php
  includes/course-theme/class-sensei-course-theme-editor.php
  includes/course-theme/class-sensei-course-theme-quiz.php
  templates/single-quiz.php
  templates/single-quiz/pagination.php
  themes/sensei-course-theme/templates/quiz.html
Labels: Templates

#4667 Remove deprecated functionality
  includes/admin/class-sensei-learner-management.php
  includes/admin/class-sensei-setup-wizard.php
  includes/class-sensei-autoloader.php
  includes/class-sensei-course-results.php
  includes/class-sensei-course.php
  includes/class-sensei-data-cleaner.php
  includes/class-sensei-frontend.php
  includes/class-sensei-learner-profiles.php
  includes/class-sensei-lesson.php
  includes/class-sensei-templates.php
  includes/class-sensei-utils.php
  includes/class-sensei.php
  includes/sensei-functions.php
  includes/shortcodes/class-sensei-legacy-shortcodes.php
  includes/shortcodes/class-sensei-shortcode-loader.php
  includes/template-functions.php
Labels: Deprecation

#4677 Fix collapsible height with a loaded font
  assets/blocks/frontend.js
  webpack.config.js
Labels: [Type] Bug

#4678 Fix preview learning mode in a course with disabled learning mode
  includes/course-theme/class-sensei-course-theme-option.php
Labels: [Type] Bug

#4676 Fix quiz buttons styles
  assets/css/frontend.scss
Labels: [Type] Bug

#4681 Add "New" badge to Learning Mode
  assets/css/global.scss
  assets/js/admin/course-theme/course-theme-sidebar.js
  includes/class-sensei-settings.php
Labels: [Type] Enhancement

#4683 Merge `master` to `feature/course-theme`
  .github/workflows/php.yml
  assets/blocks/quiz/quiz-block/quiz-settings.js
  changelog.txt
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
  tests/README.md
Labels: [Type] Maintenance

#4634 Move Import and Export to the Tools page
  assets/setup-wizard/ready/index.js
  assets/setup-wizard/ready/index.test.js
  includes/admin/class-sensei-tools.php
  includes/admin/tools/class-sensei-tool-export.php
  includes/admin/tools/class-sensei-tool-import.php
  includes/admin/tools/views/html-export.php
  includes/admin/tools/views/html-import.php
  includes/class-sensei-autoloader.php
  tests/e2e/specs/activate-and-setup/setup-wizard.test.js
Labels: [Type] Enhancement

#4672 Update courses page navigation
  assets/css/admin-custom.css
  assets/js/admin/custom-navigation.js
  assets/js/settings.js
  includes/class-sensei-admin.php
  includes/class-sensei-course.php
  webpack.config.js
Labels: [Type] Enhancement

#4663 Add a students column to the courses list table
  assets/css/admin-custom.css
  includes/class-sensei-course.php
  includes/class-sensei-learner.php
Labels: [Type] Enhancement

#4646 Consolidate course module columns
  assets/css/admin-custom.css
  includes/class-sensei-course.php
  includes/class-sensei-lesson.php
  includes/class-sensei-modules.php
Labels: [Type] Enhancement

#4666 Add a "more" link to the course modules column
  assets/css/admin-custom.scss
  assets/js/admin/course-index.js
  includes/class-sensei-course.php
  includes/class-sensei-modules.php
  tests/unit-tests/test-class-modules.php
  webpack.config.js
Labels: [Type] Enhancement, Hooks

#4687 Lessons page submenu items
  includes/class-sensei-admin.php
  includes/class-sensei-lesson.php
Labels: [Type] Enhancement

#4692 Add custom navigation to Questions menu item
  assets/js/admin/custom-navigation.js
  includes/class-sensei-admin.php
  includes/class-sensei-lesson.php
  includes/class-sensei-question.php
Labels: [Type] Enhancement

#4699 Update settings URL when changing a tab
  assets/js/settings.js
Labels: [Type] Enhancement

#4693 Update modules navigation
  includes/class-sensei-admin.php
  includes/class-sensei-modules.php
Labels: [Type] Enhancement

#4684 Fix responsive styles and tweak prev/next links
  assets/course-theme/adminbar-layout.js
  assets/course-theme/focus-mode.js
  assets/css/sensei-course-theme/base.scss
  assets/css/sensei-course-theme/blockbase-ponyfill.scss
  assets/css/sensei-course-theme/course-navigation.scss
  assets/css/sensei-course-theme/focus-mode.scss
  assets/css/sensei-course-theme/header.scss
  assets/css/sensei-course-theme/layout.scss
  assets/css/sensei-course-theme/mobile.scss
  assets/css/sensei-course-theme/prev-next-lesson.scss
  assets/css/sensei-course-theme/quiz.scss
  includes/blocks/course-theme/class-course-theme.php
  includes/blocks/course-theme/class-focus-mode.php
  includes/blocks/course-theme/class-next-lesson.php
  includes/blocks/course-theme/class-prev-lesson.php
  includes/blocks/course-theme/class-prev-next-lesson.php
  includes/class-sensei-autoloader.php
  themes/sensei-course-theme/templates/lesson.html
Labels: [Type] Bug

#4706 Improve focus mode toggle button
  assets/course-theme/blocks/blocks.js
  assets/css/sensei-course-theme/focus-mode.scss
  assets/css/sensei-course-theme/layout.scss
  assets/icons/double-chevron-right.svg
Labels: [Type] Enhancement

#4712 Add course type to analysis links
  includes/class-sensei-analysis-course-list-table.php
  includes/class-sensei-analysis-lesson-list-table.php
  includes/class-sensei-analysis-overview-list-table.php
  includes/class-sensei-analysis-user-profile-list-table.php
  includes/class-sensei-analysis.php
Labels: [Type] Enhancement

#4721 Merge menu restructuring to master
  assets/css/admin-custom.scss
  assets/css/global.scss
  assets/js/admin/course-index.js
  assets/js/admin/custom-navigation.js
  assets/js/admin/event-logging.js
  assets/js/settings.js
  assets/setup-wizard/ready/index.js
  assets/setup-wizard/ready/index.test.js
  includes/admin/class-sensei-admin-notices.php
  includes/admin/class-sensei-extensions.php
  includes/admin/class-sensei-learner-management.php
  includes/admin/class-sensei-tools.php
  includes/admin/tools/class-sensei-tool-export.php
  includes/admin/tools/class-sensei-tool-import.php
  includes/admin/tools/views/html-export.php
  includes/admin/tools/views/html-import.php
  includes/admin/views/html-admin-page-tools-header.php
  includes/class-sensei-admin.php
  includes/class-sensei-analysis-course-list-table.php
  includes/class-sensei-analysis-lesson-list-table.php
  includes/class-sensei-analysis-overview-list-table.php
  includes/class-sensei-analysis-user-profile-list-table.php
  includes/class-sensei-analysis.php
  includes/class-sensei-autoloader.php
  includes/class-sensei-course.php
  includes/class-sensei-grading-main.php
  includes/class-sensei-grading.php
  includes/class-sensei-learner.php
  includes/class-sensei-lesson.php
  includes/class-sensei-messages.php
  includes/class-sensei-modules.php
  includes/class-sensei-posttypes.php
  includes/class-sensei-question.php
  includes/class-sensei-settings-api.php
  includes/class-sensei-settings.php
  includes/class-sensei.php
  includes/data-port/class-sensei-export.php
  includes/data-port/class-sensei-import.php
  tests/e2e/specs/activate-and-setup/setup-wizard.test.js
  tests/unit-tests/admin/test-class-sensei-extensions.php
  tests/unit-tests/test-class-grading.php
  tests/unit-tests/test-class-modules.php
  webpack.config.js
Labels: [Type] Maintenance

#4723 Update learning mode banner copy
  includes/course-theme/class-sensei-course-theme-option.php
Labels: [Type] Enhancement
