Repository Automattic/sensei, pull requests merged in 2022-12, with the labels that each got.

#6210 Fix sidebar position for learning mode
  assets/css/sensei-course-theme/ui-blocks.scss
Labels: Learning Mode

#6214 Fix mail list br tag escape in landing page
  includes/block-patterns/page/templates/landing-page-grid.php
  includes/block-patterns/page/templates/landing-page-list.php
Labels: Theme

#6171 Fix CSS indentation and spacing
  assets/css/_grid.scss
  assets/css/_mixins.scss
  assets/css/admin-custom.scss
  assets/css/course-editor.scss
  assets/css/enrolment-debug.scss
  assets/css/font-recoleta.scss
  assets/css/fontawesome.scss
  assets/css/frontend.scss
  assets/css/global.scss
  assets/css/home.scss
  assets/css/lesson-editor.scss
  assets/css/meta-box-quiz-editor.scss
  assets/css/modules-admin.css
  assets/css/modules-frontend.scss
  assets/css/pages-frontend.scss
  assets/css/ranges.css
  assets/css/sensei-course-theme/4-0-2/layout.scss
  assets/css/sensei-course-theme/4-0-2/mobile.scss
  assets/css/sensei-course-theme/blockbase-ponyfill.scss
  assets/css/sensei-course-theme/blocks/contact-teacher.scss
  assets/css/sensei-course-theme/blocks/course-navigation.scss
  assets/css/sensei-course-theme/blocks/course-progress-bar.scss
  assets/css/sensei-course-theme/blocks/lesson-actions.scss
  assets/css/sensei-course-theme/blocks/lesson-video.scss
  assets/css/sensei-course-theme/blocks/prev-next-lesson.scss
  assets/css/sensei-course-theme/buttons.scss
  assets/css/sensei-course-theme/content.scss
  assets/css/sensei-course-theme/focus-mode.scss
  assets/css/sensei-course-theme/global-styles.scss
  assets/css/sensei-course-theme/layout.scss
  assets/css/sensei-course-theme/lesson-complete-transition.scss
  assets/css/sensei-course-theme/mobile.scss
  assets/css/sensei-course-theme/modal.scss
  assets/css/sensei-course-theme/notices.scss
  assets/css/sensei-course-theme/quiz.scss
  assets/css/sensei-course-theme/sidebar-mobile-menu.scss
  assets/css/sensei-course-theme/theme-fixes.scss
  assets/css/sensei-course-theme/theme.scss
  assets/css/sensei-course-theme/ui-blocks.scss
  assets/css/sensei-course-theme/video-container.scss
  assets/css/sensei-modal.scss
  assets/css/sensei-theme-blocks.scss
  assets/css/settings.scss
  assets/css/tools.scss
Labels: [Type] Maintenance

#6172 Fix the docs build command not working
  includes/class-sensei-notices.php
Labels: [Type] Maintenance

#6229 Ensure passing an integer module id
  includes/class-sensei-modules.php
Labels: [Type] Bug

#6220 Fix the docs build command not working again
  includes/class-sensei-teacher.php
Labels: [Type] Maintenance

#6253 Add meta checkbox for course open access
  assets/js/admin/course-general-sidebar.js
  includes/class-sensei-course.php
Labels: Guest Users

#6231 Install Course theme in setup wizard
  assets/setup-wizard/features/index.js
  includes/admin/class-sensei-extensions.php
  includes/rest-api/class-sensei-rest-api-internal.php
  includes/rest-api/class-sensei-rest-api-theme-controller.php
Labels: Onboarding Course Theme Step

#6259 Create guest user for open access courses and login
  includes/blocks/class-sensei-block-take-course.php
  includes/class-sensei-frontend.php
  includes/class-sensei-guest-user.php
Labels: Guest Users

#6110 Add TypeScript support
  .github/workflows/js.yml
  .gitignore
  assets/course-theme/adminbar-layout.ts
  assets/course-theme/focus-mode.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: [Pri] Low

#6264 Show lesson and quiz as if enrolled for open access lessons
  includes/blocks/class-sensei-view-quiz-block.php
  includes/blocks/course-theme/class-lesson-actions.php
  includes/class-sensei-guest-user.php
  includes/class-sensei-lesson.php
  includes/class-sensei-quiz.php
  includes/enrolment/class-sensei-course-enrolment.php
  templates/single-quiz/question-type-boolean.php
  templates/single-quiz/question-type-gap-fill.php
  templates/single-quiz/question-type-multiple-choice.php
  templates/single-quiz/question-type-single-line.php
Labels: Guest Users

#6271 Remove legacy e2e tests
  package-lock.json
  package.json
Labels: e2e

#6262 Add `sensei_usage_tracking_data` filter hook
  includes/class-sensei-usage-tracking-data.php
  tests/unit-tests/test-class-sensei-usage-tracking-data.php
Labels: Hooks

#6266 Add E2E tests for course creation
  tests/e2e-playwright/config/global-setup.ts
  tests/e2e-playwright/helpers/api.ts
  tests/e2e-playwright/pages/admin/courses/courses.ts
  tests/e2e-playwright/pages/admin/dashboard/dashboard.ts
  tests/e2e-playwright/pages/admin/post-type/index.ts
  tests/e2e-playwright/specs/admin/teacher/course-creation.spec.ts
Labels: [Type] Maintenance, e2e

#6261 Run tests when changes are introduced on the trunk
  .github/workflows/build-docs.yml
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  .github/workflows/js.yml
  .github/workflows/php.yml
  .github/workflows/trunk.yml
  README.md
Labels: [Type] Maintenance, e2e

#6228 Log sent emails
  includes/class-sensei-emails.php
Labels: Logging

#6279 Create user and enrol on lesson and quiz actions
  includes/blocks/course-theme/class-quiz-actions.php
  includes/class-sensei-guest-user.php
  tests/unit-tests/test-class-sensei-guest-user.php
Labels: Guest Users

#6280 Confine guest user to open course only and persist lesson and quiz progress states
  includes/class-sensei-guest-user.php
Labels: Guest Users

#6289 Add a module with a lesson while creating a course
  tests/e2e-playwright/pages/admin/courses/index.ts
  tests/e2e-playwright/pages/admin/dashboard/index.ts
  tests/e2e-playwright/specs/admin/teacher/course-creation.spec.ts
Labels: [Type] Maintenance, e2e

#6295 Add wordpress js linter style
  tests/e2e-playwright/.eslintrc.js
  tests/e2e-playwright/config/global-setup.ts
  tests/e2e-playwright/helpers/api.ts
  tests/e2e-playwright/helpers/context.ts
  tests/e2e-playwright/helpers/database.ts
  tests/e2e-playwright/helpers/lesson-templates.ts
  tests/e2e-playwright/pages/admin/courses/courses.ts
  tests/e2e-playwright/pages/admin/courses/index.ts
  tests/e2e-playwright/pages/admin/dashboard/index.ts
  tests/e2e-playwright/pages/admin/plugins/plugins.ts
  tests/e2e-playwright/pages/admin/post-type/blocks/query-loop.ts
  tests/e2e-playwright/pages/admin/post-type/index.ts
  tests/e2e-playwright/pages/admin/students/students.js
  tests/e2e-playwright/pages/admin/students/students.ts
  tests/e2e-playwright/pages/frontend/lesson.ts
  tests/e2e-playwright/specs/admin/blocks/course-list-block.spec.ts
  tests/e2e-playwright/specs/admin/students/setup-wizard.spec.ts
  tests/e2e-playwright/specs/admin/students/students-management.spec.ts
  tests/e2e-playwright/specs/admin/teacher/course-creation.spec.ts
  tests/e2e-playwright/specs/frontend/course-fixtures.ts
  tests/e2e-playwright/specs/frontend/student/course-completion.spec.ts
Labels: e2e

#6297 Refactor the data creation + small improvements
  tests/e2e-playwright/.eslintrc.js
  tests/e2e-playwright/config/global-setup.ts
  tests/e2e-playwright/factories/courses.ts
  tests/e2e-playwright/factories/lesson.ts
  tests/e2e-playwright/factories/users.ts
  tests/e2e-playwright/helpers/api.ts
  tests/e2e-playwright/helpers/api/courses.ts
  tests/e2e-playwright/helpers/api/index.ts
  tests/e2e-playwright/helpers/api/users.ts
  tests/e2e-playwright/helpers/context.ts
  tests/e2e-playwright/specs/admin/blocks/course-list-block.spec.ts
  tests/e2e-playwright/specs/admin/students/setup-wizard.spec.ts
  tests/e2e-playwright/specs/admin/students/students-management.spec.ts
  tests/e2e-playwright/specs/admin/teacher/course-creation.spec.ts
  tests/e2e-playwright/specs/frontend/course-fixtures.ts
  tests/e2e-playwright/specs/frontend/student/course-completion.spec.ts
Labels: e2e

#6290 Change preview users to be per course
  includes/class-sensei-preview-user.php
  includes/class-sensei-utils.php
  tests/unit-tests/test-class-sensei-preview-user.php
Labels: Guest Users

#6305 Skip welcome modal on the e2e test suite
  tests/e2e-playwright/config/global-setup.ts
  tests/e2e-playwright/factories/users.ts
  tests/e2e-playwright/helpers/api/users.ts
  tests/e2e-playwright/helpers/context.ts
  tests/e2e-playwright/helpers/preferences.ts
  tests/e2e-playwright/pages/admin/post-type/index.ts
  tests/e2e-playwright/specs/admin/blocks/course-list-block.spec.ts
  tests/e2e-playwright/specs/admin/teacher/course-creation.spec.ts
Labels: [Type] Maintenance, e2e

#6309 Add support to the "Preview in new tab" editor feature
  .github/workflows/e2e.yml
  tests/e2e-playwright/pages/admin/post-type/index.ts
  tests/e2e-playwright/specs/admin/blocks/course-list-block.spec.ts
  tests/e2e-playwright/specs/admin/teacher/course-creation.spec.ts
Labels: e2e

#6274 Add notice asking user for reviews/feedback
  assets/css/admin-notices.scss
  assets/home/link.js
  assets/home/notices.js
  assets/home/notices.scss
  assets/home/utils.js
  assets/js/admin/sensei-notice-dismiss.js
  assets/shared/styles/_variables.scss
  includes/admin/class-sensei-admin-notices.php
  includes/admin/home/notices/class-sensei-home-notices-provider.php
  includes/admin/home/notices/class-sensei-home-notices.php
  includes/class-sensei-data-cleaner.php
  includes/class-sensei-updates.php
  tests/unit-tests/admin/home/notices/test-class-sensei-home-notices-provider.php
  tests/unit-tests/admin/home/notices/test-class-sensei-home-notices.php
  tests/unit-tests/admin/test-class-sensei-admin-notices.php
Labels: [Type] Enhancement

#6310 Remove the "source" property from events data
  includes/class-sensei-usage-tracking-data.php
  includes/class-sensei-usage-tracking.php
Labels: Logging, Deprecation

#6257 Fix private message emails not being sent
  includes/class-sensei-emails.php
  includes/class-sensei-messages.php
  includes/class-sensei-utils.php
  includes/emails/class-sensei-email-teacher-new-message.php
  tests/framework/trait-sensei-course-enrolment-manual-test-helpers.php
  tests/unit-tests/test-class-sensei-messages.php
  tests/unit-tests/test-class-sensei-usage-tracking-data.php
  tests/unit-tests/test-class-utils.php
Labels: [Type] Bug

#6314 Upgrade playwright version
  package-lock.json
  package.json
Labels: e2e

#6315 Run e2e tests using the course theme
  .wp-env.json
  tests/e2e-playwright/helpers/database.ts
Labels: [Type] Maintenance, e2e

#6296 Add filters for course actions buttons
  assets/blocks/course-list-block/course-list.scss
  includes/block-patterns/course-list/class-sensei-course-list-block-patterns.php
Labels: Hooks

#6335 Fix editor wizard header style
  assets/admin/editor-wizard/style.scss
Labels: [Type] Bug
