Repository Automattic/sensei, pull requests merged in 2022-05, with the labels that each got.

#5082 Fix lesson compatibility issue with Divi
  includes/course-theme/class-sensei-course-theme-compat.php
Labels: [Type] Bug

#5090 Lessons: Report return empty array when no lessons in course
  includes/reports/overview/data-provider/class-sensei-reports-overview-data-provider-lessons.php
  tests/unit-tests/reports/overview/data-provider/test-class-sensei-reports-overview-data-provider-lessons.php
Labels: Reports

#5078 Remove infinite loop on test execution
  assets/shared/structure/structure-store.test.js
Labels: Student Management

#5076 Add a filter for students on a course by Date Started
  assets/css/settings.scss
  includes/class-sensei-analysis-course-list-table.php
  includes/class-sensei-autoloader.php
  includes/reports/helper/class-sensei-reports-helper-date-range-trait.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-abstract.php
  tests/unit-tests/test-class-sensei-analysis-course-list-table.php
Labels: [Type] Enhancement, Reports

#5095 Hide the export button when there is no data
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-abstract.php
  tests/unit-tests/reports/overview/list-table/test-class-sensei-reports-overview-list-table-abstract.php
Labels: Reports

#5097 Display average total for Days to Completion in Courses report header
  includes/class-sensei-analysis-overview-list-table.php
  includes/class-sensei-course.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-courses.php
  tests/unit-tests/reports/overview/list-table/test-class-sensei-reports-overview-list-table-courses.php
  tests/unit-tests/test-class-course.php
Labels: [Type] Enhancement, Reports

#5087 Add lesson notices filters
  includes/class-sensei-lesson.php
  includes/course-theme/class-sensei-course-theme-lesson.php
  includes/sensei-functions.php
Labels: [Type] Enhancement, Hooks

#5106 Fix nightly tests
  tests/unit-tests/reports/overview/data-provider/test-class-sensei-reports-overview-data-provider-students.php
Labels: [Type] Maintenance

#5105 Only show enrolled students in reports
  includes/reports/overview/data-provider/class-sensei-reports-overview-data-provider-students.php
  tests/unit-tests/reports/overview/data-provider/test-class-sensei-reports-overview-data-provider-students.php
Labels: [Type] Bug, Reports

#5111 Fix student name appearing twice on student report title
  includes/class-sensei-analysis.php
  tests/unit-tests/test-class-sensei-analysis.php
Labels: Reports

#5112 Merge post code freeze to trunk
  .github/workflows/php.yml
  composer.json
  composer.lock
  includes/blocks/course-theme/class-course-content.php
  includes/class-sensei-dependency-checker.php
  includes/class-sensei-lesson.php
  includes/course-theme/class-sensei-course-theme-compat.php
  includes/course-theme/class-sensei-course-theme-lesson.php
  includes/sensei-functions.php
  sensei-lms.php
Labels: [Type] Maintenance

#5101 Fetch last activity date with the main query
  includes/reports/overview/data-provider/class-sensei-reports-overview-data-provider-courses.php
  includes/reports/overview/data-provider/class-sensei-reports-overview-data-provider-lessons.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-courses.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-lessons.php
Labels: [Type] Enhancement, Reports

#5117 Set post type in the module link for selecting proper menu item
  assets/js/admin/event-logging.js
  includes/class-sensei-admin.php
  includes/class-sensei-modules.php
  includes/class-sensei-posttypes.php
Labels: [Type] Bug, Modules

#5085 Remove WP 5.5 compatibility methods
  includes/blocks/class-sensei-blocks.php
  includes/blocks/compat.php
  includes/class-sensei-bootstrap.php
Labels: [Type] Maintenance

#5091 Reports: Apply data filters to column total values
  includes/class-sensei-course.php
  includes/class-sensei-grading.php
  includes/reports/overview/data-provider/class-sensei-reports-overview-data-provider-courses.php
  includes/reports/overview/data-provider/class-sensei-reports-overview-data-provider-lessons.php
  includes/reports/overview/data-provider/class-sensei-reports-overview-data-provider-students.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-abstract.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-courses.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-factory.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-lessons.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-students.php
  includes/reports/overview/services/class-sensei-reports-overview-service-courses.php
  includes/reports/overview/services/class-sensei-reports-overview-service-students.php
  tests/unit-tests/reports/overview/list-table/test-class-sensei-reports-overview-list-table-courses.php
  tests/unit-tests/reports/overview/list-table/test-class-sensei-reports-overview-list-table-students.php
  tests/unit-tests/reports/overview/services/test-class-sensei-reports-overview-service-courses.php
  tests/unit-tests/test-class-course.php
Labels: Reports, Deprecation

#5113 Fix reports date filters not accounting for the user timezone
  assets/js/admin/reports.js
  includes/reports/helper/class-sensei-reports-helper-date-range-trait.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-abstract.php
  tests/unit-tests/reports/helper/test-class-sensei-reports-helper-date-range-trait.php
  tests/unit-tests/reports/overview/list-table/test-class-sensei-reports-overview-list-table-abstract.php
Labels: [Type] Bug, Reports

#5122 Fix courses and lessons last activity date not showing in reports
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-courses.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-lessons.php
Labels: Reports

#5084 Merge `feature/reports-v3` to `trunk`
  assets/css/settings.scss
  assets/js/admin/reports.js
  includes/class-sensei-analysis-course-list-table.php
  includes/class-sensei-analysis-overview-list-table.php
  includes/class-sensei-analysis.php
  includes/class-sensei-autoloader.php
  includes/class-sensei-course.php
  includes/class-sensei-grading.php
  includes/reports/helper/class-sensei-reports-helper-date-range-trait.php
  includes/reports/overview/data-provider/class-sensei-reports-overview-data-provider-courses.php
  includes/reports/overview/data-provider/class-sensei-reports-overview-data-provider-lessons.php
  includes/reports/overview/data-provider/class-sensei-reports-overview-data-provider-students.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-abstract.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-courses.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-factory.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-lessons.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-students.php
  includes/reports/overview/services/class-sensei-reports-overview-service-courses.php
  includes/reports/overview/services/class-sensei-reports-overview-service-students.php
  readme.txt
  tests/unit-tests/reports/helper/test-class-sensei-reports-helper-date-range-trait.php
  tests/unit-tests/reports/overview/data-provider/test-class-sensei-reports-overview-data-provider-lessons.php
  tests/unit-tests/reports/overview/data-provider/test-class-sensei-reports-overview-data-provider-students.php
  tests/unit-tests/reports/overview/list-table/test-class-sensei-reports-overview-list-table-abstract.php
  tests/unit-tests/reports/overview/list-table/test-class-sensei-reports-overview-list-table-courses.php
  tests/unit-tests/reports/overview/list-table/test-class-sensei-reports-overview-list-table-students.php
  tests/unit-tests/reports/overview/services/test-class-sensei-reports-overview-service-courses.php
  tests/unit-tests/test-class-course.php
  tests/unit-tests/test-class-sensei-analysis-course-list-table.php
  tests/unit-tests/test-class-sensei-analysis.php
Labels: Reports, [Type] Maintenance

#5120 Fix exporting "students taking course" not affected by filters
  includes/class-sensei-analysis-course-list-table.php
  tests/unit-tests/test-class-sensei-analysis-course-list-table.php
Labels: [Type] Bug

#5121 Fix hide export button when no results on "Students taking course" screen
  includes/class-sensei-analysis-course-list-table.php
  tests/unit-tests/test-class-sensei-analysis-course-list-table.php
Labels: [Type] Bug

#5104 Refactor students page fetching data through Gutenberg and avoiding subqueries
  assets/admin/lib/http-client/index.js
  assets/admin/lib/http-client/index.test.js
  assets/admin/students/student-action-menu/index.test.js
  assets/admin/students/student-bulk-action-button/index.test.js
  assets/admin/students/student-modal/course-list-fetch.test.js
  assets/admin/students/student-modal/course-list.js
  assets/admin/students/student-modal/course-list.test.js
  assets/admin/students/student-modal/index.js
  assets/admin/students/student-modal/index.test.js
  assets/react-hooks/use-select-with-debounce.js
  assets/react-hooks/use-select-with-debounce.test.js
  includes/admin/class-sensei-learner-management.php
  includes/admin/class-sensei-learners-admin-bulk-actions-view.php
  includes/class-sensei-db-query-learners.php
Labels: [Type] Bug

#5149 Add editor wizard modal for courses and lessons
  assets/admin/editor-wizard/editor-wizard-modal.js
  assets/admin/editor-wizard/index.js
  assets/admin/editor-wizard/style.scss
  assets/blocks/single-lesson.js
  assets/images/onboarding-learning-mode-check.jpg
  assets/images/onboarding-learning-mode.jpg
  assets/js/admin/blocks-toggling-control.js
  assets/js/admin/course-theme/course-theme-onboarding.js
  assets/js/admin/course-theme/guide.js
  assets/js/admin/course-theme/index.js
  includes/admin/class-sensei-editor-wizard.php
  includes/blocks/class-sensei-lesson-blocks.php
  includes/class-sensei-autoloader.php
  includes/class-sensei-course-structure.php
  includes/class-sensei.php
  webpack.config.js
Labels: [Type] Enhancement

#5153 Fix deprecated warnings on the students report screen
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-students.php
Labels: [Type] Bug

#5147 Fix readme.txt typo
  readme.txt
Labels: [Type] Maintenance

#5148 Fix the version number and define a constant for it
  includes/class-sensei.php
  sensei-lms.php
  tests/unit-tests/test-class-sensei-updates.php
  tests/unit-tests/test-class-sensei.php
Labels: [Type] Maintenance

#5119 Configure NPM to throws an error when the env is using a wrong npm version
  .github/workflows/build-docs.yml
  .github/workflows/build.yml
  .github/workflows/e2e-playwright.yml
  .github/workflows/js.yml
  .npmrc
Labels: [Status] In Progress, [Type] Maintenance, Development Experience

#5114 Fix teacher name getting appended and duplicated in module title in course edit
  assets/blocks/course-outline/data.js
  assets/blocks/course-outline/module-block/block.json
  assets/blocks/course-outline/module-block/module-edit.js
  assets/blocks/course-outline/module-block/module-edit.test.js
  assets/blocks/course-outline/module-block/module.scss
  includes/class-sensei-course-structure.php
  includes/rest-api/class-sensei-rest-api-course-structure-controller.php
  tests/unit-tests/test-class-sensei-course-structure.php
Labels: [Type] Bug, Modules, Blocks

#5155 Update the link and text for CTA on the extensions page
  assets/extensions/featured-product-sensei-pro.js
  assets/extensions/featured-product.js
Labels: [Type] Maintenance

#5151 Fix lesson not getting assigned to module if course teacher has teacher role
  assets/blocks/course-outline/data.js
  assets/blocks/course-outline/module-block/block.json
  assets/shared/structure/structure-store.js
  assets/shared/structure/structure-store.test.js
  includes/class-sensei-course-structure.php
  includes/class-sensei-teacher.php
Labels: [Type] Bug, Modules, Blocks

#5144 Add `learn/` prefixed rewrite rule for module views
  includes/course-theme/class-sensei-course-theme.php
Labels: [Type] Bug, Modules, Course Theme

#5164 Fix add student to course not visible if sensei pro/content drip is enabled
  assets/css/settings.scss
Labels: [Type] Bug, Student Management

#5156 Fix lesson blocks notice when Learning Mode is enabled
  assets/js/admin/blocks-toggling-control.js
Labels: [Type] Bug

#5157 Add patterns list
  assets/admin/editor-wizard/editor-wizard-modal.js
  assets/admin/editor-wizard/patterns-list.js
  assets/admin/editor-wizard/patterns-list.scss
  assets/admin/editor-wizard/style.scss
Labels: [Type] Enhancement

#5160 Update/e2e tests move wizard setup tests to playwright
  docker-compose.yaml
  tests/e2e-playwright/pages/admin/plugins/plugins.js
  tests/e2e-playwright/specs/admin/students/setup-wizard.spec.js
  tests/e2e/.eslintrc.js
  tests/e2e/README.md
  tests/e2e/bin/wp-cli.sh
  tests/e2e/config/jest.config.js
  tests/e2e/config/jest.setup.js
  tests/e2e/docker/wordpress/Dockerfile
  tests/e2e/specs/activate-and-setup/setup-wizard.test.js
  tests/e2e/utils/flows.js
  tests/e2e/utils/helpers.js
Labels: e2e

#5169 Add Paid Course Upsell
  assets/admin/editor-wizard/editor-wizard-modal.js
  assets/admin/editor-wizard/steps/course-details-step.js
  assets/admin/editor-wizard/steps/course-patterns-step.js
  assets/admin/editor-wizard/steps/course-upgrade-step.js
  assets/admin/editor-wizard/steps/lesson-details-step.js
  assets/admin/editor-wizard/steps/lesson-patterns-step.js
  assets/admin/editor-wizard/steps/upgrade-step.js
  assets/admin/editor-wizard/style.scss
  assets/admin/editor-wizard/wizard.js
  assets/admin/editor-wizard/wizard.test.js
  assets/extensions/featured-product-sensei-pro.js
  assets/extensions/store.js
  assets/images/sensei-pro-upsell.png
Labels: [Type] Enhancement

#5181 Add support to "import" images directly in js
  assets/admin/editor-wizard/steps/course-details-step.js
  assets/admin/editor-wizard/steps/course-upgrade-step.js
  assets/admin/editor-wizard/steps/lesson-details-step.js
  webpack.config.js
Labels: [Type] Enhancement

#5184 Add extensions preload on editor wizard
  assets/admin/editor-wizard/editor-wizard-modal.js
  includes/admin/class-sensei-editor-wizard.php
Labels: [Type] Bug

#5186 Add some Paid Course Upsell tests
  assets/admin/editor-wizard/editor-wizard-modal.js
  assets/admin/editor-wizard/steps/course-upgrade-step.test.js
  assets/admin/editor-wizard/use-editor-wizard-steps.js
  assets/admin/editor-wizard/use-editor-wizard-steps.test.js
  jest.config.js
  tests/__mocks__/image.js
Labels: [Type] Maintenance

#5173 Add some samples as Sensei patterns
  includes/admin/class-sensei-editor-wizard.php
Labels: [Type] Enhancement

#5177 Do not auto-add Quiz blocks on the lessons anymore
  includes/rest-api/class-sensei-rest-api-lessons-controller.php
Labels: [Type] Enhancement

#5193 Fix dependency import
  assets/admin/editor-wizard/use-editor-wizard-steps.js
Labels: [Type] Bug

#5192 Disable the lesson archive
  includes/class-sensei-posttypes.php
Labels: [Type] Enhancement, Lessons

#5194 Add Lesson Details Step
  assets/admin/editor-wizard/steps/course-details-step.js
  assets/admin/editor-wizard/steps/course-upgrade-step.js
  assets/admin/editor-wizard/steps/course-upgrade-step.test.js
  assets/admin/editor-wizard/steps/lesson-details-step.js
  assets/admin/editor-wizard/steps/lesson-details-step.test.js
  assets/images/details-step.png
Labels: [Type] Enhancement

#5196 Create 3 default lessons on the Course Outline Block
  assets/blocks/course-outline/outline-block/outline-edit.js
  includes/blocks/class-sensei-course-blocks.php
Labels: [Type] Enhancement

#5198 Fix module order not preserved after teacher update
  includes/class-sensei-course-structure.php
  includes/class-sensei-teacher.php
  tests/unit-tests/test-class-teacher.php
Labels: [Type] Bug, Modules

#5201 Fix the "import" docs link
  assets/data-port/import/upload/upload-page.js
  sample-data/lessons.csv
Labels: [Type] Bug

#5178 Fix localization warnings
  assets/admin/students/student-action-menu/index.test.js
  assets/admin/students/student-modal/index.js
  assets/admin/students/student-modal/index.test.js
  includes/admin/class-sensei-learners-admin-bulk-actions-view.php
  includes/admin/class-sensei-learners-main.php
  includes/class-sensei-course.php
  includes/class-sensei-learner-profiles.php
  includes/class-sensei-lesson.php
  includes/class-sensei-messages.php
  includes/class-sensei-posttypes.php
  includes/course-theme/class-sensei-course-theme-lesson.php
Labels: i18n, [Type] Maintenance

#5195 Redirect the quiz if the lesson is password protected
  includes/class-sensei-quiz.php
  tests/unit-tests/test-class-quiz.php
Labels: [Type] Enhancement, Quizzes

#5191 Add Codecov to GitHub Actions
  .codecov.yml
  .github/workflows/php.yml
  .gitignore
  package.json
Labels: [Type] Maintenance

#5179 Apply pattern to the post when selected
  assets/admin/editor-wizard/editor-wizard-modal.js
  assets/admin/editor-wizard/patterns-list.js
  assets/admin/editor-wizard/steps/course-patterns-step.js
  assets/admin/editor-wizard/steps/lesson-patterns-step.js
  assets/admin/editor-wizard/steps/patterns-step.js
  assets/admin/editor-wizard/steps/patterns-step.test.js
  assets/admin/editor-wizard/style.scss
  assets/admin/editor-wizard/wizard.js
  includes/admin/class-sensei-editor-wizard.php
Labels: [Type] Enhancement

#5202 Add patterns filter by post type
  assets/admin/editor-wizard/patterns-list.js
  assets/admin/editor-wizard/style.scss
  includes/admin/class-sensei-editor-wizard.php
Labels: [Type] Enhancement

#5205 Add editor wizard responsive style and tweak some styles
  assets/admin/editor-wizard/patterns-list.scss
  assets/admin/editor-wizard/steps/course-details-step.js
  assets/admin/editor-wizard/steps/course-upgrade-step.js
  assets/admin/editor-wizard/steps/lesson-details-step.js
  assets/admin/editor-wizard/steps/patterns-step.js
  assets/admin/editor-wizard/style.scss
Labels: [Type] Enhancement
