Repository Automattic/sensei, pull requests merged in 2022-03, with the labels that each got.

#4853 Rename Analysis to Reports
  assets/css/global.scss
  assets/js/admin/event-logging.js
  includes/admin/class-sensei-admin-notices.php
  includes/class-sensei-admin.php
  includes/class-sensei-analysis-course-list-table.php
  includes/class-sensei-analysis-lesson-list-table.php
  includes/class-sensei-analysis-overview-list-table.php
  includes/class-sensei-analysis-user-profile-list-table.php
  includes/class-sensei-analysis.php
  includes/class-sensei-lesson.php
Labels: [Type] Enhancement, Deprecation

#4860 Fix teachers can see all courses on some screens
  includes/admin/class-sensei-admin-notices.php
  includes/class-sensei-teacher.php
Labels: [Type] Bug

#4884 Add workflow to report commit status with link to download the plugin build
  .github/workflows/report-build.yml
Labels: [Type] Maintenance

#4886 Add Github Actions workflow to build plugin on each PR
  .github/workflows/build.yml
Labels: [Type] Maintenance

#4888 Fix course completed date does not update when having one lesson
  includes/class-sensei-utils.php
Labels: [Type] Bug

#4895 Add Last activity for Lessons
  includes/class-sensei-analysis-overview-list-table.php
Labels: [Type] Enhancement

#4883 Added days to completion column to lesson overview
  includes/class-sensei-analysis-overview-list-table.php
Labels: [Type] Enhancement

#4868 Update navigation on Reports page
  assets/css/admin-custom.scss
  includes/class-sensei-admin.php
  includes/class-sensei-analysis-overview-list-table.php
  includes/class-sensei-analysis.php
Labels: [Type] Enhancement, Analysis, Hooks, Deprecation

#4878 Add new lesson report default view and course filter
  assets/css/settings.scss
  assets/js/admin/reports.js
  includes/class-sensei-analysis-overview-list-table.php
  includes/class-sensei-analysis.php
  includes/class-sensei-list-table.php
  includes/class-sensei-utils.php
  tests/unit-tests/test-class-sensei-analysis-overview-list-table.php
  tests/unit-tests/test-class-utils.php
  webpack.config.js
Labels: [Type] Enhancement

#4901 Fix PHP notices when exporting the courses or lessons reports
  includes/class-sensei-analysis-course-list-table.php
  includes/class-sensei-analysis-lesson-list-table.php
  includes/class-sensei-analysis-overview-list-table.php
Labels: [Type] Bug

#4907 Add .nvmrc file with the current Node LTS version
  .nvmrc
Labels: [Type] Maintenance

#4906 Add Days to Completion column for courses
  includes/class-sensei-analysis-overview-list-table.php
  tests/unit-tests/test-class-sensei-analysis-overview-list-table.php
Labels: [Type] Enhancement

#4914 Fix phpunit config and add tests run with coverage
  .gitignore
  package.json
  phpunit.xml
Labels: [Type] Maintenance

#4915 Improve students report screen performance
  includes/class-sensei-analysis-overview-list-table.php
Labels: Performance

#4910 Add days to completion total for courses
  includes/class-sensei-analysis-overview-list-table.php
  includes/class-sensei-course.php
  tests/unit-tests/test-class-course.php
Labels: [Type] Enhancement

#4912 Add the video embed from legacy meta box to learning mode
  includes/class-sensei-lesson.php
  includes/course-theme/class-sensei-course-theme.php
Labels: [Type] Enhancement

#4924 Allow clearing the reports last activity date filter
  includes/class-sensei-analysis-overview-list-table.php
  tests/unit-tests/test-class-sensei-analysis-overview-list-table.php
Labels: [Type] Enhancement

#4934 Merge `feature/reports` branch to `master`
  assets/css/admin-custom.scss
  assets/css/global.scss
  assets/css/settings.scss
  assets/js/admin/event-logging.js
  assets/js/admin/reports.js
  includes/admin/class-sensei-admin-notices.php
  includes/class-sensei-admin.php
  includes/class-sensei-analysis-course-list-table.php
  includes/class-sensei-analysis-lesson-list-table.php
  includes/class-sensei-analysis-overview-list-table.php
  includes/class-sensei-analysis-user-profile-list-table.php
  includes/class-sensei-analysis.php
  includes/class-sensei-course.php
  includes/class-sensei-grading.php
  includes/class-sensei-lesson.php
  includes/class-sensei-list-table.php
  includes/class-sensei-teacher.php
  includes/class-sensei-utils.php
  tests/framework/factories/class-sensei-factory.php
  tests/unit-tests/test-class-course.php
  tests/unit-tests/test-class-grading.php
  tests/unit-tests/test-class-sensei-analysis-overview-list-table.php
  tests/unit-tests/test-class-utils.php
  webpack.config.js
Labels: [Type] Maintenance

#4882 Add a database seed WP-CLI command
  includes/class-sensei-cli.php
  includes/class-sensei.php
  includes/cli/class-sensei-db-seed-command.php
Labels: [Type] Maintenance

#4932 Improve the students export performance
  includes/class-sensei-analysis-overview-list-table.php
Labels: Performance

#4933 Add unit tests for better coverage
  tests/unit-tests/test-class-sensei-customizer.php
  tests/unit-tests/test-class-sensei-db-query-learners.php
Labels: [Type] Maintenance

#4917 Report courses add Average Progress table
  includes/class-sensei-analysis-overview-list-table.php
  tests/unit-tests/test-class-sensei-analysis-overview-list-table.php
Labels: [Type] Enhancement

#4937 Fix empty jQuery datepicker UI box showing in the footer
  assets/css/images/ui-bg_flat_0_aaaaaa_40x100.png
  assets/css/images/ui-bg_flat_75_ffffff_40x100.png
  assets/css/images/ui-bg_glass_55_fbf9ee_1x400.png
  assets/css/images/ui-bg_glass_65_ffffff_1x400.png
  assets/css/images/ui-bg_glass_75_dadada_1x400.png
  assets/css/images/ui-bg_glass_75_e6e6e6_1x400.png
  assets/css/images/ui-bg_glass_95_fef1ec_1x400.png
  assets/css/images/ui-bg_highlight-soft_75_cccccc_1x100.png
  assets/css/images/ui-icons_222222_256x240.png
  assets/css/images/ui-icons_2e83ff_256x240.png
  assets/css/images/ui-icons_444444_256x240.png
  assets/css/images/ui-icons_454545_256x240.png
  assets/css/images/ui-icons_555555_256x240.png
  assets/css/images/ui-icons_777620_256x240.png
  assets/css/images/ui-icons_777777_256x240.png
  assets/css/images/ui-icons_888888_256x240.png
  assets/css/images/ui-icons_cc0000_256x240.png
  assets/css/images/ui-icons_cd0a0a_256x240.png
  assets/css/images/ui-icons_ffffff_256x240.png
  assets/css/jquery-ui.css
Labels: [Type] Bug

#4960 Fix sorting for students reports table
  includes/class-sensei-analysis-overview-list-table.php
Labels: Reports

#4947 Refactor the students overview report code
  includes/class-sensei-analysis.php
  includes/reports/overview/data-provider/class-sensei-reports-overview-data-provider-students.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-abstract.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-factory.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-students.php
  tests/unit-tests/reports/overview/data-provider/test-class-sensei-reports-overview-data-provider-students.php
  tests/unit-tests/reports/overview/list-table/test-class-sensei-reports-overview-list-table-students.php
Labels: Reports, [Type] Maintenance

#4964 Refactor Lessons related codes from Reports overview
  includes/reports/overview/data-provider/class-sensei-reports-overview-data-provider-lessons.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-abstract.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-factory.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-lessons.php
  tests/unit-tests/reports/overview/data-provider/test-class-sensei-reports-overview-data-provider-lessons.php
  tests/unit-tests/reports/overview/list-table/test-class-sensei-reports-overview-list-table-lessons.php
Labels: Reports

#4965 Remove sortable from columns that can't be sorted
  includes/class-sensei-analysis-overview-list-table.php
Labels: Reports

#4969 Update the reports documentation link
  includes/class-sensei-analysis.php
Labels: [Type] Enhancement

#4972 Fix reports->students not taking pagination and sorting in cosideration
  includes/reports/overview/data-provider/class-sensei-reports-overview-data-provider-students.php
Labels: [Type] Bug
