Repository Automattic/sensei, pull requests merged in 2022-07, with the labels that each got.

#5315 Avoid using GLOB_BRACE so Sensei can run even successfully in non-GNU operating systems
  includes/admin/class-sensei-status.php
Labels: [Type] Bug, [Pri] Low

#5322 Fix quiz saving issue
  assets/blocks/course-outline/course-outline-store.js
  assets/blocks/quiz/data.js
  assets/blocks/quiz/quiz-store.js
  assets/shared/structure/structure-store.js
  assets/shared/structure/structure-store.test.js
Labels: [Type] Bug

#5326 Fix unexpected style on the body
  assets/css/frontend.scss
Labels: [Type] Bug

#5327 Add a test for not existing block
  assets/shared/structure/structure-store.test.js
Labels: [Type] Maintenance

#5328 Remove unquoted complex placeholders
  includes/class-sensei-analysis-overview-list-table.php
  includes/reports/overview/data-provider/class-sensei-reports-overview-data-provider-courses.php
  includes/reports/overview/data-provider/class-sensei-reports-overview-data-provider-students.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-lessons.php
  includes/reports/overview/services/class-sensei-reports-overview-service-courses.php
  includes/reports/overview/services/class-sensei-reports-overview-service-students.php
Labels: [Type] Enhancement

#5323 Filter providers before checking if they handle enrolment on the frontend
  includes/enrolment/class-sensei-course-enrolment-manager.php
Labels: Hooks

#5332 Bump the minimum required PHP version to 7.2
  .github/workflows/php.yml
  composer.json
  composer.lock
  includes/class-sensei-dependency-checker.php
  readme.txt
  sensei-lms.php
Labels: [Type] Enhancement

#5342 Fix quiz saving
  assets/blocks/quiz/quiz-store.js
Labels: [Type] Bug

#5294 Add method to return the set of course ids for a given array of lesson ids
  includes/class-sensei-lesson.php
  includes/class-sensei.php
  tests/unit-tests/test-class-lesson.php
Labels: [Pri] High, Performance

#5333 Move `sensei_can_user_view_lesson` function to be created earlier
  includes/sensei-functions.php
  includes/template-functions.php
Labels: [Type] Bug

#5338 Update the pricing page links
  assets/admin/editor-wizard/steps/course-upgrade-step.js
  assets/admin/editor-wizard/steps/lesson-patterns-step.js
  assets/blocks/quiz/ordering-promo/index.js
  assets/blocks/quiz/quiz-block/quiz-timer-promo.js
  assets/extensions/featured-product-sensei-pro.js
  assets/js/admin/course-access-period-promo-sidebar.js
  assets/js/admin/course-pricing-promo-sidebar.js
  includes/class-sensei-groups-landing-page.php
  includes/class-sensei-lesson.php
  includes/class-sensei-settings-api.php
  readme.txt
Labels: [Type] Maintenance

#5348 Fix bulk-edit for Lessons
  assets/js/admin/lesson-bulk-edit.js
Labels: [Type] Bug

#5343 Fix an error on the admin lessons screen
  includes/class-sensei-lesson.php
  includes/class-sensei-modules.php
Labels: [Type] Bug

#5350 Fix placeholder images for courses
  includes/class-sensei-course.php
  includes/class-sensei-lesson.php
Labels: [Type] Bug

#5349 Change 'Manage Learners' to 'Manage Students' on the course management meta box
  includes/class-sensei-course.php
Labels: [Type] Bug

#5352 Feature/students group
  assets/admin/editor-wizard/steps/course-upgrade-step.js
  assets/admin/editor-wizard/steps/lesson-patterns-step.js
  assets/blocks/quiz/ordering-promo/index.js
  assets/blocks/quiz/quiz-block/quiz-timer-promo.js
  assets/css/fonts/Inter.otf
  assets/css/settings.scss
  assets/extensions/featured-product-sensei-pro.js
  assets/images/groups-promo-desktop.png
  assets/images/groups-promo-mobile.png
  assets/js/admin/course-access-period-promo-sidebar.js
  assets/js/admin/course-pricing-promo-sidebar.js
  includes/class-sensei-groups-landing-page.php
  includes/class-sensei-lesson.php
  includes/class-sensei-posttypes.php
  includes/class-sensei-settings-api.php
  readme.txt
Labels: Groups

#5354 Fix quiz notice error when lesson is completed
  includes/class-sensei-question.php
Labels: [Type] Bug

#5362 Fix url encoding of timezone for reports
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-abstract.php
Labels: [Type] Bug

#5373 Update videopress event name
  assets/js/frontend/course-video/videopress-extension.js
Labels: [Type] Bug

#5374 Add coverage report for JavaScript
  .github/workflows/code-coverage.yml
  .github/workflows/php.yml
  jest.config.js
  package.json
Labels: [Type] Maintenance

#5361 Add Confirm Dialog component
  assets/blocks/editor-components/confirm-dialog/confirm-dialog.js
  assets/blocks/editor-components/confirm-dialog/confirm-dialog.scss
  assets/blocks/editor-components/confirm-dialog/confirm-dialog.test.js
  assets/blocks/editor-components/confirm-dialog/index.js
  assets/blocks/editor-components/confirm-dialog/use-confirm-dialog-props.js
  assets/blocks/editor-components/confirm-dialog/use-confirm-dialog-props.test.js
  assets/blocks/editor-components/editor-components-style.scss
Labels: [Type] Enhancement

#5207 Add custom slug in module block
  assets/blocks/course-outline/data.js
  assets/blocks/course-outline/module-block/block.json
  assets/blocks/course-outline/module-block/module-edit.js
  assets/blocks/course-outline/module-block/module-edit.test.js
  assets/blocks/course-outline/module-block/module-settings.js
  assets/blocks/course-outline/module-block/module.scss
  assets/js/admin/course-edit.js
  includes/class-sensei-course-structure.php
  includes/class-sensei-modules.php
  includes/class-sensei-teacher.php
  tests/framework/factories/class-sensei-factory.php
  tests/unit-tests/rest-api/test-class-sensei-rest-api-course-structure-controller.php
  tests/unit-tests/test-class-teacher.php
Labels: [Type] Enhancement, Modules, Blocks, Course Outline Block

#5379 Fix Gutenberg compatibility issue
  includes/class-sensei-messages.php
  includes/course-theme/class-sensei-course-theme.php
Labels: [Type] Bug

#5380 Remove additional line from login redirection code
  includes/class-sensei-frontend.php
Labels: [Type] Bug

#5381 Prepare 4.6.0 release
  changelog.txt
  includes/class-sensei-course-structure.php
  includes/class-sensei-modules.php
  includes/class-sensei-quiz.php
  includes/class-sensei-teacher.php
  includes/class-sensei.php
  includes/reports/overview/data-provider/class-sensei-reports-overview-data-provider-students.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-abstract.php
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
Labels: [Type] Maintenance

#5364 Add players API
  assets/shared/helpers/player.js
Labels: [Type] Enhancement, Interactive Video Block

#5356 Remove the warning in the learning mode
  assets/blocks/lesson-actions/lesson-actions-block/lesson-actions-edit.js
Labels: [Type] Enhancement

#5386 Hide action buttons' notification
  assets/blocks/lesson-actions/lesson-actions-block/lesson-actions-edit.js
Labels: [Type] Maintenance

#5387 Fix/modules losing configuration when module is changed
  assets/blocks/course-outline/data.js
  assets/blocks/course-outline/data.test.js
Labels: [Type] Maintenance

#5377 Add editor player hook
  assets/shared/helpers/player.js
  assets/shared/helpers/player/index.js
  assets/shared/helpers/player/use-editor-player.js
  assets/shared/helpers/player/video-file-adapter.js
  assets/shared/helpers/player/videopress-adapter.js
  assets/shared/helpers/player/vimeo-adapter.js
  assets/shared/helpers/player/youtube-adapter.js
Labels: [Type] Enhancement, Interactive Video Block
