Repository Automattic/sensei, pull requests merged in 2022-02, with the labels that each got.

#4730 Fix link styles in Learning Mode
  assets/css/sensei-course-theme/buttons.scss
Labels: [Type] Bug

#4705 CI: Enable PHP 7.0
  .github/workflows/e2e.yml
  .github/workflows/js.yml
  .github/workflows/php.yml
  composer.json
  composer.lock
  phpcs.xml.dist
  tests/bootstrap.php
  tests/framework/factories/class-sensei-factory.php
  tests/images/greenapple.jpg
  tests/images/greenfrog.jpg
  tests/images/sensei.png
  tests/unit-tests/test-class-quiz.php
Labels: [Type] Maintenance

#4767 Remove method argument type
  includes/course-theme/class-sensei-course-theme.php
Labels: [Type] Enhancement

#4748 Fix course archive page when there's no custom permalink structure
  includes/class-sensei-course.php
  includes/class-sensei-posttypes.php
  includes/class-sensei-utils.php
Labels: [Type] Bug

#4774 Fix different default option on boolean questions
  includes/rest-api/class-sensei-rest-api-question-helpers-trait.php
Labels: [Type] Bug

#4779 Fix PHP Warning when exporting questions without wrong answers
  includes/data-port/export-tasks/class-sensei-export-questions.php
Labels: [Type] Bug

#4746 Add wp-env support
  .gitignore
  .wp-env.json
  package-lock.json
  package.json
Labels: [Type] Maintenance

#4792 Redirect logged-out user to the course after login when clicking on Take Course button in the Course page
  includes/blocks/class-sensei-block-take-course.php
Labels: [Type] Enhancement

#4793 Update Take course button from lesson notices to redirect to course
  includes/course-theme/class-sensei-course-theme-lesson.php
Labels: [Type] Enhancement

#4791 Update `package-lock.json`
  package-lock.json
Labels: [Type] Maintenance

#4790 Fix CSV importing on PHP 8
  includes/data-port/class-sensei-import-csv-reader.php
Labels: [Type] Bug

#4804 Fix JavaScript Error on the grading page
  assets/js/grading-general.js
  includes/class-sensei-grading-user-quiz.php
Labels: [Type] Bug

#4808 Move the Course Completed page to Trash when uninstalling the plugin
  includes/class-sensei-data-cleaner.php
  tests/unit-tests/test-class-sensei-data-cleaner.php
Labels: [Type] Bug

#4794 Add upgrade header to Extensions page
  assets/css/fonts/Reforma1918-Blanca.otf
  assets/extensions/extensions.scss
  assets/extensions/featured-product-sensei-pro.js
  assets/extensions/featured-product.js
  assets/extensions/main.js
  assets/icons/checked-white.svg
  includes/admin/class-sensei-extensions.php
  tests/unit-tests/admin/test-class-sensei-extensions.php
  tests/unit-tests/admin/test-class-sensei-wcpc-prompt.php
Labels: [Type] Enhancement, Hooks

#4778 Fix learning mode notices in preview lessons
  includes/course-theme/class-sensei-course-theme-lesson.php
  tests/unit-tests/course-theme/test-class-sensei-course-theme-lesson.php
Labels: [Type] Bug

#4821 Add upgrade nudge for access period
  assets/css/course-editor.scss
  assets/js/admin/course-access-period-promo-sidebar.js
  assets/js/admin/course-edit.js
Labels: [Type] Enhancement, Hooks

#4816 Add upgrade nudge to Quiz block settings
  assets/blocks/quiz/quiz-block/quiz-settings.js
  assets/blocks/quiz/quiz-block/quiz-settings.test.js
  assets/blocks/quiz/quiz-block/quiz-timer-promo.js
  assets/blocks/quiz/quiz.editor.scss
  assets/extensions/main.js
Labels: [Type] Enhancement, Hooks

#4809 Add content drip upgrade metabox to edit lesson screen
  assets/css/lesson-editor.scss
  assets/icons/external-link.svg
  includes/class-sensei-lesson.php
  webpack.config.js
Labels: [Type] Enhancement, Hooks

#4822 Add content drip promo banner to settings
  assets/css/settings.scss
  assets/images/content-drip-promo-desktop.png
  assets/images/content-drip-promo-mobile.png
  assets/js/settings.js
  includes/class-sensei-settings-api.php
  includes/class-sensei-settings.php
Labels: [Type] Enhancement

#4815 Add Ordering promo question type
  assets/blocks/quiz/ordering-promo/index.js
  assets/blocks/quiz/question-block/question-block.editor.scss
  assets/blocks/quiz/question-block/question-type-toolbar.js
  includes/blocks/class-sensei-quiz-blocks.php
  webpack.config.js
Labels: [Type] Enhancement, Hooks

#4810 Add Pricing side item for displating upgrade to sensei pro option
  assets/css/course-editor.scss
  assets/js/admin/course-edit.js
  assets/js/admin/course-pricing-promo-sidebar.js
Labels: [Type] Enhancement

#4727 Order lessons between modules
  assets/css/admin-custom.scss
  assets/js/admin/ordering.js
  includes/class-sensei-admin.php
  tests/unit-tests/test-class-admin.php
Labels: [Type] Enhancement

#4837 Fix course ordering not working on admin dashboard and shortcode pages
  includes/class-sensei-course.php
  tests/unit-tests/test-class-course.php
Labels: [Type] Bug

#4819 Fix some JS deprecated functions
  .eslintrc.js
  assets/js/admin/blocks-toggling-control.js
  assets/js/admin/course-edit.js
  assets/js/admin/meta-box-quiz-editor.js
  assets/js/admin/ordering.js
  assets/js/modules-admin.js
Labels: [Pri] Low, [Type] Maintenance

#4851 Fix unit tests
  tests/unit-tests/test-class-course.php
Labels: [Type] Maintenance

#4856 Update ReadMe
  readme.txt
Labels: [Type] Maintenance

#4848 Allow user re-enrolling even when removed
  includes/class-sensei-frontend.php
Labels: [Type] Bug

#4858 Fix addEventListener when no element is found
  assets/js/admin/course-edit.js
Labels: [Type] Bug

#4857 Merge upsells to master
  assets/blocks/quiz/ordering-promo/index.js
  assets/blocks/quiz/question-block/question-block.editor.scss
  assets/blocks/quiz/question-block/question-type-toolbar.js
  assets/blocks/quiz/quiz-block/quiz-settings.js
  assets/blocks/quiz/quiz-block/quiz-settings.test.js
  assets/blocks/quiz/quiz-block/quiz-timer-promo.js
  assets/blocks/quiz/quiz.editor.scss
  assets/css/course-editor.scss
  assets/css/fonts/Reforma1918-Blanca.otf
  assets/css/lesson-editor.scss
  assets/css/settings.scss
  assets/extensions/extensions.scss
  assets/extensions/featured-product-sensei-pro.js
  assets/extensions/featured-product.js
  assets/extensions/main.js
  assets/icons/checked-white.svg
  assets/icons/external-link.svg
  assets/images/content-drip-promo-desktop.png
  assets/images/content-drip-promo-mobile.png
  assets/images/purchase-sensei-pro-desktop.png
  assets/images/purchase-sensei-pro-mobile.png
  assets/js/admin/course-access-period-promo-sidebar.js
  assets/js/admin/course-edit.js
  assets/js/admin/course-pricing-promo-sidebar.js
  assets/js/settings.js
  includes/admin/class-sensei-extensions.php
  includes/blocks/class-sensei-quiz-blocks.php
  includes/class-sensei-assets.php
  includes/class-sensei-lesson.php
  includes/class-sensei-settings-api.php
  includes/class-sensei-settings.php
  readme.txt
  tests/unit-tests/admin/test-class-sensei-extensions.php
  tests/unit-tests/admin/test-class-sensei-wcpc-prompt.php
  webpack.config.js
Labels: [Type] Maintenance

#4854 Remove the reports totals sidebar
  assets/css/settings.scss
  includes/class-sensei-analysis-overview-list-table.php
  includes/class-sensei-analysis.php
Labels: [Type] Enhancement, Hooks, Deprecation

#4861 Add lesson actions and navigation to the bottom of the content, for screen reader only
  assets/css/sensei-course-theme/lesson-actions.scss
  includes/blocks/course-theme/class-page-actions.php
Labels: Accessibility

#4877 Add phpcs check for missing function param comment
  phpcs.xml.dist
Labels: [Type] Maintenance

#4863 Reports: Replace `Date Registered` column with `Last Activity`
  includes/class-sensei-analysis-overview-list-table.php
  tests/unit-tests/test-class-sensei-analysis-overview-list-table.php
Labels: [Type] Enhancement
