Repository Automattic/sensei, pull requests merged in 2022-06, with the labels that each got.

#5206 Add new sensei patterns and separate block patterns logic
  assets/admin/editor-wizard/patterns-list.js
  assets/admin/editor-wizard/patterns-list.scss
  assets/admin/editor-wizard/style.scss
  assets/images/pattern-long-sales-01.jpg
  assets/images/pattern-long-sales-02.jpg
  assets/images/pattern-long-sales-03.jpg
  assets/images/patterns-video-hero-01.jpg
  assets/images/patterns-video-hero-02.jpg
  assets/images/patterns-video-hero-03.jpg
  assets/images/patterns-video.mp4
  includes/admin/class-sensei-editor-wizard.php
  includes/block-patterns/class-sensei-block-patterns.php
  includes/block-patterns/course/long-sales-page.php
  includes/block-patterns/course/templates/long-sales-page.php
  includes/block-patterns/course/templates/video-hero.php
  includes/block-patterns/course/video-hero.php
  includes/block-patterns/lesson/discussion-question.php
  includes/block-patterns/lesson/files-to-download.php
  includes/block-patterns/lesson/templates/discussion-question.php
  includes/block-patterns/lesson/templates/files-to-download.php
  includes/block-patterns/lesson/templates/video-lesson.php
  includes/block-patterns/lesson/video-lesson.php
  includes/class-sensei-autoloader.php
  includes/class-sensei.php
Labels: [Type] Enhancement

#5225 Fix lesson patterns placeholders
  includes/block-patterns/lesson/templates/discussion-question.php
  includes/block-patterns/lesson/templates/video-lesson.php
Labels: [Type] Bug

#5228 Fix pattern images urls
  assets/images/patterns-long-sales-01.jpg
  assets/images/patterns-long-sales-02.jpg
  assets/images/patterns-long-sales-03.jpg
Labels: [Type] Bug

#5222 Fix patterns styles for TwentyTwenty One
  assets/blocks/button/button-edit.js
  includes/block-patterns/course/templates/long-sales-page.php
  includes/block-patterns/course/templates/video-hero.php
Labels: [Type] Bug

#5220 Fix editor wizard styles
  assets/admin/editor-wizard/steps/course-details-step.js
  assets/admin/editor-wizard/steps/course-upgrade-step.js
  assets/admin/editor-wizard/steps/lesson-details-step.js
  assets/admin/editor-wizard/steps/patterns-step.js
  assets/admin/editor-wizard/style.scss
  assets/blocks/editor-components/limited-text-control/index.js
Labels: [Type] Bug

#5232 Fix course pattern themes compatibility
  assets/admin/editor-wizard/steps/course-patterns-step.js
  assets/css/block-patterns.scss
  includes/block-patterns/class-sensei-block-patterns.php
  includes/block-patterns/course/templates/long-sales-page.php
  includes/block-patterns/course/templates/video-hero.php
  webpack.config.js
Labels: [Type] Bug

#5254 Add Upsell section for Premium Lesson Patterns
  assets/admin/editor-wizard/steps/lesson-patterns-step.js
  assets/admin/editor-wizard/steps/patterns-step.js
  assets/admin/editor-wizard/style.scss
  assets/icons/logo-tree.svg
Labels: [Type] Enhancement

#5246 Add default course pattern
  assets/admin/editor-wizard/editor-wizard-modal.js
  assets/admin/editor-wizard/helpers.js
  assets/blocks/core-pattern-polyfill/README.md
  assets/blocks/core-pattern-polyfill/block.json
  assets/blocks/core-pattern-polyfill/core-pattern-polyfill.js
  assets/blocks/core-pattern-polyfill/edit.js
  assets/blocks/core-pattern-polyfill/index.js
  includes/block-patterns/class-sensei-block-patterns.php
  includes/block-patterns/course/course-default.php
  includes/block-patterns/course/templates/course-default.php
  includes/blocks/class-sensei-course-blocks.php
  webpack.config.js
Labels: [Type] Enhancement

#5257 Fixes to the Upsell for Premium Lesson Patterns
  assets/admin/editor-wizard/steps/lesson-patterns-step.js
  assets/admin/editor-wizard/use-editor-wizard-steps.js
  assets/admin/editor-wizard/use-editor-wizard-steps.test.js
  includes/admin/class-sensei-extensions.php
  tests/unit-tests/admin/test-class-sensei-setup-wizard-api.php
  tests/unit-tests/admin/test-class-sensei-setup-wizard.php
Labels: [Type] Enhancement

#5256 Add filter for loading custom navigation script for pages
  includes/class-sensei-admin.php
Labels: Hooks

#5259 Fix broken blocks on WP 5.8
  includes/block-patterns/course/templates/life-coach.php
Labels: [Type] Bug

#5261 Fix Course Outline styles on pattern thumbnails
  assets/blocks/course-outline/course-outline-editor.scss
Labels: [Type] Bug

#5268 Change lesson pattern with quiz
  includes/block-patterns/lesson/templates/default-with-quiz.php
Labels: [Type] Enhancement

#5265 Fix svg mock in JS tests
  tests/__mocks__/svg.js
Labels: [Type] Maintenance

#5266 Fix JS tests issues
  assets/admin/editor-wizard/helpers.test.js
  package-lock.json
Labels: [Type] Maintenance

#5270 Fix svg mock for JS tests
  tests/__mocks__/svg.js
Labels: [Type] Bug

#5233 Add a workflow to close issues when the PR is merged
  .codecov.yml
  .github/workflows/close-issue-on-merge.yml
  .github/workflows/e2e-playwright.yml
Labels: [Type] Maintenance

#5274 Add editor wizard usage tracking
  assets/admin/editor-wizard/editor-wizard-modal.js
  assets/admin/editor-wizard/helpers.js
  assets/admin/editor-wizard/patterns-list.js
  assets/admin/editor-wizard/steps/patterns-step.js
  assets/admin/editor-wizard/wizard.js
  assets/admin/editor-wizard/wizard.test.js
Labels: Logging

#5282 Add woothemes-sensei detection to the extensions API
  assets/admin/editor-wizard/helpers.js
  assets/admin/editor-wizard/steps/lesson-patterns-step.js
  assets/admin/editor-wizard/use-editor-wizard-steps.js
Labels: [Type] Bug

#5295 Add Divi fix when using Learning Mode
  assets/css/sensei-course-theme/layout.scss
Labels: [Type] Bug
