Repository Automattic/sensei, pull requests merged in 2023-10, with the labels that each got.

#7171 Changed styles for question feedback
  assets/blocks/quiz/question-block/question.scss
  assets/css/3rd-party/themes/divi/learning-mode.scss
  changelog/add-changed-styles-for-question-feedback
  includes/class-sensei-question.php
Labels: [Project] Frontend Improvements

#7190 Update stylings for footer in awaiting grade quizzes in learning mode
  assets/css/3rd-party/themes/course/quiz.scss
  assets/css/frontend.scss
  assets/css/sensei-course-theme/quiz-compat.scss
  assets/css/sensei-course-theme/quiz.scss
  changelog/add-stylings-for-footer-in-awaiting-grade-quiz-lm
  includes/blocks/course-theme/class-lesson-actions.php
  includes/class-sensei-quiz.php
  tests/unit-tests/test-class-quiz.php
Labels: [Project] Frontend Improvements

#7202 Update footer design for graded quiz
  assets/css/sensei-course-theme/content.scss
  assets/css/sensei-course-theme/quiz.scss
  changelog/add-footer-design-for-graded-quiz
  includes/blocks/course-theme/class-lesson-actions.php
  includes/class-sensei-quiz.php
  tests/unit-tests/test-class-quiz.php
Labels: [Project] Frontend Improvements

#7206 Add question mark on the end of the phrase 'Does Sensei work in my language'
  readme.txt
Labels: No Changelog

#7185 Use student progress models on the frontend
  config/psalm/psalm-baseline.xml
  includes/admin/tools/class-sensei-tool-enrolment-debug.php
  includes/blocks/course-theme/class-course-navigation.php
  includes/class-sensei-course.php
  includes/class-sensei-grading.php
  includes/class-sensei-lesson.php
  includes/class-sensei-modules.php
  includes/class-sensei-question.php
  includes/class-sensei-quiz.php
  includes/class-sensei-utils.php
  includes/class-sensei.php
  includes/course-theme/class-sensei-course-theme-lesson.php
  includes/course-theme/class-sensei-course-theme-quiz.php
  includes/course-theme/class-sensei-course-theme-templates.php
  includes/internal/migration/migrations/class-student-progress-migration.php
  includes/internal/student-progress/course-progress/models/class-course-progress-abstract.php
  includes/internal/student-progress/course-progress/repositories/class-comment-reading-aggregate-course-progress-repository.php
  includes/internal/student-progress/course-progress/repositories/class-comments-based-course-progress-repository.php
  includes/internal/student-progress/course-progress/repositories/class-course-progress-repository-factory.php
  includes/internal/student-progress/course-progress/repositories/class-course-progress-repository-interface.php
  includes/internal/student-progress/course-progress/repositories/class-table-reading-aggregate-course-progress-repository.php
  includes/internal/student-progress/course-progress/repositories/class-tables-based-course-progress-repository.php
  includes/internal/student-progress/lesson-progress/models/class-lesson-progress-abstract.php
  includes/internal/student-progress/lesson-progress/repositories/class-comment-reading-aggregate-lesson-progress-repository.php
  includes/internal/student-progress/lesson-progress/repositories/class-comments-based-lesson-progress-repository.php
  includes/internal/student-progress/lesson-progress/repositories/class-lesson-progress-repository-factory.php
  includes/internal/student-progress/lesson-progress/repositories/class-lesson-progress-repository-interface.php
  includes/internal/student-progress/lesson-progress/repositories/class-table-reading-aggregate-lesson-progress-repository.php
  includes/internal/student-progress/lesson-progress/repositories/class-tables-based-lesson-progress-repository.php
  includes/internal/student-progress/quiz-progress/models/class-comments-based-quiz-progress.php
  includes/internal/student-progress/quiz-progress/models/class-quiz-progress-abstract.php
  includes/internal/student-progress/quiz-progress/repositories/class-comment-reading-aggregate-quiz-progress-repository.php
  includes/internal/student-progress/quiz-progress/repositories/class-comments-based-quiz-progress-repository.php
  includes/internal/student-progress/quiz-progress/repositories/class-quiz-progress-repository-factory.php
  includes/internal/student-progress/quiz-progress/repositories/class-quiz-progress-repository-interface.php
  includes/internal/student-progress/quiz-progress/repositories/class-table-reading-aggregate-quiz-progress-repository.php
  includes/internal/student-progress/quiz-progress/repositories/class-tables-based-quiz-progress-repository.php
  includes/sensei-functions.php
  includes/template-functions.php
  psalm.xml
  templates/course-results/lessons.php
  tests/unit-tests/internal/quiz-submission/submission/repositories/test-class-comments-based-submission-repository.php
  tests/unit-tests/internal/student-progress/course-progress/repositories/test-class-comment-reading-aggregate-course-progress-repository.php
  tests/unit-tests/internal/student-progress/course-progress/repositories/test-class-comments-based-course-progress-repository.php
  tests/unit-tests/internal/student-progress/course-progress/repositories/test-class-table-reading-aggregate-course-progress-repository.php
  tests/unit-tests/internal/student-progress/course-progress/repositories/test-class-tables-based-course-progress-repository.php
  tests/unit-tests/internal/student-progress/lesson-progress/repositories/test-class-comment-reading-aggregate-lesson-progress-repository.php
  tests/unit-tests/internal/student-progress/lesson-progress/repositories/test-class-comments-based-lesson-progress-repository.php
  tests/unit-tests/internal/student-progress/lesson-progress/repositories/test-class-table-reading-aggregate-lesson-progress-repository.php
  tests/unit-tests/internal/student-progress/lesson-progress/repositories/test-class-tables-based-lesson-progress-repository.php
  tests/unit-tests/internal/student-progress/quiz-progress/repositories/test-class-comment-reading-aggregate-quiz-progress-repository.php
  tests/unit-tests/internal/student-progress/quiz-progress/repositories/test-class-table-reading-aggregate-quiz-progress-repository.php
  tests/unit-tests/internal/student-progress/quiz-progress/repositories/test-class-tables-based-quiz-progress-repository.php
  tests/unit-tests/test-class-course.php
  tests/unit-tests/test-class-lesson.php
  tests/unit-tests/test-class-quiz.php
Labels: [Project] High-Performance Progress Storage, No Changelog

#7216 Release 4.18.0
  changelog.txt
  changelog/add-changed-styles-for-question-feedback
  changelog/add-footer-design-for-graded-quiz
  changelog/add-php-81-support
  changelog/add-styles-for-sensei-login-page
  changelog/add-styles-for-sensei-login-page-dev
  changelog/add-stylings-for-footer-in-awaiting-grade-quiz-lm
  changelog/add-success-message-styles
  changelog/add-update-design-on-navigation-in-quiz-template-editor
  changelog/fix-course-list-width
  changelog/fix-learner-courses-block-classname
  changelog/fix-missing-next-lesson-button
  changelog/fix-reset-progress
  changelog/fix-sensei-email-generating-multiple-queries-on-page-load
  changelog/fix-translation-with-gender-issues
  changelog/update-php-version
  includes/blocks/class-sensei-course-results-block.php
  includes/blocks/class-sensei-learner-courses-block.php
  includes/class-sensei-quiz.php
  includes/class-sensei-utils.php
  includes/internal/emails/generators/class-email-generators-abstract.php
  includes/internal/student-progress/course-progress/models/class-comments-based-course-progress.php
  includes/internal/student-progress/course-progress/models/class-course-progress-abstract.php
  includes/internal/student-progress/course-progress/models/class-course-progress-interface.php
  includes/internal/student-progress/course-progress/models/class-tables-based-course-progress.php
  includes/internal/student-progress/lesson-progress/models/class-comments-based-lesson-progress.php
  includes/internal/student-progress/lesson-progress/models/class-lesson-progress-abstract.php
  includes/internal/student-progress/lesson-progress/models/class-lesson-progress-interface.php
  includes/internal/student-progress/lesson-progress/models/class-tables-based-lesson-progress.php
  includes/internal/student-progress/quiz-progress/models/class-comments-based-quiz-progress.php
  includes/internal/student-progress/quiz-progress/models/class-quiz-progress-abstract.php
  includes/internal/student-progress/quiz-progress/models/class-quiz-progress-interface.php
  includes/internal/student-progress/quiz-progress/models/class-tables-based-quiz-progress.php
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
  templates/user/login-form.php
Labels: No Changelog

#7214 Remove mentions of "[Type] Maintenance" label
  renovate.json
  scripts/release-pr-steps.sh
Labels: No Changelog

#7222 Add table-reading quiz submission repositories
  includes/class-sensei-utils.php
  includes/class-sensei.php
  includes/internal/quiz-submission/answer/repositories/class-answer-repository-factory.php
  includes/internal/quiz-submission/answer/repositories/class-comment-reading-aggregate-answer-repository.php
  includes/internal/quiz-submission/answer/repositories/class-table-reading-aggregate-answer-repository.php
  includes/internal/quiz-submission/grade/repositories/class-comment-reading-aggregate-grade-repository.php
  includes/internal/quiz-submission/grade/repositories/class-grade-repository-factory.php
  includes/internal/quiz-submission/grade/repositories/class-table-reading-aggregate-grade-repository.php
  includes/internal/quiz-submission/submission/repositories/class-comment-reading-aggregate-submission-repository.php
  includes/internal/quiz-submission/submission/repositories/class-submission-repository-factory.php
  includes/internal/quiz-submission/submission/repositories/class-table-reading-aggregate-submission-repository.php
  includes/internal/student-progress/course-progress/repositories/class-course-progress-repository-factory.php
  tests/unit-tests/internal/quiz-submission/answer/repositories/test-class-answer-repository-factory.php
  tests/unit-tests/internal/quiz-submission/answer/repositories/test-class-comment-reading-aggregate-answer-repository.php
  tests/unit-tests/internal/quiz-submission/answer/repositories/test-class-table-reading-aggregate-answer-repository.php
  tests/unit-tests/internal/quiz-submission/grade/repositories/test-class-comment-reading-aggregate-grade-repository.php
  tests/unit-tests/internal/quiz-submission/grade/repositories/test-class-grade-repository-factory.php
  tests/unit-tests/internal/quiz-submission/grade/repositories/test-class-table-reading-aggregate-grade-repository.php
  tests/unit-tests/internal/quiz-submission/submission/repositories/test-class-comment-reading-aggregate-submission-repository.php
  tests/unit-tests/internal/quiz-submission/submission/repositories/test-class-submission-repository-factory.php
  tests/unit-tests/internal/quiz-submission/submission/repositories/test-class-table-reading-aggregate-submission-repository.php
Labels: [Project] High-Performance Progress Storage, No Changelog

#7230 Add a progress table eraser tool
  includes/class-sensei.php
  includes/internal/tools/class-progress-tables-eraser.php
  includes/internal/tools/views/html-progress-tables-eraser-form.php
  tests/unit-tests/internal/tools/test-class-progress-tables-eraser.php
Labels: [Project] High-Performance Progress Storage, No Changelog

#7239 Update text standard on course settings
  assets/js/admin/course-general-sidebar.js
  assets/js/admin/course-video-sidebar.js
Labels: No Changelog

#7247 Fix no side spacing applied in quiz in learning mode for mobile view
  assets/css/sensei-course-theme/content.scss
  themes/sensei-course-theme/templates/quiz.html
Labels: Learning Mode, No Changelog, [Project] Frontend Improvements

#7231 Add a course setting to not allow self-enrollment
  assets/js/admin/course-general-sidebar.js
  changelog/add-setting-not-allowing-self-enrollment
  changelog/fix-take-course-notices
  includes/blocks/class-sensei-block-take-course.php
  includes/class-sensei-course.php
  includes/class-sensei-lesson.php
  includes/course-theme/class-sensei-course-theme-lesson.php
  tests/unit-tests/blocks/test-class-sensei-block-take-course.php
  tests/unit-tests/course-theme/test-class-sensei-course-theme-lesson.php
  tests/unit-tests/test-class-course.php
  tests/unit-tests/test-class-lesson.php
Labels: [Status] Needs Documentation
