Repository Automattic/sensei, pull requests merged in 2023-06, with the labels that each got.

#6945 Add a project task template using forms
  .github/ISSUE_TEMPLATE/project_task.yml
Labels: No Changelog

#6936 Fix editor block error when updating an email
  changelog/fix-editor-block-error-when-changing-email-status
  includes/internal/emails/patterns/content-drip.php
  includes/internal/emails/patterns/course-created.php
  includes/internal/emails/patterns/course-expiration-today.php
  includes/internal/emails/patterns/course-expiration-x-days.php
  includes/internal/emails/patterns/course-welcome.php
  includes/internal/emails/patterns/new-course-assigned.php
  includes/internal/emails/patterns/quiz-graded.php
  includes/internal/emails/patterns/student-completes-course.php
  includes/internal/emails/patterns/student-completes-lesson.php
  includes/internal/emails/patterns/student-message-reply.php
  includes/internal/emails/patterns/student-no-progress-28-days.php
  includes/internal/emails/patterns/student-no-progress-3-days.php
  includes/internal/emails/patterns/student-no-progress-7-days.php
  includes/internal/emails/patterns/student-sends-message.php
  includes/internal/emails/patterns/student-starts-course.php
  includes/internal/emails/patterns/student-submits-quiz.php
  includes/internal/emails/patterns/teacher-message-reply.php
Labels: [Type] Bug, Emails

#6940 Fix Course Wizard spacing when using the latest Gutenberg
  assets/admin/editor-wizard/style.scss
  changelog/fix-course-wizard-spacing-on-latest-gutenberg
Labels: [Type] Bug

#6437 Use title/lastTitle sync strategy only for modules
  assets/blocks/course-outline/data.js
  assets/blocks/course-outline/data.test.js
  assets/blocks/course-outline/lesson-block/lesson-edit.js
Labels: [Type] Bug, No Changelog

#6975 Avoid an error with getting future post URL
  changelog/fix-frontend-error-when-schedule-email
  includes/internal/emails/class-email-post-type.php
Labels: [Type] Bug

#6966 Add Enrolled and Completion Rate columns to Courses report
  changelog/update-course-report
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-courses.php
  includes/reports/overview/services/class-sensei-reports-overview-service-courses.php
  tests/unit-tests/reports/overview/list-table/test-class-sensei-reports-overview-list-table-courses.php
  tests/unit-tests/reports/overview/services/test-class-sensei-reports-overview-service-courses.php
Labels: Reports

#6643 Fix resetting a quiz also resets the course start date
  changelog/fix-course-start-date-reset
  includes/class-sensei-quiz.php
  tests/unit-tests/test-class-quiz.php
Labels: [Type] Bug

#6974 Update placeholder for course outline block to include blank or AI option
  assets/blocks/course-outline/course-outline-editor.scss
  assets/blocks/course-outline/outline-block/ai-lessons-image.js
  assets/blocks/course-outline/outline-block/outline-placeholder.js
  assets/blocks/course-outline/outline-block/outline-placeholder.test.js
  assets/blocks/single-course-style-editor.scss
  assets/shared/components/ai-icon/index.js
  assets/shared/components/ai-loader-icon/index.js
  assets/shared/components/sensei-pro-badge/index.js
  assets/shared/components/sensei-pro-badge/style.scss
  assets/shared/styles/_variables.scss
  changelog/update-course-outline-placeholder-options
  includes/blocks/class-sensei-course-blocks.php
Labels: [Status] Needs Documentation

#6906 Fix auto grading not working for multiple choice questions when multiple correct answers
  assets/js/grading-general.js
  changelog/fix-multiple-choice-question-auto-grading
Labels: [Type] Bug

#6977 Fix Lesson Complete email recipient
  changelog/fix-lesson-complete-email-recipient
  includes/internal/emails/generators/class-course-teachers-trait.php
  includes/internal/emails/generators/class-email-generators-abstract.php
  includes/internal/emails/generators/class-student-completes-course.php
  includes/internal/emails/generators/class-student-completes-lesson.php
  tests/unit-tests/internal/emails/generators/test-class-student-completes-course.php
  tests/unit-tests/internal/emails/generators/test-class-student-completes-lesson.php
Labels: [Type] Bug

#6984 Remove trailing <br> in the user answer and in the correct answer before comparing
  assets/js/grading-general.js
  changelog/fix-auto-grading-non-multiple
Labels: [Type] Bug

#6971 Fix end to e2e fails caused by nonce issue
  .github/workflows/e2e.yml
  package-lock.json
  playwright.config.js
  tests/e2e-playwright/config/global-setup.ts
  tests/e2e-playwright/factories/users.ts
  tests/e2e-playwright/helpers/api/contexts.ts
  tests/e2e-playwright/helpers/api/courses.ts
  tests/e2e-playwright/helpers/api/index.ts
  tests/e2e-playwright/helpers/api/users.ts
  tests/e2e-playwright/helpers/context.ts
  tests/e2e-playwright/helpers/database.ts
  tests/e2e-playwright/specs/admin/blocks/course-list-block.spec.ts
  tests/e2e-playwright/specs/admin/students/students-management.spec.ts
  tests/e2e-playwright/specs/admin/teacher/course-creation.spec.ts
  tests/e2e-playwright/specs/frontend/course-fixtures.ts
Labels: [Type] Maintenance, e2e, No Changelog

#6987 Release 4.15.1
  changelog.txt
  changelog/fix-auto-grading-non-multiple
  changelog/fix-course-start-date-reset
  changelog/fix-course-wizard-spacing-on-latest-gutenberg
  changelog/fix-editor-block-error-when-changing-email-status
  changelog/fix-frontend-error-when-schedule-email
  changelog/fix-lesson-complete-email-recipient
  changelog/fix-multiple-choice-question-auto-grading
  changelog/update-course-outline-placeholder-options
  changelog/update-course-report
  includes/internal/emails/generators/class-course-teachers-trait.php
  includes/reports/overview/list-table/class-sensei-reports-overview-list-table-courses.php
  includes/reports/overview/services/class-sensei-reports-overview-service-courses.php
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
Labels: [Type] Maintenance, No Changelog

#6985 Enable feature flags for the front-end
  assets/blocks/course-outline/outline-block/outline-placeholder.js
  assets/blocks/course-outline/outline-block/outline-placeholder.test.js
  includes/blocks/class-sensei-course-blocks.php
  includes/class-sensei-feature-flags.php
  tests/unit-tests/test-class-lesson.php
  tests/unit-tests/test-class-sensei-feature-flags.php
  tests/unit-tests/test-class-sensei-learners-main.php
Labels: [Type] Maintenance, No Changelog, Course Outline AI
