Repository Automattic/sensei, pull requests merged in 2023-02, with the labels that each got.

#5814 Fix alignment of url buttons for Blockbase/Astra themes
  assets/blocks/course-list-block/course-list.scss
  includes/blocks/class-sensei-block-view-results.php
  includes/blocks/class-sensei-continue-course-block.php
  tests/unit-tests/blocks/test-class-sensei-block-view-results.php
  tests/unit-tests/blocks/test-class-sensei-continue-course-block.php
Labels: [Type] Bug

#6200 Auto select course template depending on selected course pattern
  assets/admin/editor-wizard/patterns-list.js
  assets/admin/editor-wizard/steps/patterns-step.js
Labels: Theme

#6454 Avoid running WordPress Dependencies Report on trunk
  .github/workflows/dependencies-report.yml
  .github/workflows/js.yml
Labels: [Type] Maintenance

#6436 Release 4.11.0
  assets/admin/students/student-action-menu/index.js
  assets/admin/students/student-bulk-action-button/index.js
  changelog.txt
  includes/admin/class-sensei-setup-wizard-pages.php
  includes/blocks/course-list/class-sensei-course-list-filter-block.php
  includes/class-sensei-course.php
  includes/class-sensei-db-query-learners.php
  includes/class-sensei-guest-user.php
  includes/class-sensei-preview-user.php
  includes/class-sensei-quiz.php
  includes/class-sensei-temporary-user-cleaner.php
  includes/class-sensei-temporary-user.php
  includes/class-sensei-usage-tracking-data.php
  includes/class-sensei-utils.php
  includes/internal/student-progress/course-progress/repositories/class-comments-based-course-progress-repository.php
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
  templates/archive-course.php
  tests/unit-tests/internal/student-progress/course-progress/repositories/test-class-comments-based-course-progress-repository.php
Labels: [Type] Maintenance

#6462 Remove unused axios dependency
  package-lock.json
  package.json
Labels: [Type] Maintenance

#6484 Fix type error when `the_content` is not a string
  includes/blocks/course-theme/class-course-content.php
  includes/class-sensei-notices.php
Labels: [Type] Bug

#6486 Release 4.11.1
  changelog.txt
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
Labels: [Type] Maintenance

#6487 Add email post type
  .github/workflows/e2e.yml
  includes/class-sensei-autoloader.php
  includes/class-sensei-feature-flags.php
  includes/class-sensei.php
  includes/internal/emails/class-email-post-type.php
  tests/unit-tests/internal/emails/test-class-email-post-type.php
  tests/unit-tests/test-class-sensei-feature-flags.php
Labels: [Type] Enhancement, Email Customization

#6494 Replace email settings with post type list when feature enabled
  assets/js/settings.js
  includes/class-sensei-admin.php
  includes/class-sensei-autoloader.php
  includes/class-sensei-settings-api.php
  includes/class-sensei-settings.php
  includes/class-sensei.php
  includes/internal/emails/class-email-customization.php
  includes/internal/emails/class-email-settings-tab.php
  includes/internal/emails/class-settings-menu.php
  tests/unit-tests/internal/emails/test-class-email-customization.php
  tests/unit-tests/internal/emails/test-class-email-settings-tab.php
  tests/unit-tests/internal/emails/test-class-settings-menu.php
Labels: [Type] Enhancement, Hooks

#6500 Fix badge style in settings
  includes/class-sensei-settings.php
Labels: [Type] Enhancement

#6511 Add submenu for email settings
  includes/internal/emails/class-email-settings-tab.php
Labels: [Type] Enhancement

#6505 Add the email list tables
  includes/class-sensei-autoloader.php
  includes/internal/emails/class-email-list-table.php
  includes/internal/emails/class-email-settings-tab.php
  tests/framework/factories/class-sensei-factory.php
  tests/framework/factories/class-sensei-unittest-factory-for-email.php
  tests/unit-tests/internal/emails/test-class-email-list-table.php
  tests/unit-tests/internal/emails/test-class-email-settings-tab.php
Labels: Hooks

#6507 Fix sprintf issue reported in 4673
  includes/data-port/class-sensei-import-job-cli.php
Labels: [Type] Bug, [Type] Good First Bug

#6519 Set the list of allowed blocks for email templates
  includes/class-sensei-autoloader.php
  includes/internal/emails/class-email-blocks.php
  includes/internal/emails/class-email-customization.php
  tests/unit-tests/internal/emails/test-class-email-blocks.php
Labels: Email Customization

#5696 Add changelogger
  .github/actions/deepen-to-merge-base/action.yml
  .github/actions/install-php/action.yml
  .github/workflows/changelogger.yml
  changelog.txt
  changelog/.gitkeep
  changelog/add-changelogger
  composer.json
  composer.lock
  includes/class-sensei-updates.php
  phpcs.xml.dist
  readme.txt
  scripts/check-changelogger-use.php
  tests/unit-tests/test-class-sensei-updates.php
Labels: [Type] Maintenance

#6533 Send email using GB template replacing placeholders to teacher on course start
  changelog/add-send-email-to-teacher-on-course-start
  composer.json
  composer.lock
  includes/class-sensei-autoloader.php
  includes/class-sensei.php
  includes/internal/emails/class-email-customization.php
  includes/internal/emails/class-email-generator.php
  includes/internal/emails/class-email-sender.php
  templates/emails/block-email-template.php
  tests/unit-tests/internal/emails/test-class-email-generator.php
  tests/unit-tests/internal/emails/test-class-email-sender.php
Labels: Hooks, Email Customization

#6527 Fix spacing issues on Emails settings page
  assets/css/admin-custom.scss
  changelog/adjust-email-list-spacing
  includes/class-sensei-settings-api.php
  includes/class-sensei-settings.php
  includes/internal/emails/class-email-settings-tab.php
  tests/unit-tests/internal/emails/test-class-email-settings-tab.php
Labels: Hooks, Email Customization

#6518 Auto select specific template for pattern at course creation if specified
  includes/block-patterns/course/life-coach.php
  includes/block-patterns/course/long-sales-page.php
  includes/block-patterns/course/video-hero.php
Labels: Theme

#6543 Handle block editors with no post in email block class
  changelog/add-handle-block-editors-with-no-post
  includes/internal/emails/class-email-blocks.php
  tests/unit-tests/internal/emails/test-class-email-blocks.php
Labels: Email Customization

#6546 Fix hook docs failing
  includes/internal/emails/class-email-generator.php
  includes/internal/emails/class-email-sender.php
Labels: [Type] Maintenance, No Changelog

#6520 Add enable/disable actions to the email list table
  assets/css/admin-custom.scss
  changelog/add-email-disabling
  includes/class-sensei-autoloader.php
  includes/class-sensei-list-table.php
  includes/internal/emails/class-email-customization.php
  includes/internal/emails/class-email-list-table-actions.php
  includes/internal/emails/class-email-list-table.php
  tests/bootstrap.php
  tests/framework/exceptions/class-sensei-wp-redirect-exception.php
  tests/framework/trait-sensei-test-redirect-helpers.php
  tests/unit-tests/course-theme/test-class-sensei-course-theme.php
  tests/unit-tests/internal/emails/test-class-email-list-table-actions.php
  tests/unit-tests/internal/emails/test-class-email-list-table.php
  tests/unit-tests/test-class-quiz.php
  tests/unit-tests/test-class-sensei-messages.php
Labels: Hooks

#6549 Update node + npm version
  .github/workflows/build-docs.yml
  .github/workflows/build.yml
  .github/workflows/code-coverage.yml
  .github/workflows/dependencies-report.yml
  .github/workflows/e2e.yml
  .github/workflows/js.yml
  assets/blocks/course-categories-block/course-categories-edit.js
  assets/blocks/course-categories-block/utils/style.test.js
  assets/blocks/course-list-block/featured-label/index.test.js
  assets/blocks/course-outline/module-block/module-edit.js
  package-lock.json
  package.json
Labels: [Type] Maintenance, No Changelog

#6553 Update the nvm node version
  .nvmrc
Labels: [Type] Maintenance, No Changelog

#6548 Setup email templates
  changelog/add-email-templates-setup
  includes/class-sensei-autoloader.php
  includes/class-sensei-updates.php
  includes/internal/emails/class-email-customization.php
  includes/internal/emails/class-email-data.php
  includes/internal/emails/class-email-list-table.php
  includes/internal/emails/class-email-repository.php
  includes/internal/emails/class-recreate-emails-tool.php
  includes/internal/emails/class-template-wizard.php
  tests/unit-tests/internal/emails/test-class-email-list-table.php
  tests/unit-tests/internal/emails/test-class-email-settings-tab.php
Labels: [Type] Enhancement, Email Customization

#6523 Add Email settings form
  changelog/add-email-settings
  includes/class-sensei.php
  includes/internal/emails/class-email-customization.php
  includes/internal/emails/class-email-settings-tab.php
  includes/internal/emails/views/html-settings.php
  tests/unit-tests/internal/emails/test-class-email-customization.php
  tests/unit-tests/internal/emails/test-class-email-settings-tab.php
Labels: [Type] Enhancement

#6542 Update pull request template to include pre-merge checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [Type] Maintenance, No Changelog

#6552 Add bulk email actions
  changelog/add-bulk-email-actions
  includes/class-sensei-list-table.php
  includes/internal/emails/class-email-list-table-actions.php
  includes/internal/emails/class-email-list-table.php
  tests/unit-tests/internal/emails/test-class-email-list-table-actions.php
  tests/unit-tests/internal/emails/test-class-email-list-table.php
Labels: Email Customization

#6557 Add reply to setting for email and email type input
  changelog/add-reply-to-setting-for-email
  includes/class-sensei-settings-api.php
  includes/class-sensei-settings.php
  includes/internal/emails/class-email-settings-tab.php
  tests/unit-tests/internal/emails/test-class-email-settings-tab.php
Labels: Email Customization

#6558 Remove align wide setting from blocks in GB editor for email post type
  assets/blocks/email-editor.js
  assets/blocks/email-editor.test.js
  changelog/add-remove-wide-width-setting-from-email-block
Labels: Email Customization

#6559 Disable relative css units for email templates
  includes/internal/emails/class-email-blocks.php
  tests/unit-tests/internal/emails/test-class-email-blocks.php
Labels: Email Customization, No Changelog

#6560 Add tests for email templates setup
  changelog/update-tests-for-email-templates-setup
  includes/class-sensei-autoloader.php
  includes/class-sensei-updates.php
  includes/internal/emails/class-email-customization.php
  includes/internal/emails/class-email-generator.php
  includes/internal/emails/class-email-list-table.php
  includes/internal/emails/class-email-repository.php
  includes/internal/emails/class-email-seeder-data.php
  includes/internal/emails/class-email-seeder.php
  includes/internal/emails/class-email-sender.php
  includes/internal/emails/class-email-settings-tab.php
  includes/internal/emails/class-recreate-emails-tool.php
  tests/unit-tests/internal/emails/test-class-email-generator.php
  tests/unit-tests/internal/emails/test-class-email-list-table.php
  tests/unit-tests/internal/emails/test-class-email-repository.php
  tests/unit-tests/internal/emails/test-class-email-seeder-data.php
  tests/unit-tests/internal/emails/test-class-email-seeder.php
  tests/unit-tests/internal/emails/test-class-email-sender.php
  tests/unit-tests/internal/emails/test-class-email-settings-tab.php
  tests/unit-tests/internal/emails/test-class-recreate-emails-tool.php
  tests/unit-tests/internal/emails/test-class-settings-menu.php
Labels: [Type] Maintenance

#6567 Send email to teacher when a student completes a course
  changelog/add-course-complete-mail
  includes/class-sensei-autoloader.php
  includes/internal/emails/class-email-blocks.php
  includes/internal/emails/class-email-customization.php
  includes/internal/emails/class-email-generator.php
  includes/internal/emails/class-email-patterns.php
  includes/internal/emails/class-email-seeder-data.php
  includes/internal/emails/class-email-sender.php
  tests/unit-tests/internal/emails/test-class-email-customization.php
  tests/unit-tests/internal/emails/test-class-email-generator.php
  tests/unit-tests/internal/emails/test-class-email-patterns.php
  tests/unit-tests/internal/emails/test-class-email-sender.php
Labels: Email Customization

#6568 Update start course mail to use pattern, add pattern in seeder, disable legacy version
  includes/internal/emails/class-email-customization.php
  includes/internal/emails/class-email-generator.php
  includes/internal/emails/class-email-patterns.php
  includes/internal/emails/class-email-seeder-data.php
  tests/unit-tests/internal/emails/test-class-email-customization.php
  tests/unit-tests/internal/emails/test-class-email-generator.php
  tests/unit-tests/internal/emails/test-class-email-patterns.php
Labels: Email Customization, No Changelog

#6564 Update email hook name to match naming conventions
  changelog/update-hook-name
  includes/internal/emails/class-email-generator.php
  includes/internal/emails/class-email-sender.php
  tests/unit-tests/internal/emails/test-class-email-generator.php
  tests/unit-tests/internal/emails/test-class-email-sender.php
Labels: Hooks, Email Customization

#6569 Redirect to email listing from standard custom post type listing
  changelog/fix-redirect-to-email-list
  includes/internal/emails/class-email-post-type.php
  tests/unit-tests/internal/emails/test-class-email-post-type.php
Labels: [Type] Bug, Email Customization

#6577 Replace old hook name with new hook name in tests
  tests/unit-tests/internal/emails/test-class-email-generator.php
Labels: [Type] Maintenance, No Changelog
