Repository Automattic/sensei, pull requests merged in 2023-08, with the labels that each got.

#7048 Update `sensei_results_links` filter to include the learner's user ID
  changelog/add-profile-links-filter
  includes/class-sensei-course.php
Labels: Hooks

#7046 Pass tables based submission to delete all related grades
  changelog/fix-grades-duplicates
  includes/class-sensei-grading.php
  includes/internal/quiz-submission/grade/repositories/class-aggregate-grade-repository.php
  tests/unit-tests/internal/quiz-submission/grade/repositories/test-class-aggregate-grade-repository.php
Labels: [Project] Progress Storage

#7062 Fix E2E tests failing randomly due to login issues
  tests/e2e-playwright/helpers/context.ts
Labels: [Type] Maintenance, No Changelog

#7049 Add student progress migration
  changelog/add-data-migrator
  includes/class-sensei.php
  includes/internal/installer/class-migration.php
  includes/internal/installer/migrations/class-student-progress-migration.php
  includes/internal/student-progress/tools/class-migration-tool.php
  tests/unit-tests/internal/installer/migrations/test-class-student-progress-migration.php
  tests/unit-tests/internal/student-progress/tools/test-class-migration-tool.php
Labels: [Project] Progress Storage

#7014 Add CC/BCC fields for Sensei emails
  changelog/add-email-cc-bcc
  includes/class-sensei-settings-api.php
  includes/class-sensei-settings.php
  includes/class-sensei.php
  includes/internal/emails/class-email-sender.php
  includes/internal/emails/class-email-settings-tab.php
  tests/unit-tests/internal/emails/test-class-email-sender.php
  tests/unit-tests/internal/emails/test-class-email-settings-tab.php
  tests/unit-tests/test-class-sensei-settings-api.php
  tests/unit-tests/test-class-sensei-settings.php
Labels: [Status] Needs Documentation, Emails

#7058 Fix "View Results" button not working
  changelog/fix-view-results-button-not-working
  includes/blocks/class-sensei-block-view-results.php
  tests/unit-tests/blocks/test-class-sensei-block-view-results.php
Labels: [Type] Bug

#7084 Fix E2E tests failing on WP 6.3
  tests/e2e-playwright/pages/admin/post-type/index.ts
Labels: [Type] Maintenance, No Changelog

#6713 Add Release Preparation scripts
  includes/class-sensei.php
  package.json
  scripts/Dockerfile
  scripts/RELEASE.md
  scripts/changelog-unwrap-pr-links.sh
  scripts/release-pr-steps.sh
  scripts/release-pr.sh
  scripts/update-version.sh
Labels: [Type] Maintenance, No Changelog

#7057 Update supported WP version to 6.3
  .github/workflows/php.yml
  readme.txt
  sensei-lms.php
Labels: [Type] Maintenance, No Changelog

#7045 Fix lessons not using set template in fse themes
  changelog/fix-lesson-not-using-set-template-in-fse-themes
  includes/unsupported-theme-handlers/class-sensei-unsupported-theme-handler-cpt.php
  tests/framework/trait-sensei-file-system-helper.php
  tests/unit-tests/test-class-utils.php
  tests/unit-tests/unsupported-theme-handlers/test-class-sensei-unsupported-theme-handler-cpt.php
Labels: [Project] Frontend Improvements

#7091 Fix lessons not being saved when creating a course on the latest Gutenberg version
  assets/shared/structure/structure-store.js
  changelog/fix-lessons-not-saved-when-creating-course
Labels: [Type] Bug

#6804 Add the "Development" changelog section
  .editorconfig
  composer.json
Labels: [Type] Maintenance, No Changelog

#7056 Remove default template learning mode lesson
  includes/course-theme/class-sensei-course-theme-templates.php
  tests/unit-tests/course-theme/test-class-sensei-course-theme-templates.php
Labels: No Changelog, [Project] Frontend Improvements

#7082 Fix error when the module author user is deleted
  changelog/fix-error-when-module-author-does-not-exist
  includes/class-sensei-modules.php
  tests/unit-tests/test-class-modules.php
Labels: [Type] Bug

#7060 Add composer package scoping info to the contributing doc
  CONTRIBUTING.md
Labels: [Type] Maintenance, No Changelog

#7022 Add PHP syntax check CI workflow
  .github/workflows/build.yml
Labels: [Type] Maintenance, No Changelog

#7096 Release 4.16.1
  changelog.txt
  changelog/add-data-migrator
  changelog/add-email-cc-bcc
  changelog/add-profile-links-filter
  changelog/fix-duplicate-comment-section-in-fse-themes
  changelog/fix-error-when-module-author-does-not-exist
  changelog/fix-grades-duplicates
  changelog/fix-learning-mode-template-on-wpcom
  changelog/fix-lesson-button-colors
  changelog/fix-lesson-not-using-set-template-in-fse-themes
  changelog/fix-lessons-not-saved-when-creating-course
  changelog/fix-php81-deprecation-notice
  changelog/fix-view-results-button-not-working
  changelog/fix-wp-core-deprecation-messages
  includes/class-sensei-utils.php
  includes/class-sensei.php
  includes/course-theme/class-sensei-course-theme-templates.php
  includes/internal/emails/class-email-settings-tab.php
  includes/internal/installer/class-installer.php
  includes/internal/installer/class-migration.php
  includes/internal/installer/class-schema.php
  includes/internal/installer/class-updates-factory.php
  includes/internal/installer/migrations/class-student-progress-migration.php
  includes/internal/quiz-submission/answer/repositories/class-aggregate-answer-repository.php
  includes/internal/quiz-submission/answer/repositories/class-tables-based-answer-repository.php
  includes/internal/quiz-submission/grade/repositories/class-aggregate-grade-repository.php
  includes/internal/quiz-submission/grade/repositories/class-tables-based-grade-repository.php
  includes/internal/quiz-submission/submission/repositories/class-aggregate-submission-repository.php
  includes/internal/quiz-submission/submission/repositories/class-tables-based-submission-repository.php
  includes/internal/student-progress/course-progress/repositories/class-aggregate-course-progress-repository.php
  includes/internal/student-progress/course-progress/repositories/class-tables-based-course-progress-repository.php
  includes/internal/student-progress/lesson-progress/repositories/class-aggregate-lesson-progress-repository.php
  includes/internal/student-progress/lesson-progress/repositories/class-tables-based-lesson-progress-repository.php
  includes/internal/student-progress/quiz-progress/repositories/class-aggregate-quiz-progress-repository.php
  includes/internal/student-progress/quiz-progress/repositories/class-tables-based-quiz-progress-repository.php
  includes/internal/student-progress/services/class-course-deleted-handler.php
  includes/internal/student-progress/services/class-lesson-deleted-handler.php
  includes/internal/student-progress/services/class-quiz-deleted-handler.php
  includes/internal/student-progress/services/class-user-deleted-handler.php
  includes/internal/student-progress/tools/class-migration-tool.php
  includes/unsupported-theme-handlers/class-sensei-unsupported-theme-handler-cpt.php
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
Labels: [Type] Maintenance, No Changelog

#7099 Update package-lock.json
  package-lock.json
Labels: [Type] Maintenance, No Changelog

#7097 Add Psalm to Sensei
  composer.json
  composer.lock
  config/psalm/psalm-loader.php
  psalm.xml
Labels: [Type] Maintenance, No Changelog

#7105 Add Psalm workflow
  .github/workflows/psalm.yml
Labels: [Type] Maintenance, No Changelog

#7063 Fix extra empty header element echoing in course and lesson
  changelog/fix-extra-heading-fix-course-and-lesson
  includes/class-sensei-lesson.php
Labels: [Project] Frontend Improvements

#7087 Add header on quiz template on Learning Mode
  assets/css/sensei-course-theme/quiz.scss
  assets/css/sensei-course-theme/sidebar-mobile-menu.scss
  changelog/add-header-on-lm-quiz-template
  includes/course-theme/class-sensei-course-theme-templates.php
  tests/unit-tests/course-theme/test-class-sensei-course-theme-templates.php
  themes/sensei-course-theme/patterns/header.html
  themes/sensei-course-theme/templates/default/lesson.html
  themes/sensei-course-theme/templates/quiz.html
Labels: Learning Mode, [Project] Frontend Improvements

#7118 Quote path to allow spaces in it
  scripts/release-pr.sh
Labels: [Type] Maintenance, No Changelog

#7093 Update quiz navigation and title area in learning mode
  assets/course-theme/blocks/quiz-blocks/index.js
  assets/css/3rd-party/themes/course/learning-mode.scss
  assets/css/3rd-party/themes/course/quiz.scss
  assets/css/learning-mode-compat.scss
  assets/css/sensei-course-theme/quiz-compat.scss
  assets/css/sensei-course-theme/quiz.scss
  assets/css/sensei-course-theme/theme-fixes.scss
  changelog/add-change-quiz-design-learning-mode
  config/psalm/psalm-baseline.xml
  includes/blocks/course-theme/class-quiz-back-to-lesson.php
  includes/course-theme/class-sensei-course-theme.php
  themes/sensei-course-theme/templates/quiz.html
Labels: [Project] Frontend Improvements

#7059 Fix learning mode lesson button, image and featured video style in Course theme
  assets/css/3rd-party/themes/course/learning-mode.scss
  assets/css/sensei-course-theme/blocks/lesson-actions.scss
  assets/css/sensei-course-theme/buttons.scss
  changelog/fix-lm-button-padding-and-gap-style
Labels: [Project] Frontend Improvements

#7120 Fix creation of dynamic property
  changelog/fix-php8.0-dynamic-property
  config/psalm/psalm-baseline.xml
  includes/class-sensei-db-query-learners.php
  includes/class-sensei-lesson.php
  includes/class-sensei-posttypes.php
  includes/class-sensei-question.php
  includes/class-sensei-quiz.php
  includes/class-sensei-settings-api.php
  includes/class-sensei.php
  includes/data-port/models/class-sensei-import-question-model.php
  includes/shortcodes/class-sensei-shortcode-course-categories.php
  includes/shortcodes/class-sensei-shortcode-lesson-page.php
Labels: [Type] Bug, [Type] Maintenance

#7092 Add recurring migration job
  composer.json
  composer.lock
  config/psalm/psalm-loader.php
  includes/background-jobs/class-sensei-scheduler-action-scheduler.php
  includes/class-sensei.php
  includes/internal/action-scheduler/class-action-scheduler.php
  includes/internal/installer/migrations/class-student-progress-migration.php
  includes/internal/student-progress/jobs/class-migration-job-scheduler.php
  includes/internal/student-progress/jobs/class-migration-job.php
  includes/internal/student-progress/tools/class-migration-tool.php
  psalm.xml
  sensei-lms.php
  tests/bootstrap.php
  tests/framework/actionscheduler-mocks.php
  tests/unit-tests/background-jobs/test-class-sensei-scheduler-action-scheduler.php
  tests/unit-tests/internal/action-scheduler/test-class-action-scheduler.php
  tests/unit-tests/internal/student-progress/jobs/test-class-migration-job-scheduler.php
  tests/unit-tests/internal/student-progress/jobs/test-class-migration-job.php
  tests/unit-tests/internal/student-progress/tools/test-class-migration-tool.php
Labels: [Project] Progress Storage, No Changelog

#7130 Add an npm script to run e2e tests with Gutenberg
  package.json
  tests/e2e-playwright/config/global-setup.ts
Labels: [Type] Maintenance, No Changelog
