Repository Automattic/sensei, pull requests merged in 2023-05, with the labels that each got.

#6833 Update colors & typography for "Lesson (Learning Mode - Default)" template in the editor
  assets/css/learning-mode-compat.scss
  assets/css/sensei-course-theme/base.scss
  assets/css/sensei-course-theme/blocks/course-navigation.scss
  assets/css/sensei-course-theme/blocks/course-progress-bar.scss
  assets/css/sensei-course-theme/blocks/course-title.scss
  assets/css/sensei-course-theme/blocks/exit-course.scss
  assets/css/sensei-course-theme/blocks/lesson-module.scss
  assets/css/sensei-course-theme/buttons.scss
  assets/css/sensei-course-theme/editor.scss
  assets/css/sensei-course-theme/fixed-sidebar.scss
  assets/css/sensei-course-theme/notices.scss
  assets/css/sensei-course-theme/theme-fixes.scss
  assets/css/sensei-course-theme/ui-blocks.scss
Labels: Learning Mode, No Changelog

#6853 Fix missing link in Sensei plugin description.
  readme.txt
Labels: [Type] Maintenance, No Changelog

#6847 Improve README and CONTRIBUTING guide
  CONTRIBUTING.md
  README.md
Labels: [Type] Enhancement, No Changelog

#6850 Fix email page template link and layout issues
  assets/css/email-notifications/email-editor-style.scss
  changelog/fix-email-template-editor
  includes/course-theme/class-sensei-course-theme-editor.php
  includes/internal/emails/class-email-post-type.php
  tests/unit-tests/internal/emails/test-class-email-post-type.php
Labels: [Type] Bug, Email Customization

#6823 Fix blocks late initialization
  changelog/fix-blocks-late-initialization
  includes/blocks/class-sensei-blocks-initializer.php
  tests/unit-tests/blocks/test-class-sensei-blocks-initializer.php
  tests/unit-tests/blocks/test-class-sensei-course-outline-block.php
Labels: [Type] Bug, Learning Mode

#6858 Style lesson title in the editor to match the Lesson Learning Mode template
  assets/css/learning-mode-compat.scss
Labels: Learning Mode, No Changelog

#6828 Review learning mode default spacings
  assets/course-theme/blocks/course-navigation/index.js
  assets/course-theme/blocks/lesson-blocks/page-actions.block.json
  assets/css/learning-mode-compat.scss
  assets/css/sensei-course-theme/blocks/course-navigation.scss
  assets/css/sensei-course-theme/blocks/course-progress-bar.scss
  assets/css/sensei-course-theme/blocks/lesson-actions.scss
  assets/css/sensei-course-theme/buttons.scss
  assets/css/sensei-course-theme/content.scss
  assets/css/sensei-course-theme/editor.scss
  assets/css/sensei-course-theme/fixed-sidebar.scss
  assets/css/sensei-course-theme/global-styles.scss
  assets/css/sensei-course-theme/layout.scss
  assets/css/sensei-course-theme/mobile.scss
  assets/css/sensei-course-theme/sidebar-mobile-menu.scss
  assets/css/sensei-course-theme/ui-blocks.scss
  assets/icons/arrow-right.svg
  changelog/update-learning-mode-default-spacings
  includes/blocks/course-theme/class-lesson-actions.php
  includes/blocks/course-theme/class-page-actions.php
  themes/sensei-course-theme/templates/default/lesson.html
Labels: Learning Mode

#6855 Don't dispatch e-mails related to Temporary Users
  changelog/fix-email-guest-users
  includes/class-sensei-emails.php
  includes/class-sensei-guest-user.php
  includes/class-sensei-preview-user.php
  includes/class-sensei-temporary-user.php
  includes/internal/emails/class-email-sender.php
  tests/unit-tests/test-class-sensei-guest-user.php
  tests/unit-tests/test-class-sensei-preview-user.php
Labels: [Type] Bug

#6864 Update the location of the Course theme in config file
  .wp-env.json
Labels: [Type] Maintenance, No Changelog

#6857 Remove styles for lesson completion screen
  assets/css/learning-mode.4-0-2.scss
  assets/css/learning-mode.scss
  assets/css/sensei-course-theme/lesson-complete-transition.scss
  assets/css/sensei-course-theme/mobile.scss
Labels: Learning Mode, No Changelog

#6871 Load the Course Learning Mode style file only when the course theme is active
  assets/css/3rd-party/themes/course/learning-mode.scss
  includes/3rd-party/3rd-party.php
  includes/3rd-party/themes/course.php
  includes/3rd-party/themes/divi.php
  webpack.config.js
Labels: No Changelog

#6865 Fix standard theme spacing issues
  assets/css/sensei-course-theme/blocks/lesson-actions.scss
  assets/css/sensei-course-theme/buttons.scss
  assets/css/sensei-course-theme/editor.scss
  assets/css/sensei-course-theme/fixed-sidebar.scss
  assets/css/sensei-course-theme/notices.scss
  assets/css/sensei-course-theme/theme-fixes.scss
  themes/sensei-course-theme/templates/default/lesson.html
Labels: Learning Mode

#6876 Fix AI button border not being visible if learning mode not active
  assets/blocks/quiz/quiz.editor.scss
Labels: No Changelog

#6869 Fix global typography in the Course theme's default variation
  assets/course-theme/blocks/lesson-blocks/exit-course-button/exit-course-edit.js
  assets/course-theme/blocks/lesson-blocks/index.js
  assets/css/3rd-party/themes/course/learning-mode.scss
  assets/css/learning-mode-compat.scss
  assets/css/sensei-course-theme/blocks/course-navigation.scss
  assets/css/sensei-course-theme/blocks/exit-course.scss
  assets/css/sensei-course-theme/blocks/lesson-actions.scss
  includes/blocks/course-theme/class-exit-course.php
  includes/blocks/course-theme/class-lesson-actions.php
Labels: Learning Mode

#6878 Fix MailPoet error when running job
  changelog/fix-mailpoet-error
  includes/mailpoet/class-main.php
Labels: MailPoet Integration

#6854 Adjust course theme spacings and alignments
  assets/css/3rd-party/themes/course/learning-mode.scss
  assets/css/learning-mode-compat.scss
  assets/css/learning-mode.scss
  assets/css/sensei-course-theme/base.scss
  assets/css/sensei-course-theme/blocks/course-navigation.scss
  assets/css/sensei-course-theme/buttons.scss
  assets/css/sensei-course-theme/content.scss
  assets/css/sensei-course-theme/mobile.scss
Labels: Learning Mode

#6904 Fix learning mode premium template mobile lateral spacing in mobile view
  assets/css/sensei-course-theme/content.scss
  assets/css/sensei-course-theme/mobile.scss
Labels: Learning Mode, No Changelog

#6905 Fix email body rendered in the front-end in some cases
  changelog/fix-rendering-the-email-body
  includes/internal/emails/class-email-sender.php
  tests/unit-tests/internal/emails/test-class-email-sender.php
Labels: [Type] Bug

#6903 Fix visibility for the course navigation
  assets/css/sensei-course-theme/sidebar-mobile-menu.scss
Labels: Learning Mode

#6883 Adjust spacings and alignment for Divi
  assets/css/3rd-party/themes/divi/learning-mode.editor.scss
  assets/css/3rd-party/themes/divi/learning-mode.scss
  assets/css/sensei-course-theme/mobile.scss
  includes/3rd-party/themes/divi.php
  webpack.config.js
Labels: No Changelog

#6910 Update Learning Mode Improvements feature branch from trunk
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .wp-env.json
  assets/blocks/quiz/quiz-block/quiz-edit.js
  assets/blocks/quiz/quiz-block/quiz-edit.test.js
  assets/blocks/quiz/quiz.editor.scss
  assets/course-theme/supports-color.js
  assets/css/admin-notices.scss
  assets/css/global.scss
  assets/css/learning-mode.4-0-2.scss
  assets/css/learning-mode.scss
  assets/css/sensei-course-theme/lesson-complete-transition.scss
  assets/css/sensei-course-theme/mobile.scss
  assets/css/senseilms-licensing.scss
  assets/home/notices.js
  assets/home/notices.scss
  assets/icons/ai-icon.svg
  assets/js/admin/lesson-ai.js
  assets/js/admin/lesson-ai.test.js
  assets/js/grading-general.js
  changelog.txt
  changelog/change-svg-xlink-href-to-href
  changelog/fix-auto-grading
  changelog/fix-divi-error-on-video-template
  changelog/fix-email-template-creation
  changelog/fix-email-template-editor
  changelog/fix-mailpoet-error
  changelog/fix-rendering-the-email-body
  changelog/fix-wpmail-temporary-users
  changelog/pr-6631
  changelog/remove-layout-calls
  includes/admin/class-sensei-admin-notices.php
  includes/admin/class-sensei-extensions.php
  includes/admin/class-senseilms-plugin-updater.php
  includes/admin/home/notices/class-sensei-home-notices-provider.php
  includes/admin/home/notices/class-sensei-home-notices.php
  includes/admin/views/html-admin-page-home.php
  includes/class-sensei-emails.php
  includes/class-sensei-guest-user.php
  includes/class-sensei-lesson.php
  includes/class-sensei-preview-user.php
  includes/class-sensei-temporary-user.php
  includes/class-sensei.php
  includes/internal/emails/class-email-post-type.php
  includes/internal/emails/class-email-repository.php
  includes/internal/emails/class-email-sender.php
  includes/mailpoet/class-main.php
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
  tests/unit-tests/admin/test-class-sensei-admin-notices.php
  tests/unit-tests/internal/emails/test-class-email-repository.php
  tests/unit-tests/internal/emails/test-class-email-sender.php
  tests/unit-tests/test-class-sensei-guest-user.php
  tests/unit-tests/test-class-sensei-preview-user.php
  webpack.config.js
Labels: [Type] Maintenance, Learning Mode

#6919 Fix lateral spacing on learning mode and Twenty Twenty-Three theme
  assets/css/3rd-party/themes/course/learning-mode.scss
  assets/css/sensei-course-theme/blocks/course-navigation.scss
  assets/css/sensei-course-theme/sidebar-mobile-menu.scss
Labels: Learning Mode

#6457 Remove multiple product list from course in Course List block
  includes/blocks/course-list/class-sensei-course-list-block.php
  tests/unit-tests/blocks/test-class-sensei-course-list-block.php
Labels: Blocks, No Changelog

#6922 Update learning mode template preview
  themes/sensei-course-theme/templates/default/img-full.jpg
  themes/sensei-course-theme/templates/default/img-thumb.jpg
  themes/sensei-course-theme/templates/modern/img-full.jpg
  themes/sensei-course-theme/templates/modern/img-thumb.jpg
  themes/sensei-course-theme/templates/video-full/img-full.jpg
  themes/sensei-course-theme/templates/video-full/img-thumb.jpg
  themes/sensei-course-theme/templates/video/img-full.jpg
  themes/sensei-course-theme/templates/video/img-thumb.jpg
Labels: Learning Mode

#6930 Use Fill button style when Complete Lesson button is the only action available
  includes/blocks/course-theme/class-lesson-actions.php
Labels: Learning Mode, No Changelog

#6920 Update the future minimum PHP version
  includes/class-sensei-dependency-checker.php
Labels: [Type] Maintenance, No Changelog

#6933 Hide message in body in Learning Mode
  assets/css/sensei-course-theme/notices.scss
Labels: Learning Mode
