Repository Automattic/sensei, pull requests merged in 2023-11, with the labels that each got.

#7250 Add text that "Don't allow self-enrollment" setting is not available for paid courses
  assets/js/admin/course-general-sidebar.js
Labels: No Changelog

#7252 Fix action buttons color matching background color making it not visible in Course theme
  assets/css/3rd-party/themes/course/learning-mode.scss
Labels: No Changelog

#7253 Release 4.19.0
  changelog.txt
  changelog/add-setting-not-allowing-self-enrollment
  changelog/fix-full-width-blocks-editor
  changelog/fix-take-course-notices
  changelog/remove-course-theme-hook
  changelog/update-awaiting-grade-notice
  changelog/update-graded-notice
  includes/class-sensei-analysis-overview-list-table.php
  includes/class-sensei-course.php
  includes/class-sensei-grading-main.php
  includes/internal/quiz-submission/answer/repositories/class-table-reading-aggregate-answer-repository.php
  includes/internal/quiz-submission/grade/repositories/class-table-reading-aggregate-grade-repository.php
  includes/internal/quiz-submission/submission/repositories/class-table-reading-aggregate-submission-repository.php
  includes/internal/tools/class-progress-tables-eraser.php
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
Labels: No Changelog

#7160 Add progress validation command
  includes/class-sensei-cli.php
  includes/class-sensei-course.php
  includes/cli/class-sensei-db-seed-command.php
  includes/cli/class-sensei-validate-progress-command.php
  includes/internal/migration/migrations/class-student-progress-migration.php
  includes/internal/migration/validations/class-progress-validation.php
  includes/internal/migration/validations/class-validation-error.php
  psalm.xml
  tests/unit-tests/internal/migration/migrations/test-class-student-progress-migration.php
  tests/unit-tests/internal/migration/migrations/validations/test-class-validation-error.php
  tests/unit-tests/internal/migration/migrations/validations/test-progress-validation.php
Labels: [Project] High-Performance Progress Storage, No Changelog

#7267 Add "[Status] Needs Triage" label to new issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: No Changelog

#7265 Fix editor player integration to support new editor canvas iframe
  assets/shared/helpers/player/use-editor-player.js
Labels: No Changelog

#7258 Fix email editor styles sneaking into other editors
  assets/css/email-notifications/email-editor-style.scss
  changelog/fix-email-editor-styles-sneaking-into-other-editors
Labels: [Project] Frontend Improvements

#7269 Release 4.19.1
  changelog.txt
  changelog/fix-email-editor-styles-sneaking-into-other-editors
  includes/cli/class-sensei-validate-progress-command.php
  includes/internal/migration/validations/class-progress-validation.php
  includes/internal/migration/validations/class-validation-error.php
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
Labels: No Changelog

#7251 Quiz submission validation CLI command
  includes/class-sensei-cli.php
  includes/cli/class-sensei-validate-progress-command.php
  includes/cli/class-sensei-validate-quiz-submission-command.php
  includes/internal/migration/validations/class-quiz-submission-validation.php
  tests/unit-tests/internal/migration/migrations/validations/test-class-progress-validation.php
  tests/unit-tests/internal/migration/migrations/validations/test-class-quiz-submission-validation.php
Labels: No Changelog

#7255 Add styles for quiz timer
  assets/css/sensei-course-theme/quiz.scss
  themes/sensei-course-theme/templates/quiz.html
Labels: No Changelog

#7279 Fix tests failing randomly
  includes/internal/tools/class-progress-tables-eraser.php
  tests/framework/factories/class-sensei-factory.php
  tests/unit-tests/internal/migration/migrations/validations/test-class-progress-validation.php
Labels: No Changelog

#7280 Add comment to use component only on the editor side
  assets/shared/blocks/single-line-input/single-line-input.js
Labels: No Changelog

#7224 Allow styling lesson action buttons in learning mode
  assets/blocks/lesson-action-blocks.js
  assets/blocks/lesson-actions/index.js
  assets/blocks/lesson-actions/lesson-actions-block/constants.js
  assets/blocks/lesson-actions/lesson-actions-block/index.js
  assets/blocks/lesson-actions/lesson-actions-block/lesson-actions-edit.js
  assets/blocks/lesson-actions/lesson-actions-block/lesson-actions-editor.scss
  assets/blocks/lesson-actions/lesson-completed-block/index.js
  assets/blocks/single-lesson.js
  assets/css/3rd-party/themes/astra/learning-mode.scss
  assets/css/3rd-party/themes/divi/learning-mode.scss
  assets/css/learning-mode-compat.scss
  assets/css/learning-mode.editor.scss
  assets/css/sensei-course-theme/content.scss
  changelog/add-learning-mode-lesson-actions-update
  includes/3rd-party/themes/astra.php
  includes/blocks/class-sensei-global-blocks.php
  includes/blocks/class-sensei-lesson-actions-block.php
  includes/blocks/class-sensei-lesson-blocks.php
  includes/blocks/class-sensei-lesson-completed-block.php
  includes/blocks/class-sensei-view-quiz-block.php
  includes/blocks/course-theme/class-course-theme-blocks.php
  includes/class-sensei-utils.php
  includes/course-theme/class-sensei-course-theme-template-selection.php
  includes/course-theme/class-sensei-course-theme-templates.php
  tests/e2e-playwright/pages/frontend/lesson.ts
  themes/sensei-course-theme/templates/default/lesson.html
  themes/sensei-course-theme/templates/default/lesson.php
  webpack.config.js
Labels: Learning Mode

#7282 Add a feature flag and experimental settings ui
  includes/class-sensei-feature-flags.php
  includes/class-sensei-settings.php
Labels: [Project] High-Performance Progress Storage, No Changelog

#7256 Add stylesheets for course theme variations
  assets/css/3rd-party/themes/course/blue.scss
  assets/css/3rd-party/themes/course/dark.scss
  assets/css/3rd-party/themes/course/default.scss
  assets/css/3rd-party/themes/course/gold.scss
  changelog/add-stylesheets-for-course-theme-variations
  includes/3rd-party/themes/course.php
  webpack.config.js
Labels: [Type] Enhancement

#7289 Migrate legacy quiz data
  changelog/update-migrate-quiz-answers
  config/psalm/psalm-baseline.xml
  includes/class-sensei-grading.php
  includes/class-sensei-quiz.php
  includes/class-sensei-updates.php
  includes/class-sensei-utils.php
  includes/update-tasks/class-sensei-update-legacy-quiz-data.php
  sensei-lms.php
  tests/unit-tests/test-class-quiz.php
  tests/unit-tests/test-class-sensei-utils.php
  tests/unit-tests/update-tasks/test-class-sensei-update-legacy-quiz-data.php
Labels: Performance, Deprecation, [Type] Technical Debt, [Project] High-Performance Progress Storage

#7268 Update footer styles in multi page quiz
  assets/css/3rd-party/themes/course/dark.scss
  assets/css/3rd-party/themes/course/learning-mode.scss
  assets/css/3rd-party/themes/course/quiz.scss
  assets/css/frontend.scss
  assets/css/learning-mode-compat.scss
  assets/css/sensei-course-theme/blocks/lesson-actions.scss
  assets/css/sensei-course-theme/buttons.scss
  assets/css/sensei-course-theme/content.scss
  assets/css/sensei-course-theme/notices.scss
  assets/css/sensei-course-theme/quiz-compat.scss
  assets/css/sensei-course-theme/quiz.scss
  changelog/fix-button-styles-for-multi-page-quiz
  includes/blocks/course-theme/class-lesson-actions.php
  templates/single-quiz/pagination.php
Labels: Learning Mode, [Project] Frontend Improvements

#7263 Fix not enrolled notice style in lm
  assets/css/3rd-party/themes/course/learning-mode.scss
  assets/css/sensei-course-theme/notices.scss
  changelog/fix-not-enrolled-notice-style-in-lm
  includes/course-theme/class-sensei-course-theme-lesson.php
  templates/course-theme/locked-lesson-notice.php
Labels: [Project] Frontend Improvements

#7285 Fix notice style for paid courses
  assets/css/3rd-party/themes/course/default.scss
  assets/css/3rd-party/themes/course/learning-mode.scss
Labels: No Changelog, [Project] Frontend Improvements

#7257 Fix contact teacher form not working in lm footer button
  changelog/fix-contact-teacher-form-not-working-in-lm-footer-button
  includes/class-sensei-quiz.php
  templates/course-theme/quiz-grade-notice.php
Labels: Learning Mode, [Project] Frontend Improvements

#7283 Add border styling ability for sensei buttons
  assets/blocks/button/color-hooks.js
  assets/blocks/button/color-props.js
  assets/blocks/button/index.js
  assets/course-theme/blocks/lesson-blocks/index.js
  assets/css/learning-mode-compat.scss
  changelog/add-border-styling-ability-for-action-buttons
  includes/blocks/course-theme/class-lesson-actions.php
Labels: Deprecation, [Project] Frontend Improvements

#7288 Fix contact teacher full width in learning mode
  assets/css/learning-mode-compat.scss
  changelog/fix-contact-teacher-full-width-in-learning-mode
Labels: [Project] Frontend Improvements

#7293 Use the quiz repository classes in the front-end
  includes/class-sensei-quiz.php
  includes/internal/student-progress/quiz-progress/models/class-quiz-progress-abstract.php
  includes/internal/student-progress/quiz-progress/models/class-quiz-progress-interface.php
  tests/unit-tests/internal/student-progress/quiz-progress/models/test-class-comments-based-quiz-progress.php
  tests/unit-tests/test-class-quiz.php
Labels: [Project] High-Performance Progress Storage, No Changelog

#7264 Fix notice style for not logged in users in learning mode
  assets/css/3rd-party/themes/course/default.scss
  assets/css/3rd-party/themes/course/learning-mode.scss
  assets/css/sensei-course-theme/notices.scss
  changelog/fix-not-logged-in-style-in-lm
  includes/course-theme/class-sensei-course-theme-lesson.php
  templates/course-theme/locked-lesson-notice.php
Labels: [Project] Frontend Improvements

#7284 Fix notices being displayed on the frontend
  changelog/fix-outline-notices
  includes/class-sensei-notices.php
  includes/class-sensei-utils.php
  tests/unit-tests/test-class-sensei-utils.php
Labels: [Type] Bug

#7294 Fix a deprecated notice related to the quiz progress
  changelog/fix-deprecation-notice
  includes/internal/student-progress/quiz-progress/repositories/class-comments-based-quiz-progress-repository.php
Labels: [Type] Bug, [Project] High-Performance Progress Storage

#7310 Fix error on the setup wizard
  includes/class-sensei-settings.php
Labels: [Type] Bug, [Project] High-Performance Progress Storage, No Changelog

#7313 Release 4.19.2
  changelog.txt
  changelog/add-border-styling-ability-for-action-buttons
  changelog/add-learning-mode-lesson-actions-update
  changelog/add-stylesheets-for-course-theme-variations
  changelog/change-no-published-lessons-message
  changelog/fix-button-styles-for-multi-page-quiz
  changelog/fix-contact-teacher-form-not-working-in-lm-footer-button
  changelog/fix-contact-teacher-full-width-in-learning-mode
  changelog/fix-deprecation-notice
  changelog/fix-distorting-site-logo
  changelog/fix-gap-fill-question-with-answer-0
  changelog/fix-module-style
  changelog/fix-not-enrolled-notice-style-in-lm
  changelog/fix-not-logged-in-style-in-lm
  changelog/fix-outline-notices
  changelog/fix-pending-teacher-button-full-width
  changelog/fix-quiz-complete-status
  changelog/update-migrate-quiz-answers
  includes/3rd-party/themes/course.php
  includes/blocks/class-sensei-lesson-completed-block.php
  includes/blocks/course-theme/class-lesson-actions.php
  includes/class-sensei-settings.php
  includes/class-sensei-updates.php
  includes/class-sensei-utils.php
  includes/cli/class-sensei-validate-quiz-submission-command.php
  includes/internal/installer/class-schema.php
  includes/internal/migration/validations/class-quiz-submission-validation.php
  includes/update-tasks/class-sensei-update-legacy-quiz-data.php
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
  themes/sensei-course-theme/templates/default/lesson.php
Labels: No Changelog

#7319 Release 4.19.2
  changelog.txt
  changelog/fix-dropdown-menu-icon-size
  changelog/fix-gutenberg-compat-fix
  lang/sensei-lms.pot
  readme.txt
Labels: No Changelog

#7295 Add a repository selection settings UI
  assets/js/admin/settings/experimental-features.js
  includes/class-sensei-settings.php
  webpack.config.js
Labels: [Project] High-Performance Progress Storage, No Changelog

#7298 Take progress storage repository setting into account
  includes/class-sensei-settings.php
  includes/class-sensei.php
Labels: [Project] High-Performance Progress Storage, No Changelog

#7309 Handle synchronization option change
  assets/js/admin/settings/experimental-features.js
  includes/class-sensei-settings.php
  includes/class-sensei.php
  includes/internal/installer/class-eraser.php
  includes/internal/migration/class-migration-job-scheduler.php
  includes/internal/migration/migrations/class-student-progress-migration.php
  includes/internal/tools/class-progress-tables-eraser.php
  tests/unit-tests/internal/installer/test-class-eraser.php
  tests/unit-tests/internal/migration/test-class-migration-job-scheduler.php
  tests/unit-tests/test-class-sensei.php
Labels: [Project] High-Performance Progress Storage, No Changelog

#7314 Enable erase tables tool when the feature is enabled, but tables not in use
  includes/class-sensei.php
  includes/internal/tools/class-progress-tables-eraser.php
  tests/unit-tests/internal/tools/test-class-progress-tables-eraser.php
Labels: [Project] High-Performance Progress Storage, No Changelog

#7315 Remove HPPS migration tool
  includes/class-sensei.php
  includes/internal/migration/class-migration-tool.php
  tests/unit-tests/internal/migration/test-class-migration-tool.php
Labels: [Project] High-Performance Progress Storage, No Changelog

#7329 Fix deprecation notice when doing HPPS migration
  includes/internal/student-progress/course-progress/repositories/class-comments-based-course-progress-repository.php
  includes/internal/student-progress/lesson-progress/repositories/class-comments-based-lesson-progress-repository.php
  includes/internal/student-progress/quiz-progress/repositories/class-comments-based-quiz-progress-repository.php
Labels: [Type] Bug, [Project] High-Performance Progress Storage, No Changelog

#7328 Ignore existing rows while migrating quiz data
  includes/internal/migration/migrations/class-quiz-migration.php
Labels: [Project] High-Performance Progress Storage, No Changelog

#7325 Log important HPPS events
  includes/class-sensei-settings.php
  includes/internal/migration/class-migration-job-scheduler.php
  includes/lib/usage-tracking/class-usage-tracking-base.php
  tests/unit-tests/internal/migration/test-class-migration-job-scheduler.php
  tests/unit-tests/test-class-sensei-settings.php
  tests/unit-tests/test-class-sensei-usage-tracking.php
Labels: [Project] High-Performance Progress Storage, No Changelog

#7333 Set infinite time limit for migration jobs
  assets/js/admin/settings/experimental-features.js
  includes/class-sensei-settings.php
  includes/internal/migration/class-migration-job-scheduler.php
Labels: [Project] High-Performance Progress Storage, No Changelog
