Repository Automattic/sensei, pull requests merged in 2023-12, with the labels that each got.

#7354 Protect dependent HPPS settings from changing too early
  assets/js/admin/settings/experimental-features.js
  includes/class-sensei-settings.php
  includes/class-sensei.php
Labels: [Project] High-Performance Progress Storage, No Changelog

#7343 Add helper functions for HPPS settings
  assets/js/admin/settings/experimental-features.js
  includes/class-sensei-settings.php
  includes/class-sensei.php
  includes/internal/migration/class-migration-job-scheduler.php
  includes/internal/services/class-progress-storage-settings.php
  includes/internal/tools/class-progress-tables-eraser.php
  includes/lib/usage-tracking/class-usage-tracking-base.php
  tests/unit-tests/internal/migration/test-class-migration-job-scheduler.php
  tests/unit-tests/internal/services/test-class-progress-storage-settings.php
  tests/unit-tests/test-class-sensei-settings.php
Labels: [Project] High-Performance Progress Storage, No Changelog

#7338 Output logs for failed migration jobs
  assets/js/admin/settings/experimental-features.js
  includes/class-sensei-settings.php
  includes/class-sensei.php
  includes/internal/action-scheduler/class-action-scheduler.php
  includes/internal/migration/class-migration-job-scheduler.php
  includes/internal/services/class-progress-storage-settings.php
  includes/internal/tools/class-progress-tables-eraser.php
  includes/lib/usage-tracking/class-usage-tracking-base.php
  tests/framework/actionscheduler-mocks.php
  tests/unit-tests/internal/action-scheduler/test-class-action-scheduler.php
  tests/unit-tests/internal/migration/test-class-migration-job-scheduler.php
  tests/unit-tests/internal/services/test-class-progress-storage-settings.php
  tests/unit-tests/test-class-sensei-settings.php
Labels: [Project] High-Performance Progress Storage, No Changelog

#7344 Open the Lesson editor in same tab when Edit Lesson link is clicked in the Course Outline block
  assets/blocks/course-outline/course-outline-editor.scss
  assets/blocks/course-outline/lesson-block/lesson-edit-toolbar.js
  changelog/add-open-lesson-editor-in-same-tab
Labels: [Project] Onboarding Flow

#7369 Fix CI failing because of npm version requirement
  package-lock.json
  package.json
Labels: No Changelog

#7342 Enable showing frontend style notice in backend
  assets/css/admin-notices.scss
  assets/css/notices.scss
  assets/css/pages-frontend.scss
Labels: No Changelog

#7377 Fix restart quiz redirects to the course complete page if the course was completed
  changelog/fix-redirect-reset-quiz
  includes/class-sensei-quiz.php
  includes/class-sensei-utils.php
  tests/unit-tests/test-class-quiz.php
Labels: [Type] Bug

#7361 Fix importer not finding existing users if their username is different
  changelog/fix-importer-user-not-found
  includes/data-port/class-sensei-data-port-utilities.php
  tests/unit-tests/data-port/test-class-sensei-data-port-utilites.php
Labels: [Type] Bug

#7372 Show one generic message in case HPPS functionality is disabled
  includes/class-sensei-settings.php
Labels: [Project] High-Performance Progress Storage, No Changelog

#7367 Fix teacher can see all students on the Students screen
  changelog/fix-teacher-can-see-all-students
  includes/class-sensei-teacher.php
  includes/class-sensei-temporary-user.php
  tests/bootstrap.php
  tests/framework/trait-sensei-hpps-helpers.php
  tests/unit-tests/test-class-sensei-db-query-learners.php
  tests/unit-tests/test-class-teacher.php
Labels: [Type] Bug

#7390 Release 4.20.0
  changelog.txt
  changelog/add-open-lesson-editor-in-same-tab
  changelog/fix-continue-course-block-redirect-using-plain-permalinks
  changelog/fix-importer-user-not-found
  changelog/fix-non-learning-mode-template-styles
  changelog/fix-pattern-preview-styles
  changelog/fix-redirect-reset-quiz
  changelog/fix-take-quiz-button-not-visible-gutenberg
  changelog/fix-teacher-can-see-all-students
  changelog/update-course-list-patterns
  changelog/update-rename-block
  includes/class-sensei-feature-flags.php
  includes/class-sensei-settings.php
  includes/class-sensei-teacher.php
  includes/internal/action-scheduler/class-action-scheduler.php
  includes/internal/installer/class-eraser.php
  includes/internal/migration/class-migration-job-scheduler.php
  includes/internal/services/class-progress-storage-settings.php
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
  tests/framework/trait-sensei-hpps-helpers.php
Labels: No Changelog

#7397 Add is_wpcom property in event log
  includes/class-sensei-usage-tracking-data.php
Labels: No Changelog, [Project] Onboarding Flow

#7393 Make customize template task point to Learning Mode template
  changelog/add-update-customize-template-task
  includes/admin/home/tasks/task/class-sensei-home-task-customize-course-theme.php
  includes/class-sensei-admin.php
  includes/course-theme/class-sensei-course-theme.php
  tests/unit-tests/admin/home/tasks/task/test-class-sensei-home-task-customize-course-theme.php
Labels: [Project] Onboarding Flow

#7402 Set email template only for sensei_email post type
  changelog/fix-email-template-switch
  includes/internal/emails/class-email-page-template.php
  tests/unit-tests/internal/emails/test-class-email-page-template.php
Labels: [Type] Bug, Emails

#7405 Don't send Course Completion email twice (course already complete)
  changelog/fix-course-completion-email-duplicates
  includes/class-sensei-utils.php
  includes/internal/emails/generators/class-course-completed.php
  tests/unit-tests/internal/emails/generators/test-class-course-completed.php
  tests/unit-tests/test-class-sensei-utils.php
Labels: [Type] Bug, Hooks, Emails

#7407 Add legacy course test to the PR checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: No Changelog
