Repository Automattic/sensei, pull requests merged in 2023-09, with the labels that each got.

#7143 Fix changelog category names
  composer.json
Labels: [Type] Maintenance, No Changelog

#7140 Create tables-based versions of student progress and quiz data when saving of their comment based versions
  includes/internal/quiz-submission/answer/repositories/class-aggregate-answer-repository.php
  includes/internal/quiz-submission/grade/repositories/class-aggregate-grade-repository.php
  includes/internal/quiz-submission/grade/repositories/class-grade-repository-factory.php
  includes/internal/quiz-submission/submission/repositories/class-aggregate-submission-repository.php
  includes/internal/student-progress/course-progress/repositories/class-aggregate-course-progress-repository.php
  includes/internal/student-progress/lesson-progress/repositories/class-aggregate-lesson-progress-repository.php
  includes/internal/student-progress/quiz-progress/repositories/class-aggregate-quiz-progress-repository.php
  tests/unit-tests/internal/migration/test-class-migration-tool.php
  tests/unit-tests/internal/quiz-submission/answer/repositories/test-class-aggregate-answer-repository.php
  tests/unit-tests/internal/quiz-submission/grade/repositories/test-class-aggregate-grade-repository.php
  tests/unit-tests/internal/quiz-submission/grade/repositories/test-class-grade-repository-factory.php
  tests/unit-tests/internal/quiz-submission/submission/repositories/test-class-aggregate-submission-repository.php
  tests/unit-tests/internal/student-progress/course-progress/repositories/test-class-aggregate-course-progress-repository.php
  tests/unit-tests/internal/student-progress/lesson-progress/repositories/test-class-aggregate-lesson-progress-repository.php
  tests/unit-tests/internal/student-progress/quiz-progress/repositories/test-class-aggregate-quiz-progress-repository.php
  tests/unit-tests/test-class-quiz.php
Labels: [Project] Progress Storage, No Changelog

#7148 Add constant for disabling Action Scheduler loading
  includes/class-sensei.php
  sensei-lms.php
Labels: [Project] Progress Storage, No Changelog

#7106 Footer style improvements for quiz on learning mode
  assets/css/3rd-party/themes/course/quiz.scss
  assets/css/frontend.scss
  assets/css/sensei-course-theme/buttons.scss
  assets/css/sensei-course-theme/quiz.scss
  changelog/add-footer-style-update-lm-quiz
  includes/class-sensei-quiz.php
Labels: [Project] Frontend Improvements

#7124 Learning mode - Change all question styles for quiz page
  assets/blocks/quiz/answer-blocks/file-upload.js
  assets/blocks/quiz/answer-blocks/multi-line.js
  assets/blocks/quiz/question-answers-block/block.json
  assets/blocks/quiz/question-answers-block/question-answers.js
  assets/blocks/quiz/question-block/block.json
  assets/blocks/quiz/question-block/question-block.editor.scss
  assets/blocks/quiz/question-block/question-edit.js
  assets/blocks/quiz/question-block/question.scss
  assets/blocks/quiz/question-description-block/block.json
  assets/blocks/quiz/question-description-block/question-description.js
  assets/blocks/quiz/quiz-block/block.json
  assets/blocks/quiz/quiz-block/quiz-edit.js
  assets/blocks/quiz/quiz-block/quiz-edit.test.js
  assets/course-theme/learning-mode.js
  assets/css/3rd-party/themes/course/learning-mode.scss
  assets/css/3rd-party/themes/course/questions.scss
  assets/css/3rd-party/themes/course/quiz.scss
  assets/css/frontend.scss
  assets/css/question-answer-tinymce-editor.css
  assets/css/sensei-course-theme/content.scss
  assets/css/sensei-course-theme/quiz-compat.scss
  assets/css/sensei-course-theme/quiz.scss
  assets/js/file-upload-question-type.js
  assets/js/question-answer-tinymce-editor.js
  changelog/add-change-all-question-styles
  includes/blocks/course-theme/class-quiz-content.php
  includes/class-sensei-question.php
  includes/class-sensei-utils.php
  includes/template-functions.php
  psalm.xml
  templates/single-quiz.php
  templates/single-quiz/question-type-boolean.php
  templates/single-quiz/question-type-file-upload.php
  templates/single-quiz/question-type-multiple-choice.php
  templates/single-quiz/question-type-single-line.php
  webpack.config.js
Labels: [Project] Frontend Improvements

#7156 Rename the 'dev' changelog section to 'development'
  composer.json
Labels: [Type] Maintenance, No Changelog

#7162 Fix attempt to create quiz progress in the tables when the feature is disabled
  includes/class-sensei-quiz.php
  tests/unit-tests/test-class-quiz.php
Labels: [Type] Bug, [Project] Progress Storage, No Changelog

#7142 Read student progress from custom tables
  includes/class-sensei-quiz.php
  includes/class-sensei.php
  includes/data-port/import-tasks/class-sensei-import-file-process-task.php
  includes/internal/student-progress/course-progress/repositories/class-comment-reading-aggregate-course-progress-repository.php
  includes/internal/student-progress/course-progress/repositories/class-course-progress-repository-factory.php
  includes/internal/student-progress/course-progress/repositories/class-table-reading-aggregate-course-progress-repository.php
  includes/internal/student-progress/lesson-progress/repositories/class-comment-reading-aggregate-lesson-progress-repository.php
  includes/internal/student-progress/lesson-progress/repositories/class-lesson-progress-repository-factory.php
  includes/internal/student-progress/lesson-progress/repositories/class-table-reading-aggregate-lesson-progress-repository.php
  includes/internal/student-progress/quiz-progress/repositories/class-comment-reading-aggregate-quiz-progress-repository.php
  includes/internal/student-progress/quiz-progress/repositories/class-quiz-progress-repository-factory.php
  includes/internal/student-progress/quiz-progress/repositories/class-table-reading-aggregate-quiz-progress-repository.php
  psalm.xml
  tests/unit-tests/internal/migration/test-class-migration-tool.php
  tests/unit-tests/internal/student-progress/course-progress/repositories/test-class-comment-reading-aggregate-course-progress-repository.php
  tests/unit-tests/internal/student-progress/course-progress/repositories/test-class-course-progress-repository-factory.php
  tests/unit-tests/internal/student-progress/course-progress/repositories/test-class-table-reading-aggregate-course-progress-repository.php
  tests/unit-tests/internal/student-progress/lesson-progress/repositories/test-class-comment-reading-aggregate-lesson-progress-repository.php
  tests/unit-tests/internal/student-progress/lesson-progress/repositories/test-class-lesson-progress-repository-factory.php
  tests/unit-tests/internal/student-progress/lesson-progress/repositories/test-class-table-reading-aggregate-lesson-progress-repository.php
  tests/unit-tests/internal/student-progress/quiz-progress/repositories/test-class-comment-reading-aggregate-quiz-progress-repository.php
  tests/unit-tests/internal/student-progress/quiz-progress/repositories/test-class-quiz-progress-repository-factory.php
  tests/unit-tests/internal/student-progress/quiz-progress/repositories/test-class-table-reading-aggregate-quiz-progress-repository.php
Labels: [Project] Progress Storage, No Changelog

#7163 Feature frontend improvements
  assets/blocks/quiz/answer-blocks/file-upload.js
  assets/blocks/quiz/answer-blocks/multi-line.js
  assets/blocks/quiz/question-answers-block/block.json
  assets/blocks/quiz/question-answers-block/question-answers.js
  assets/blocks/quiz/question-block/block.json
  assets/blocks/quiz/question-block/question-block.editor.scss
  assets/blocks/quiz/question-block/question-edit.js
  assets/blocks/quiz/question-block/question.scss
  assets/blocks/quiz/question-description-block/block.json
  assets/blocks/quiz/question-description-block/question-description.js
  assets/blocks/quiz/quiz-block/block.json
  assets/blocks/quiz/quiz-block/quiz-edit.js
  assets/blocks/quiz/quiz-block/quiz-edit.test.js
  assets/course-theme/learning-mode.js
  assets/css/3rd-party/themes/course/learning-mode.scss
  assets/css/3rd-party/themes/course/questions.scss
  assets/css/3rd-party/themes/course/quiz.scss
  assets/css/frontend.scss
  assets/css/question-answer-tinymce-editor.css
  assets/css/sensei-course-theme/buttons.scss
  assets/css/sensei-course-theme/content.scss
  assets/css/sensei-course-theme/quiz-compat.scss
  assets/css/sensei-course-theme/quiz.scss
  assets/js/file-upload-question-type.js
  assets/js/question-answer-tinymce-editor.js
  changelog/add-change-all-question-styles
  changelog/add-change-style-of-submitted-quizzes
  changelog/add-footer-style-update-lm-quiz
  changelog/template-changes
  includes/blocks/class-sensei-quiz-blocks.php
  includes/blocks/course-theme/class-quiz-content.php
  includes/class-sensei-question.php
  includes/class-sensei-quiz.php
  includes/class-sensei-utils.php
  includes/template-functions.php
  psalm.xml
  templates/single-quiz.php
  templates/single-quiz/question-type-boolean.php
  templates/single-quiz/question-type-file-upload.php
  templates/single-quiz/question-type-gap-fill.php
  templates/single-quiz/question-type-multi-line.php
  templates/single-quiz/question-type-multiple-choice.php
  templates/single-quiz/question-type-single-line.php
  webpack.config.js
Labels: [Project] Frontend Improvements

#7166 Release 4.17.0
  assets/blocks/course-outline/outline-block/outline-edit.js
  changelog.txt
  changelog/add-change-all-question-styles
  changelog/add-change-quiz-design-learning-mode
  changelog/add-change-style-of-submitted-quizzes
  changelog/add-footer-style-update-lm-quiz
  changelog/add-header-on-lm-quiz-template
  changelog/fix-ai-course-outline-not-working-for-wcpc
  changelog/fix-extra-heading-fix-course-and-lesson
  changelog/fix-infinite-loop-in-messages-page
  changelog/fix-lesson-template-selection
  changelog/fix-lm-button-padding-and-gap-style
  changelog/fix-php8.0-dynamic-property
  changelog/template-changes
  changelog/update-exit-survey-tweaks
  changelog/update-lesson-layouts-order
  changelog/update-lesson-types-naming
  includes/class-sensei-utils.php
  includes/course-theme/class-sensei-course-theme-templates.php
  includes/course-theme/class-sensei-course-theme.php
  includes/internal/action-scheduler/class-action-scheduler.php
  includes/internal/migration/class-migration-abstract.php
  includes/internal/migration/class-migration-job-scheduler.php
  includes/internal/migration/class-migration-job.php
  includes/internal/migration/migrations/class-quiz-migration.php
  includes/internal/student-progress/lesson-progress/repositories/class-table-reading-aggregate-lesson-progress-repository.php
  includes/internal/student-progress/quiz-progress/repositories/class-quiz-progress-repository-factory.php
  includes/template-functions.php
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  scripts/replace-next-version-tag.sh
  sensei-lms.php
  templates/single-quiz/question-type-file-upload.php
  templates/single-quiz/question-type-gap-fill.php
  templates/single-quiz/question-type-multi-line.php
  templates/single-quiz/question-type-single-line.php
  webpack.config.js
Labels: [Type] Maintenance, No Changelog

#7168 Fix version number not being replaced and throwing error
  scripts/replace-next-version-tag.sh
Labels: No Changelog

#7173 Split the quiz submission model
  includes/internal/quiz-submission/answer/repositories/class-aggregate-answer-repository.php
  includes/internal/quiz-submission/answer/repositories/class-answer-repository-interface.php
  includes/internal/quiz-submission/answer/repositories/class-comments-based-answer-repository.php
  includes/internal/quiz-submission/answer/repositories/class-tables-based-answer-repository.php
  includes/internal/quiz-submission/grade/repositories/class-aggregate-grade-repository.php
  includes/internal/quiz-submission/grade/repositories/class-comments-based-grade-repository.php
  includes/internal/quiz-submission/grade/repositories/class-grade-repository-interface.php
  includes/internal/quiz-submission/grade/repositories/class-tables-based-grade-repository.php
  includes/internal/quiz-submission/submission/models/class-comments-based-submission.php
  includes/internal/quiz-submission/submission/models/class-submission-abstract.php
  includes/internal/quiz-submission/submission/models/class-submission-interface.php
  includes/internal/quiz-submission/submission/models/class-tables-based-submission.php
  includes/internal/quiz-submission/submission/repositories/class-aggregate-submission-repository.php
  includes/internal/quiz-submission/submission/repositories/class-comments-based-submission-repository.php
  includes/internal/quiz-submission/submission/repositories/class-submission-repository-interface.php
  includes/internal/quiz-submission/submission/repositories/class-tables-based-submission-repository.php
  tests/unit-tests/internal/quiz-submission/answer/repositories/test-class-aggregate-answer-repository.php
  tests/unit-tests/internal/quiz-submission/answer/repositories/test-class-comments-based-answer-repository.php
  tests/unit-tests/internal/quiz-submission/answer/repositories/test-class-tables-based-answer-repository.php
  tests/unit-tests/internal/quiz-submission/grade/repositories/test-class-aggregate-grade-repository.php
  tests/unit-tests/internal/quiz-submission/grade/repositories/test-class-comments-based-grade-repository.php
  tests/unit-tests/internal/quiz-submission/grade/repositories/test-class-tables-based-grade-repository.php
  tests/unit-tests/internal/quiz-submission/submission/models/test-class-comments-based-submission.php
  tests/unit-tests/internal/quiz-submission/submission/models/test-class-tables-based-submission.php
  tests/unit-tests/internal/quiz-submission/submission/repositories/test-class-aggregate-submission-repository.php
  tests/unit-tests/internal/quiz-submission/submission/repositories/test-class-comments-based-submission-repository.php
  tests/unit-tests/internal/quiz-submission/submission/repositories/test-class-tables-based-submission-repository.php
  tests/unit-tests/test-class-sensei-utils.php
Labels: [Project] Progress Storage, No Changelog

#6819 Fix sensei email generating multiple queries on page load
  changelog/fix-sensei-email-generating-multiple-queries-on-page-load
  includes/internal/emails/class-email-generator.php
  includes/internal/emails/class-email-sender.php
  includes/internal/emails/generators/class-course-completed.php
  includes/internal/emails/generators/class-course-created.php
  includes/internal/emails/generators/class-course-welcome.php
  includes/internal/emails/generators/class-email-generators-abstract.php
  includes/internal/emails/generators/class-new-course-assigned.php
  includes/internal/emails/generators/class-quiz-graded.php
  includes/internal/emails/generators/class-student-completes-course.php
  includes/internal/emails/generators/class-student-completes-lesson.php
  includes/internal/emails/generators/class-student-message-reply.php
  includes/internal/emails/generators/class-student-sends-message.php
  includes/internal/emails/generators/class-student-starts-course.php
  includes/internal/emails/generators/class-student-submits-quiz.php
  includes/internal/emails/generators/class-teacher-message-reply.php
  psalm.xml
  tests/unit-tests/internal/emails/generators/test-class-course-completed.php
  tests/unit-tests/internal/emails/generators/test-class-course-created.php
  tests/unit-tests/internal/emails/generators/test-class-course-welcome.php
  tests/unit-tests/internal/emails/generators/test-class-new-course-assigned.php
  tests/unit-tests/internal/emails/generators/test-class-quiz-graded.php
  tests/unit-tests/internal/emails/generators/test-class-student-completes-course.php
  tests/unit-tests/internal/emails/generators/test-class-student-completes-lesson.php
  tests/unit-tests/internal/emails/generators/test-class-student-message-reply.php
  tests/unit-tests/internal/emails/generators/test-class-student-starts-course.php
  tests/unit-tests/internal/emails/generators/test-class-student-submits-quiz.php
  tests/unit-tests/internal/emails/generators/test-class-teacher-message-reply.php
  tests/unit-tests/internal/emails/test-class-email-generator.php
Labels: Performance

#7178 Split the quiz answer model
  includes/class-sensei-quiz.php
  includes/internal/quiz-submission/answer/models/class-answer-abstract.php
  includes/internal/quiz-submission/answer/models/class-answer-interface.php
  includes/internal/quiz-submission/answer/models/class-comments-based-answer.php
  includes/internal/quiz-submission/answer/models/class-tables-based-answer.php
  includes/internal/quiz-submission/answer/repositories/class-aggregate-answer-repository.php
  includes/internal/quiz-submission/answer/repositories/class-answer-repository-interface.php
  includes/internal/quiz-submission/answer/repositories/class-comments-based-answer-repository.php
  includes/internal/quiz-submission/answer/repositories/class-tables-based-answer-repository.php
  includes/internal/quiz-submission/grade/repositories/class-aggregate-grade-repository.php
  includes/internal/quiz-submission/grade/repositories/class-comments-based-grade-repository.php
  includes/internal/quiz-submission/grade/repositories/class-grade-repository-interface.php
  includes/internal/quiz-submission/grade/repositories/class-tables-based-grade-repository.php
  tests/unit-tests/internal/quiz-submission/answer/models/test-class-comments-based-answer.php
  tests/unit-tests/internal/quiz-submission/answer/models/test-class-tables-based-answer.php
  tests/unit-tests/internal/quiz-submission/answer/repositories/test-class-comments-based-answer-repository.php
  tests/unit-tests/internal/quiz-submission/answer/repositories/test-class-tables-based-answer-repository.php
  tests/unit-tests/internal/quiz-submission/grade/repositories/test-class-aggregate-grade-repository.php
  tests/unit-tests/internal/quiz-submission/grade/repositories/test-class-comments-based-grade-repository.php
  tests/unit-tests/internal/quiz-submission/grade/repositories/test-class-tables-based-grade-repository.php
Labels: [Project] High-Performance Progress Storage, No Changelog

#7179 Split the quiz grade model
  includes/internal/quiz-submission/grade/models/class-comments-based-grade.php
  includes/internal/quiz-submission/grade/models/class-grade-abstract.php
  includes/internal/quiz-submission/grade/models/class-grade-interface.php
  includes/internal/quiz-submission/grade/models/class-tables-based-grade.php
  includes/internal/quiz-submission/grade/repositories/class-aggregate-grade-repository.php
  includes/internal/quiz-submission/grade/repositories/class-comments-based-grade-repository.php
  includes/internal/quiz-submission/grade/repositories/class-grade-repository-interface.php
  includes/internal/quiz-submission/grade/repositories/class-tables-based-grade-repository.php
  tests/unit-tests/internal/quiz-submission/grade/models/test-class-comments-based-grade.php
  tests/unit-tests/internal/quiz-submission/grade/models/test-class-tables-based-grade.php
  tests/unit-tests/internal/quiz-submission/grade/repositories/test-class-aggregate-grade-repository.php
  tests/unit-tests/internal/quiz-submission/grade/repositories/test-class-comments-based-grade-repository.php
  tests/unit-tests/internal/quiz-submission/grade/repositories/test-class-tables-based-grade-repository.php
Labels: [Project] High-Performance Progress Storage, No Changelog

#7172 Split progress models
  includes/class-sensei-utils.php
  includes/internal/emails/generators/class-student-completes-lesson.php
  includes/internal/migration/migrations/class-student-progress-migration.php
  includes/internal/student-progress/course-progress/models/class-comments-based-course-progress.php
  includes/internal/student-progress/course-progress/models/class-course-progress-abstract.php
  includes/internal/student-progress/course-progress/models/class-course-progress-interface.php
  includes/internal/student-progress/course-progress/models/class-tables-based-course-progress.php
  includes/internal/student-progress/course-progress/repositories/class-comment-reading-aggregate-course-progress-repository.php
  includes/internal/student-progress/course-progress/repositories/class-comments-based-course-progress-repository.php
  includes/internal/student-progress/course-progress/repositories/class-course-progress-repository-interface.php
  includes/internal/student-progress/course-progress/repositories/class-table-reading-aggregate-course-progress-repository.php
  includes/internal/student-progress/course-progress/repositories/class-tables-based-course-progress-repository.php
  includes/internal/student-progress/lesson-progress/models/class-comments-based-lesson-progress.php
  includes/internal/student-progress/lesson-progress/models/class-lesson-progress-abstract.php
  includes/internal/student-progress/lesson-progress/models/class-lesson-progress-interface.php
  includes/internal/student-progress/lesson-progress/models/class-tables-based-lesson-progress.php
  includes/internal/student-progress/lesson-progress/repositories/class-comment-reading-aggregate-lesson-progress-repository.php
  includes/internal/student-progress/lesson-progress/repositories/class-comments-based-lesson-progress-repository.php
  includes/internal/student-progress/lesson-progress/repositories/class-lesson-progress-repository-interface.php
  includes/internal/student-progress/lesson-progress/repositories/class-table-reading-aggregate-lesson-progress-repository.php
  includes/internal/student-progress/lesson-progress/repositories/class-tables-based-lesson-progress-repository.php
  includes/internal/student-progress/quiz-progress/models/class-comments-based-quiz-progress.php
  includes/internal/student-progress/quiz-progress/models/class-quiz-progress-abstract.php
  includes/internal/student-progress/quiz-progress/models/class-quiz-progress-interface.php
  includes/internal/student-progress/quiz-progress/models/class-tables-based-quiz-progress.php
  includes/internal/student-progress/quiz-progress/repositories/class-comment-reading-aggregate-quiz-progress-repository.php
  includes/internal/student-progress/quiz-progress/repositories/class-comments-based-quiz-progress-repository.php
  includes/internal/student-progress/quiz-progress/repositories/class-quiz-progress-repository-interface.php
  includes/internal/student-progress/quiz-progress/repositories/class-table-reading-aggregate-quiz-progress-repository.php
  includes/internal/student-progress/quiz-progress/repositories/class-tables-based-quiz-progress-repository.php
  includes/rest-api/class-sensei-rest-api-extensions-controller.php
  tests/unit-tests/internal/emails/generators/test-class-student-completes-lesson.php
  tests/unit-tests/internal/student-progress/course-progress/models/test-class-comments-based-course-progress.php
  tests/unit-tests/internal/student-progress/course-progress/models/test-class-tables-based-course-progress.php
  tests/unit-tests/internal/student-progress/course-progress/repositories/test-class-comment-reading-aggregate-course-progress-repository.php
  tests/unit-tests/internal/student-progress/course-progress/repositories/test-class-comments-based-course-progress-repository.php
  tests/unit-tests/internal/student-progress/course-progress/repositories/test-class-table-reading-aggregate-course-progress-repository.php
  tests/unit-tests/internal/student-progress/course-progress/repositories/test-class-tables-based-course-progress-repository.php
  tests/unit-tests/internal/student-progress/lesson-progress/models/test-class-comments-based-lesson-progress.php
  tests/unit-tests/internal/student-progress/lesson-progress/models/test-class-tables-based-lesson-progress.php
  tests/unit-tests/internal/student-progress/lesson-progress/repositories/test-class-comment-reading-aggregate-lesson-progress-repository.php
  tests/unit-tests/internal/student-progress/lesson-progress/repositories/test-class-comments-based-lesson-progress-repository.php
  tests/unit-tests/internal/student-progress/lesson-progress/repositories/test-class-table-reading-aggregate-lesson-progress-repository.php
  tests/unit-tests/internal/student-progress/lesson-progress/repositories/test-class-tables-based-lesson-progress-repository.php
  tests/unit-tests/internal/student-progress/quiz-progress/models/test-class-comments-based-quiz-progress.php
  tests/unit-tests/internal/student-progress/quiz-progress/models/test-class-tables-based-quiz-progress.php
  tests/unit-tests/internal/student-progress/quiz-progress/repositories/test-class-comment-reading-aggregate-quiz-progress-repository.php
  tests/unit-tests/internal/student-progress/quiz-progress/repositories/test-class-comments-based-quiz-progress-repository.php
  tests/unit-tests/internal/student-progress/quiz-progress/repositories/test-class-table-reading-aggregate-quiz-progress-repository.php
  tests/unit-tests/internal/student-progress/quiz-progress/repositories/test-class-tables-based-quiz-progress-repository.php
  tests/unit-tests/internal/student-progress/services/test-class-quiz-deleted-handler.php
  tests/unit-tests/test-class-quiz.php
Labels: [Project] High-Performance Progress Storage, No Changelog

#7181 Fix student progress reset not working in some cases
  changelog/fix-reset-progress
  includes/class-sensei-frontend.php
Labels: [Type] Bug

#7186 Update design of navigation area in editor for LM quiz template
  assets/course-theme/blocks/quiz-blocks/index.js
  assets/course-theme/blocks/quiz-blocks/quiz-back-to-lesson.block.json
  changelog/add-update-design-on-navigation-in-quiz-template-editor
Labels: [Project] Frontend Improvements
