Repository Automattic/sensei, pull requests merged in 2023-07, with the labels that each got.

#6997 Fix Continue Course block not redirecting to first lesson when only one lesson
  changelog/fix-continue-course-block-redirect
  includes/class-sensei-utils.php
  tests/unit-tests/test-class-utils.php
Labels: [Type] Bug

#7004 Fix tests failing on WP nightly
  tests/unit-tests/test-class-sensei-feature-flags.php
Labels: [Type] Maintenance, No Changelog

#6999 Enable to generate the course outline with blank lessons or using ai assistance
  assets/blocks/course-outline/outline-block/elements/deprecated-placeholder.js
  assets/blocks/course-outline/outline-block/outline-edit.js
  assets/blocks/course-outline/outline-block/outline-placeholder.js
  assets/blocks/course-outline/outline-block/outline-placeholder.test.js
  assets/blocks/course-outline/outline-block/use-sensei-pro-settings.js
  assets/blocks/course-outline/outline-block/use-sensei-pro-settings.test.js
Labels: No Changelog, Course Outline AI

#7010 Course outline adjustments
  assets/blocks/course-outline/course-outline-editor.scss
  assets/blocks/course-outline/outline-block/outline-placeholder.js
Labels: No Changelog, Course Outline AI

#6968 Use from name/address on the email notifications
  changelog/fix-use-from-info-on-new-emails
  includes/internal/emails/class-email-preview.php
  includes/internal/emails/class-email-sender.php
  tests/unit-tests/internal/emails/test-class-email-preview.php
  tests/unit-tests/internal/emails/test-class-email-sender.php
Labels: [Type] Bug, [Status] Needs Documentation, Emails

#7005 Bump required PHP version to 7.3
  .github/workflows/php.yml
  changelog/update-bump-php-version
  composer.json
  includes/class-sensei-dependency-checker.php
  readme.txt
  sensei-lms.php
Labels: [Status] Needs Documentation

#7011 Update e2e tests with the new course outline selection
  .github/workflows/e2e.yml
  .wp-env.json
  package-lock.json
  package.json
  tests/e2e-playwright/config/global-setup.ts
  tests/e2e-playwright/pages/admin/courses/index.ts
  tests/e2e-playwright/specs/admin/blocks/course-list-block.spec.ts
  tests/e2e-playwright/specs/admin/teacher/course-creation.spec.ts
Labels: [Type] Maintenance, No Changelog, [Project] Course Outline AI

#7013 Update Composer dependencies
  .github/actions/install-php/action.yml
  composer.json
  composer.lock
  includes/lib/usage-tracking/tests/test-class-usage-tracking.php
  tests/unit-tests/admin/test-class-sensei-learners-admin-bulk-actions-ajax.php
  tests/unit-tests/admin/test-class-sensei-setup-wizard.php
  tests/unit-tests/blocks/course-theme/test-class-lesson-actions.php
  tests/unit-tests/blocks/test-class-sensei-block-take-course.php
  tests/unit-tests/blocks/test-class-sensei-block-view-results.php
  tests/unit-tests/blocks/test-class-sensei-contact-teacher-block.php
  tests/unit-tests/blocks/test-class-sensei-continue-course-block.php
  tests/unit-tests/blocks/test-class-sensei-course-categories-block.php
  tests/unit-tests/blocks/test-class-sensei-global-blocks.php
  tests/unit-tests/course-theme/test-class-sensei-course-theme-lesson.php
  tests/unit-tests/data-port/models/test-class-sensei-data-port-course-model.php
  tests/unit-tests/data-port/test-class-sensei-data-port-manager.php
  tests/unit-tests/enrolment/test-class-sensei-enrolment-job-scheduler.php
  tests/unit-tests/enrolment/test-class-sensei-enrolment-provider-journal-store.php
  tests/unit-tests/enrolment/test-class-sensei-enrolment-provider-state-store.php
  tests/unit-tests/internal/emails/generators/test-class-course-completed.php
  tests/unit-tests/internal/emails/generators/test-class-new-course-assigned.php
  tests/unit-tests/internal/emails/generators/test-class-quiz-graded.php
  tests/unit-tests/internal/emails/generators/test-class-student-completes-course.php
  tests/unit-tests/internal/emails/generators/test-class-student-message-reply.php
  tests/unit-tests/internal/emails/generators/test-class-student-starts-course.php
  tests/unit-tests/internal/emails/generators/test-class-student-submits-quiz.php
  tests/unit-tests/internal/emails/test-class-email-blocks.php
  tests/unit-tests/internal/emails/test-class-email-repository.php
  tests/unit-tests/test-class-admin.php
  tests/unit-tests/test-class-posttypes.php
  tests/unit-tests/test-class-sensei-guest-user.php
  tests/unit-tests/test-class-sensei-preview-user.php
  tests/unit-tests/test-class-sensei-usage-tracking-data.php
  tests/unit-tests/test-class-teacher.php
Labels: [Type] Maintenance, No Changelog

#7015 Fix php 8.1 autovivification of false to array deprecation message issue
  changelog/fix-php-8-1-array-from-false-deprecate
  includes/admin/home/class-sensei-home-remote-data-api.php
Labels: [Type] Bug

#7017 Add GitHub workflow for validating pull requests
  .github/workflows/php.yml
  .github/workflows/pr-validation.yml
Labels: [Type] Maintenance, No Changelog

#7018 Improve course outline placeholder
  assets/blocks/course-outline/course-outline-editor.scss
  assets/blocks/course-outline/outline-block/ai-lessons-image.js
  assets/blocks/course-outline/outline-block/elements/ai-lessons-image.js
  assets/blocks/course-outline/outline-block/outline-placeholder.js
  assets/blocks/course-outline/outline-block/outline-placeholder.scss
  assets/blocks/course-outline/outline-block/outline-placeholder.test.js
  assets/icons/course.svg
Labels: No Changelog, [Project] Course Outline AI

#7021 Downgrade symfony/polyfill due to incompatibility with SVN
  composer.json
  composer.lock
Labels: [Type] Maintenance, No Changelog

#7023 Add PR links on the Readme
  changelog.txt
  readme.txt
Labels: [Type] Maintenance, No Changelog

#6399 Add quiz grade tables based repository
  includes/class-sensei-quiz.php
  includes/class-sensei-utils.php
  includes/class-sensei.php
  includes/internal/quiz-submission/answer/repositories/class-aggregate-answer-repository.php
  includes/internal/quiz-submission/answer/repositories/class-answer-repository-factory.php
  includes/internal/quiz-submission/answer/repositories/class-answer-repository-interface.php
  includes/internal/quiz-submission/answer/repositories/class-comments-based-answer-repository.php
  includes/internal/quiz-submission/answer/repositories/class-tables-based-answer-repository.php
  includes/internal/quiz-submission/grade/repositories/class-aggregate-grade-repository.php
  includes/internal/quiz-submission/grade/repositories/class-comments-based-grade-repository.php
  includes/internal/quiz-submission/grade/repositories/class-grade-repository-factory.php
  includes/internal/quiz-submission/grade/repositories/class-grade-repository-interface.php
  includes/internal/quiz-submission/grade/repositories/class-tables-based-grade-repository.php
  tests/unit-tests/internal/quiz-submission/answer/repositories/test-class-aggregate-answer-repository.php
  tests/unit-tests/internal/quiz-submission/answer/repositories/test-class-comments-based-answer-repository.php
  tests/unit-tests/internal/quiz-submission/answer/repositories/test-class-tables-based-answer-repository.php
  tests/unit-tests/internal/quiz-submission/grade/repositories/test-class-aggregate-grade-repository.php
  tests/unit-tests/internal/quiz-submission/grade/repositories/test-class-comments-based-grade-repository.php
  tests/unit-tests/internal/quiz-submission/grade/repositories/test-class-grade-repository-factory.php
  tests/unit-tests/internal/quiz-submission/grade/repositories/test-class-tables-based-grade-repository.php
  tests/unit-tests/test-class-quiz.php
  tests/unit-tests/test-class-utils.php
Labels: [Type] Enhancement

#7019 Increase the # of words used to generate the course category on e2e tests
  tests/e2e-playwright/specs/admin/blocks/course-list-block.spec.ts
Labels: [Type] Maintenance, No Changelog

#7030 Add Slack notification when tests fail in trunk
  .github/workflows/e2e.yml
  .github/workflows/js.yml
  .github/workflows/php.yml
Labels: [Type] Maintenance, No Changelog

#7035 Fix flaky MailPoet test 🎉
  tests/framework/class-sensei-mailpoet-api-factory.php
Labels: [Type] Maintenance, No Changelog

#7036 Fix Slack notifications not sending on push to trunk
  .github/workflows/trunk.yml
Labels: [Type] Maintenance, No Changelog

#7042 Fix e2e test failure when creating a course
  package-lock.json
  package.json
  tests/e2e-playwright/pages/admin/post-type/index.ts
  tests/e2e-playwright/specs/admin/teacher/course-creation.spec.ts
Labels: [Type] Maintenance, No Changelog

#7025 Create progress tables only if the feature is enabled
  includes/internal/installer/class-schema.php
  tests/bootstrap.php
  tests/unit-tests/internal/installer/test-class-schema.php
Labels: [Project] Progress Storage, No Changelog
