Repository Automattic/sensei, pull requests merged in 2023-01, with the labels that each got.

#6347 Update question post type to not be publicly queryable
  includes/class-sensei-posttypes.php
Labels: [Type] Bug

#6078 Display warning in the editor when adding the lesson properties block if Learning Mode is enabled
  assets/blocks/lesson-properties/lesson-properties-edit.js
Labels: [Type] Bug

#6311 Allow preview users to take unpublished course
  includes/blocks/class-sensei-course-outline-block.php
  includes/class-sensei-course.php
  includes/class-sensei-preview-user.php
  includes/template-functions.php
  tests/unit-tests/test-class-sensei-preview-user.php
Labels: Guest Users

#6307 Add scheduled cleaner for inactive guest user
  includes/class-sensei-guest-user-cleaner.php
  includes/class-sensei.php
  tests/unit-tests/test-class-sensei-guest-user-cleaner.php
Labels: Guest Users

#6318 Stop guest users and guest role from appearing
  includes/class-sensei-guest-user.php
  includes/class-sensei.php
  tests/unit-tests/test-class-sensei-guest-user.php
Labels: Guest Users

#6373 Add course open access count in data usage
  includes/class-sensei-usage-tracking-data.php
  tests/unit-tests/test-class-sensei-usage-tracking-data.php
Labels: Guest Users

#6371 Change reset progress copy
  assets/admin/students/student-action-menu/index.js
  assets/admin/students/student-action-menu/index.test.js
  assets/admin/students/student-bulk-action-button/index.test.js
  assets/admin/students/student-modal/index.js
  assets/admin/students/student-modal/index.test.js
  includes/admin/class-sensei-learners-admin-bulk-actions-controller.php
Labels: [Type] Enhancement

#6353 Release 4.10.0
  assets/css/settings.scss
  changelog.txt
  includes/admin/class-sensei-extensions.php
  includes/admin/home/tasks/task/class-sensei-home-task-customize-course-theme.php
  includes/block-patterns/course-list/class-sensei-course-list-block-patterns.php
  includes/blocks/class-sensei-block-contact-teacher.php
  includes/class-sensei-grading-user-quiz.php
  includes/class-sensei-messages.php
  includes/class-sensei-usage-tracking-data.php
  includes/class-sensei-usage-tracking.php
  includes/class-sensei-utils.php
  includes/data-port/class-sensei-data-port-utilities.php
  includes/rest-api/class-sensei-rest-api-theme-controller.php
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
Labels: [Type] Maintenance

#6377 Fix issue where Quiz Timer options would appear only when the Random Question Order is enabled
  assets/blocks/quiz/quiz-block/quiz-settings.js
Labels: [Type] Bug, [Pri] Normal

#6364 Add hooks to disable open access and student previews
  assets/js/admin/course-general-sidebar.js
  includes/blocks/class-sensei-block-take-course.php
  includes/class-sensei-course.php
  includes/class-sensei-guest-user.php
  includes/class-sensei-preview-user.php
  tests/unit-tests/test-class-sensei-guest-user.php
  tests/unit-tests/test-class-sensei-preview-user.php
Labels: Hooks

#6381 Update composer config to add ts files to the build
  composer.json
Labels: [Type] Maintenance

#6376 Fix some issues related to Github Actions's workflows
  .github/workflows/close-issue-on-merge.yml
  .github/workflows/js.yml
  .github/workflows/trunk.yml
Labels: [Type] Maintenance

#6343 Add course list block in my courses page
  assets/blocks/course-list-block/index.js
  assets/blocks/course-list-filter-block/block.json
  assets/blocks/course-list-filter-block/course-list-filter-edit.js
  assets/blocks/course-list-filter-block/course-list-filter.js
  includes/admin/class-sensei-setup-wizard-pages.php
  includes/blocks/class-sensei-global-blocks.php
  includes/blocks/course-list/class-sensei-course-list-block.php
  includes/blocks/course-list/class-sensei-course-list-categories-filter.php
  includes/blocks/course-list/class-sensei-course-list-featured-filter.php
  includes/blocks/course-list/class-sensei-course-list-filter-abstract.php
  includes/blocks/course-list/class-sensei-course-list-filter-block.php
  includes/blocks/course-list/class-sensei-course-list-student-course-filter.php
  tests/unit-tests/admin/test-class-sensei-setup-wizard-api.php
  tests/unit-tests/blocks/test-class-sensei-course-list-filter-block.php
Labels: Course List Block

#6354 Add course list block in course archive page
  includes/admin/class-sensei-setup-wizard-pages.php
  includes/blocks/class-sensei-blocks-initializer.php
  includes/blocks/course-list/class-sensei-course-list-filter-block.php
  includes/class-sensei-course.php
  includes/unsupported-theme-handlers/class-sensei-unsupported-theme-handler-course-archive.php
  templates/archive-course.php
  tests/unit-tests/admin/test-class-sensei-setup-wizard-api.php
  tests/unit-tests/unsupported-theme-handlers/test-class-sensei-unsupported-theme-handler-course-archive.php
Labels: Hooks, Templates, Course List Block

#6406 Fix error when calling `the_content` filter with no post context
  includes/class-sensei-messages.php
Labels: [Type] Bug

#6366 Add filter for the student bulk action modal
  assets/admin/students/student-action-menu/index.js
  assets/admin/students/student-bulk-action-button/index.js
  assets/admin/students/student-bulk-action-button/student-bulk-action-button.scss
  includes/admin/class-sensei-learner-management.php
  webpack.config.js
Labels: [Type] Enhancement, Hooks

#6416 Make course list filters work in archive page
  assets/blocks/course-list-filter-block/course-list-filter.js
  includes/admin/class-sensei-setup-wizard-pages.php
  includes/blocks/class-sensei-blocks-initializer.php
  includes/blocks/course-list/class-sensei-course-list-block.php
  includes/blocks/course-list/class-sensei-course-list-categories-filter.php
  includes/blocks/course-list/class-sensei-course-list-featured-filter.php
  includes/blocks/course-list/class-sensei-course-list-filter-block.php
  includes/blocks/course-list/class-sensei-course-list-student-course-filter.php
  includes/class-sensei-course.php
  templates/archive-course.php
  tests/unit-tests/blocks/test-class-sensei-course-list-filter-block.php
Labels: Templates, Course List Block

#6395 Add filters to hide users, move some common code to Temporary users c…
  includes/class-sensei-data-cleaner.php
  includes/class-sensei-db-query-learners.php
  includes/class-sensei-grading.php
  includes/class-sensei-guest-user.php
  includes/class-sensei-preview-user.php
  includes/class-sensei-temporary-user-cleaner.php
  includes/class-sensei-temporary-user.php
  includes/class-sensei-utils.php
  includes/class-sensei.php
  tests/unit-tests/test-class-sensei-guest-user.php
  tests/unit-tests/test-class-sensei-temporary-user-cleaner.php
  tests/unit-tests/test-class-sensei-temporary-user.php
Labels: Hooks

#6424 Curate list of installed plugins that are logged
  includes/class-sensei-usage-tracking.php
Labels: Logging

#6439 Fix guest user not starting quiz timer
  includes/class-sensei-guest-user.php
Labels: Hooks, Guest Users

#6438 Fix `the_content` hook called twice when viewing a lesson in learning mode
  includes/blocks/course-theme/class-course-content.php
Labels: Performance

#6441 Return the latest status comment for course progress in case there are many
  includes/internal/student-progress/course-progress/repositories/class-comments-based-course-progress-repository.php
  tests/unit-tests/internal/student-progress/course-progress/repositories/test-class-comments-based-course-progress-repository.php
Labels: [Type] Bug
