Repository Automattic/sensei, pull requests merged in 2023-04, with the labels that each got.

#6727 Only show the sensei email template when user is editing the sensei_email post_type
  changelog/fix-hide_sensei_page_template
  includes/internal/emails/class-email-page-template.php
  tests/unit-tests/internal/emails/test-class-email-page-template.php
Labels: Email Customization

#6729 Add a "copy-changelog-to-readme" script
  scripts/copy-changelog-to-readme.php
Labels: [Type] Maintenance, No Changelog, Release Automation

#6759 Substitute theme cache to allow site editor for a non-block theme
  includes/course-theme/class-sensei-course-theme-editor.php
Labels: [Type] Bug, Learning Mode, No Changelog

#6755 Proposal: Switch to using Composer autoloader for Sensei classes
  changelog/change-use-composer-autoloader
  composer.json
  includes/class-sensei-autoloader-bundle.php
  includes/class-sensei-autoloader.php
  includes/class-sensei-bootstrap.php
  sensei-lms.php
Labels: Deprecation

#6769 Fix tests not running after switching to Composer autoloader
  composer.json
  includes/class-sensei.php
  includes/sensei-functions.php
  sensei-lms.php
Labels: [Type] Maintenance, No Changelog

#6753 Fix performance issue with alloptions filter
  changelog/fix-alloptions-call
  includes/class-sensei-settings.php
  includes/class-sensei.php
Labels: Deprecation

#6771 Tweaks to Learning Mode lesson template
  assets/course-theme/blocks/lesson-blocks/index.js
  includes/blocks/course-theme/class-lesson-actions.php
  themes/sensei-course-theme/templates/default/lesson.html
Labels: Learning Mode, No Changelog

#6778 Make the email post type private
  changelog/fix-email-post-type-being-public
  includes/internal/emails/class-email-post-type.php
Labels: [Type] Bug

#6767 Fix the home email notification settings link
  changelog/fix-email-notificaiton-settings-link
  includes/admin/home/quick-links/class-sensei-home-quick-links-provider.php
Labels: [Type] Bug

#6779 Fix Exit Course block: don't pass raw attributes to the wrapping function
  includes/blocks/course-theme/class-exit-course.php
  includes/blocks/course-theme/class-focus-mode.php
Labels: [Type] Bug, Learning Mode, No Changelog

#6782 Skip Lesson complete screen
  assets/course-theme/complete-lesson-button.js
  changelog/change-remove-lesson-complete-screen
Labels: Learning Mode

#6762 Enable course title to use heading global colors + link:hover color
  assets/course-theme/blocks/lesson-blocks/course-title.block.json
  assets/course-theme/blocks/lesson-blocks/course-title/block.json
  assets/course-theme/blocks/lesson-blocks/course-title/course-title-edit.js
  assets/course-theme/blocks/lesson-blocks/course-title/index.js
  assets/course-theme/blocks/lesson-blocks/index.js
  assets/course-theme/blocks/lesson-blocks/meta.js
  assets/css/learning-mode-compat.scss
  assets/css/sensei-course-theme/base.scss
  assets/css/sensei-course-theme/blocks/course-title.scss
  assets/css/sensei-course-theme/mobile.scss
  assets/css/sensei-course-theme/theme-fixes.scss
  assets/css/sensei-course-theme/theme.scss
  includes/blocks/course-theme/class-course-title.php
Labels: No Changelog

#6768 Add support to use global colors on the exit course button
  assets/course-theme/blocks/lesson-blocks/exit-course-button/block.json
  assets/course-theme/blocks/lesson-blocks/exit-course-button/exit-course-edit.js
  assets/course-theme/blocks/lesson-blocks/exit-course-button/index.js
  assets/course-theme/blocks/lesson-blocks/exit-course.block.json
  assets/course-theme/blocks/lesson-blocks/index.js
  assets/css/sensei-course-theme/blocks/exit-course-button.scss
  assets/css/sensei-course-theme/theme-fixes.scss
  assets/css/sensei-theme-blocks.scss
  changelog/fix-use-global-colors-exit-button
  includes/blocks/course-theme/class-exit-course.php
Labels: No Changelog

#6775 Add condition for notices to happen in a specific date range
  changelog/add-notice-condition-date-range
  includes/admin/class-sensei-admin-notices.php
  tests/unit-tests/admin/test-class-sensei-admin-notices.php
Labels: Re-engaging Customers

#6777 Fix patterns layout preview style
  assets/admin/editor-wizard/patterns-list.scss
  changelog/fix-wizard-layouts-preview
Labels: [Type] Bug

#6805 Fix warning when no author found for module and add a final fallback as author
  changelog/fix-warning-when-no-author-found-for-module
  includes/class-sensei-modules.php
  tests/unit-tests/test-class-modules.php
Labels: [Type] Bug

#6783 Update colors and typography of default Learning Mode template
  assets/course-theme/blocks/course-navigation/index.js
  assets/course-theme/blocks/lesson-blocks/index.js
  assets/course-theme/blocks/lesson-blocks/module-title/module-title-edit.js
  assets/css/learning-mode-compat.scss
  assets/css/sensei-course-theme/base.scss
  assets/css/sensei-course-theme/blocks/course-navigation.scss
  assets/css/sensei-course-theme/blocks/course-progress-bar.scss
  assets/css/sensei-course-theme/blocks/course-title.scss
  assets/css/sensei-course-theme/blocks/exit-course-button.scss
  assets/css/sensei-course-theme/blocks/exit-course.scss
  assets/css/sensei-course-theme/blocks/lesson-actions.scss
  assets/css/sensei-course-theme/blocks/lesson-module.scss
  assets/css/sensei-course-theme/buttons.scss
  assets/css/sensei-course-theme/content.scss
  assets/css/sensei-course-theme/editor.scss
  assets/css/sensei-course-theme/mobile.scss
  assets/css/sensei-course-theme/theme-fixes.scss
  assets/css/sensei-theme-blocks.scss
  includes/blocks/course-theme/class-lesson-actions.php
  includes/blocks/course-theme/class-lesson-module.php
  themes/sensei-course-theme/templates/default/lesson.html
Labels: No Changelog

#6803 Fix PHP warning on Divi when using Learning Mode Video theme
  changelog/fix-divi-error-on-video-template
  includes/3rd-party/divi.php
Labels: [Type] Bug

#6825 Use href instead of xlink:href for loading SVG icons
  changelog/change-svg-xlink-href-to-href
  includes/class-sensei-assets.php
Labels: [Pri] Low

#6846 Update Sensei LMS plugin description for the WPorg plugin listing
  readme.txt
Labels: [Type] Maintenance, No Changelog
