Repository Automattic/sensei, pull requests merged in 2024-02, with the labels that each got.

#7456 Add course tour steps and feature flag for the onboarding tour
  assets/tour/course/steps.js
  includes/class-sensei-feature-flags.php
Labels: No Changelog

#7468 Fix memory issue on the student courses reports screen
  changelog/fix-reports-memory-issue
  includes/class-sensei-analysis.php
  includes/class-sensei-teacher.php
  tests/framework/trait-sensei-hpps-helpers.php
  tests/unit-tests/test-class-sensei-analysis.php
  tests/unit-tests/test-class-teacher.php
Labels: [Type] Bug

#7473 Release 4.20.2
  changelog.txt
  changelog/change-autofocus-course-title
  changelog/fix-404-after-language-switch
  changelog/fix-no-email-template-in-site-editor
  changelog/fix-reports-memory-issue
  includes/class-sensei.php
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
Labels: No Changelog

#7474 Fix update version script to support alpha versions
  scripts/update-version.sh
Labels: No Changelog

#7482 Update the WP Coding Standards
  composer.json
  composer.lock
  config/psalm/psalm-baseline.xml
  includes/admin/class-sensei-plugins-installation.php
  includes/class-sensei-analysis-overview-list-table.php
  includes/class-sensei-settings.php
  includes/internal/migration/validations/class-progress-validation.php
  includes/internal/migration/validations/class-quiz-submission-validation.php
  includes/internal/student-progress/course-progress/repositories/class-comments-based-course-progress-repository.php
  includes/internal/student-progress/course-progress/repositories/class-tables-based-course-progress-repository.php
  includes/internal/student-progress/lesson-progress/repositories/class-comments-based-lesson-progress-repository.php
  includes/internal/student-progress/lesson-progress/repositories/class-tables-based-lesson-progress-repository.php
  includes/internal/student-progress/quiz-progress/repositories/class-comments-based-quiz-progress-repository.php
  includes/internal/student-progress/quiz-progress/repositories/class-tables-based-quiz-progress-repository.php
  phpcs.xml.dist
  tests/bootstrap.php
  tests/framework/trait-sensei-test-redirect-helpers.php
  tests/unit-tests/internal/tools/test-class-progress-tables-eraser.php
Labels: No Changelog

#7496 Fix lesson translation for the course outline
  includes/wpml/class-sensei-wpml.php
Labels: No Changelog, WPML

#7499 Fix course/lesson patterns not working on latest Gutenberg
  assets/admin/editor-wizard/helpers.js
  assets/admin/editor-wizard/patterns-list.js
  changelog/fix-patterns-not-working-on-latest-gutenberg
Labels: [Type] Bug

#7500 Release 4.21.0 a.1
  lang/sensei-lms.pot
  package-lock.json
  package.json
  sensei-lms.php
Labels: No Changelog

#7484 Include base event fields for stats and system logs
  includes/class-sensei-usage-tracking-data.php
  includes/lib/usage-tracking/class-usage-tracking-base.php
Labels: No Changelog

#7513 Fix test_WPUserQuery_HasNoTemporaryUsers for WP nightly build
  tests/unit-tests/test-class-sensei-temporary-user.php
Labels: No Changelog

#7506 Add explanation about the "Display Course Author" setting
  includes/class-sensei-settings.php
Labels: No Changelog

#7517 Fix Sensei Email template being set as default template in editor when Gutenberg is installed
  changelog/fix-email-post-type-being-set-for-all-posts
  includes/internal/emails/class-email-page-template.php
  tests/unit-tests/internal/emails/test-class-email-page-template.php
Labels: Emails

#7518 Remove mention of Media Attachments extension from ReadMe
  readme.txt
Labels: No Changelog
