Repository Automattic/sensei, pull requests merged in 2024-11, with the labels that each got.

#7700 Allow additional users to manage students
  changelog/add-filter-student-management-teacher-ids
  includes/admin/class-sensei-learner-management.php
  tests/unit-tests/admin/test-class-sensei-learner-management.php
Labels: Hooks

#7698 Update Github artifact actions to v4
  .github/actions/install-php/action.yml
  .github/workflows/build-docs.yml
  .github/workflows/build.yml
  .github/workflows/changelogger.yml
  .github/workflows/dependencies-report.yml
  .github/workflows/e2e.yml
  .github/workflows/gardening.yml
  .github/workflows/js.yml
  .github/workflows/php.yml
  .github/workflows/psalm.yml
  .github/workflows/release-checklist.yml
  .github/workflows/report-build.yml
Labels: No Changelog

#7702 Filter course IDs associated with a given teacher
  changelog/fix-co-teachers-get-students
  includes/class-sensei-teacher.php
  tests/unit-tests/test-class-teacher.php
Labels: Hooks

#7615 Prevent sending welcome email immediately on enrole in case their access starts in the future
  includes/class-sensei-emails.php
  includes/internal/emails/class-email-sender.php
  includes/internal/emails/generators/class-course-welcome.php
  includes/internal/emails/generators/class-email-generators-abstract.php
  tests/unit-tests/internal/emails/generators/test-class-course-welcome.php
Labels: Hooks, No Changelog

#7711 Release 4.24.4
  changelog.txt
  changelog/add-filter-student-management-teacher-ids
  changelog/fix-archive-404-issue-in-hello-elementor
  changelog/fix-co-teachers-get-students
  changelog/fix-course-horizontal-scroll-with-course-theme
  changelog/fix-early-translations
  changelog/fix-prevent-rendering-lesson-actions-in-content-drip
  changelog/fix-teacher-student-complete-email-label
  changelog/fix-timed-quiz-input-not-stopping-when-time-ends
  changelog/fix-view-results-block-deprecated-notice
  includes/admin/class-sensei-learner-management.php
  includes/class-sensei-analysis.php
  includes/class-sensei-grading.php
  includes/class-sensei-lesson.php
  includes/class-sensei-posttypes.php
  includes/class-sensei-quiz.php
  includes/class-sensei-settings-api.php
  includes/class-sensei-teacher.php
  lang/sensei-lms.pot
  package-lock.json
  package.json
  readme.txt
  sensei-lms.php
  tests/unit-tests/test-class-posttypes.php
Labels: No Changelog
