Repository Automattic/sensei, pull requests merged in 2024-07, with the labels that each got.

#7640 Fix PHPUnit tests failing on WP trunk
  tests/unit-tests/test-class-sensei-utils.php
Labels: No Changelog

#7641 Fix E2E tests
  package-lock.json
  package.json
  tests/e2e-playwright/helpers/database.ts
  tests/e2e-playwright/helpers/preferences.ts
  tests/e2e-playwright/pages/admin/post-type/index.ts
Labels: No Changelog

#7643 Register blocks to make translations available in the editor
  includes/blocks/class-sensei-block-quiz-question.php
  includes/blocks/class-sensei-block-quiz.php
  includes/blocks/class-sensei-course-actions-block.php
  includes/blocks/class-sensei-global-blocks.php
Labels: Deprecation, No Changelog

#7595 Fix custom styles for emails in preview and in sent messages
  assets/blocks/email-editor.js
  assets/css/email-notifications/email-editor-style.scss
  assets/css/email-notifications/email-style.scss
  changelog/fix-email-styles
  includes/internal/emails/class-email-post-type.php
  includes/internal/emails/class-email-sender.php
Labels: Emails
