Repository Automattic/sensei, pull requests merged in 2024-01, with the labels that each got.

#7423 When task "Customize your lesson template" is clicked, open Lesson template in 'edit' mode
  includes/admin/home/tasks/task/class-sensei-home-task-customize-course-theme.php
  tests/unit-tests/admin/home/tasks/task/test-class-sensei-home-task-customize-course-theme.php
Labels: No Changelog, [Project] Onboarding Flow

#7429 Fix husky pre-commit not working
  .husky/pre-commit
Labels: No Changelog

#7424 Fix settings form not redirecting to the correct tab when submitted
  assets/css/admin-custom.scss
  assets/js/admin/course-theme/course-theme-sidebar.js
  assets/js/settings.js
  changelog/fix-settings-form-redirect
  config/psalm/psalm-baseline.xml
  includes/admin/home/quick-links/class-sensei-home-quick-links-provider.php
  includes/admin/home/tasks/task/class-sensei-home-task-configure-learning-mode.php
  includes/class-sensei-course.php
  includes/class-sensei-lesson.php
  includes/class-sensei-settings-api.php
  includes/internal/emails/class-settings-menu.php
  tests/unit-tests/internal/emails/test-class-settings-menu.php
  tests/unit-tests/test-class-lesson.php
  tests/unit-tests/test-class-sensei-settings-api.php
Labels: [Type] Bug, Settings

#7383 Add translations for lessons and quizzes that were created while saving the course structure
  changelog/fix-wpml-save-course-structure
  includes/class-sensei-course-structure.php
  includes/wpml/class-sensei-wpml.php
  tests/unit-tests/test-class-sensei-course-structure.php
  tests/unit-tests/wpml/test-class-sensei-wpml.php
Labels: Hooks, WPML

#7420 Add HPPS instructions
  changelog/add-hpps-instructions
  includes/class-sensei-settings.php
Labels: [Project] High-Performance Progress Storage

#7434 Auto-focus the course title field when creating a new course
  assets/admin/editor-wizard/steps/course-details-step.js
  assets/admin/editor-wizard/steps/course-details-step.test.js
  changelog/change-autofocus-course-title
Labels: [Type] Enhancement, [Project] Onboarding Flow

#7435 Flush rewrite rules when language changed or translation updated
  changelog/fix-404-after-language-switch
  includes/class-sensei.php
  tests/unit-tests/test-class-sensei.php
Labels: [Type] Bug, i18n

#7447 Release 4.20.2-a.1
  lang/sensei-lms.pot
  package-lock.json
  package.json
  sensei-lms.php
Labels: No Changelog
