Repository Automattic/sensei, pull requests merged in 2024-03, with the labels that each got.

#7521 Release 4.21.1-a.1
  lang/sensei-lms.pot
  package-lock.json
  package.json
  sensei-lms.php
Labels: No Changelog

#7519 Show tours only for new Sensei installations
  includes/admin/class-sensei-tour.php
  tests/unit-tests/admin/test-class-sensei-tour.php
Labels: No Changelog

#7510 When tour is closed or skipped, persist the choice and don't load that tour for that user
  assets/admin/tour/components/sensei-tour-kit/index.js
  assets/admin/tour/components/sensei-tour-kit/index.test.js
  assets/admin/tour/course-tour/index.js
  assets/admin/tour/data/store.js
  assets/admin/tour/data/store.test.js
  assets/admin/tour/lesson-tour/index.js
  config/psalm/psalm-baseline.xml
  includes/admin/class-sensei-tour.php
  includes/rest-api/class-sensei-rest-api-internal.php
  includes/rest-api/class-sensei-rest-api-tour-controller.php
  tests/unit-tests/admin/test-class-sensei-tour.php
  tests/unit-tests/rest-api/test-class-sensei-rest-api-tour-controller.php
Labels: Hooks, No Changelog

#7523 Add a test for lesson bulk edit
  tests/unit-tests/test-class-lesson.php
Labels: No Changelog

#7411 Add a comment in the PRs after every build with a link to the WordPress Playground for preview
  .github/workflows/build.yml
Labels: No Changelog

#7527 Update playground workflow to run only on pull requests
  .github/workflows/build.yml
Labels: No Changelog

#7522 Add tracks event in Sensei tour component and track Course and Lesson onboarding tour steps
  assets/admin/tour/components/sensei-tour-kit/index.js
  assets/admin/tour/components/sensei-tour-kit/index.test.js
  assets/admin/tour/course-tour/index.js
  assets/admin/tour/course-tour/index.test.js
  assets/admin/tour/course-tour/steps.js
  assets/admin/tour/lesson-tour/index.js
  assets/admin/tour/lesson-tour/index.test.js
  assets/admin/tour/lesson-tour/steps.js
Labels: [Status] Needs Documentation, No Changelog

#7487 Integrate tour-kit library, implement Course and Lesson tours
  assets/admin/editor-wizard/editor-wizard-modal.js
  assets/admin/students/student-action-menu/index.test.js
  assets/admin/tour/components/sensei-tour-kit/index.js
  assets/admin/tour/components/sensei-tour-kit/index.test.js
  assets/admin/tour/course-tour/index.js
  assets/admin/tour/course-tour/index.test.js
  assets/admin/tour/course-tour/steps.js
  assets/admin/tour/data/store.js
  assets/admin/tour/data/store.test.js
  assets/admin/tour/lesson-tour/index.js
  assets/admin/tour/lesson-tour/index.test.js
  assets/admin/tour/lesson-tour/steps.js
  assets/admin/tour/style.scss
  assets/admin/tour/types.js
  assets/blocks/course-outline/outline-block/outline-placeholder.test.js
  config/psalm/psalm-baseline.xml
  includes/admin/class-sensei-tour.php
  includes/class-sensei.php
  includes/rest-api/class-sensei-rest-api-internal.php
  includes/rest-api/class-sensei-rest-api-tour-controller.php
  package-lock.json
  package.json
  tests/e2e-playwright/specs/admin/teacher/course-creation.spec.ts
  tests/unit-tests/admin/test-class-sensei-tour.php
  tests/unit-tests/rest-api/test-class-sensei-rest-api-tour-controller.php
  webpack.config.js
Labels: Hooks, No Changelog, [Project] Onboarding Flow

#7526 Use bulk_edit_posts hook for bulk edit handler
  includes/class-sensei-lesson.php
  tests/unit-tests/test-class-lesson.php
Labels: No Changelog

#7530 Add notification when layouts are not available
  assets/admin/editor-wizard/patterns-list.js
  assets/admin/editor-wizard/patterns-list.scss
  assets/admin/editor-wizard/patterns-list.test.js
  changelog/fix-editor-layout-with-divi
Labels: Hooks

#7536 Add toggle to pre-publish panel to publish lessons when course is published
  assets/admin/course-pre-publish-panel/course-pre-publish-panel.js
  assets/admin/course-pre-publish-panel/index.js
  assets/icons/logo-tree.svg
  assets/js/admin/course-settings-plugin-sidebar.js
  changelog/update-save-lessons-on-course-save
  config/psalm/psalm-baseline.xml
  includes/admin/class-sensei-course-pre-publish-panel.php
  includes/block-patterns/class-sensei-block-patterns.php
  includes/class-sensei-course.php
  includes/class-sensei-data-cleaner.php
  includes/class-sensei.php
  tests/unit-tests/admin/test-class-sensei-course-pre-publish-panel.php
  webpack.config.js
Labels: [Status] Needs Documentation

#7068 Update font sizes for module title and lesson header
  assets/blocks/course-outline/module-block/module.scss
  assets/blocks/course-outline/outline-block/outline.scss
  assets/css/3rd-party/themes/course/default.scss
  assets/css/3rd-party/themes/course/style.scss
  changelog/add-ability-to-set-font-size-for-subheader
  includes/3rd-party/themes/course.php
  webpack.config.js
Labels: [Project] Frontend Improvements

#7546 Fix emails with special characters being displayed incorrectly in the subject line
  changelog/fix-encoded-email-subject
  includes/internal/emails/generators/class-course-completed.php
  includes/internal/emails/generators/class-new-course-assigned.php
  includes/internal/emails/generators/class-quiz-graded.php
  includes/internal/emails/generators/class-student-completes-course.php
  includes/internal/emails/generators/class-student-completes-lesson.php
  includes/internal/emails/generators/class-student-message-reply.php
  includes/internal/emails/generators/class-student-sends-message.php
  includes/internal/emails/generators/class-teacher-message-reply.php
  tests/unit-tests/internal/emails/generators/test-class-course-completed.php
  tests/unit-tests/internal/emails/generators/test-class-course-welcome.php
  tests/unit-tests/internal/emails/generators/test-class-new-course-assigned.php
  tests/unit-tests/internal/emails/generators/test-class-student-completes-course.php
  tests/unit-tests/internal/emails/generators/test-class-student-completes-lesson.php
  tests/unit-tests/internal/emails/generators/test-class-student-message-reply.php
  tests/unit-tests/internal/emails/generators/test-class-student-sends-message.php
  tests/unit-tests/internal/emails/generators/test-class-student-starts-course.php
  tests/unit-tests/internal/emails/generators/test-class-teacher-message-reply.php
Labels: Customer Report

#7548 Remove outline from tour highlight and tweak border color
  assets/admin/tour/style.scss
Labels: No Changelog

#7538 Add interactivity to lesson steps
  assets/admin/tour/components/sensei-tour-kit/index.js
  assets/admin/tour/components/sensei-tour-kit/index.test.js
  assets/admin/tour/course-tour/steps.js
  assets/admin/tour/helper.js
  assets/admin/tour/helper.test.js
  assets/admin/tour/lesson-tour/index.js
  assets/admin/tour/lesson-tour/steps.js
  assets/admin/tour/lesson-tour/steps.test.js
  assets/admin/tour/style.scss
  assets/blocks/quiz/quiz-block/quiz-settings.js
Labels: No Changelog, [Project] Onboarding Flow

#7550 Improve lesson tour experience
  assets/admin/tour/lesson-tour/steps.js
  assets/admin/tour/style.scss
Labels: No Changelog, [Project] Onboarding Flow

#7552 Fix highlight not removed after closing tour
  assets/admin/tour/components/sensei-tour-kit/index.js
  assets/admin/tour/components/sensei-tour-kit/index.test.js
Labels: No Changelog

#7554 Update stable tag Release 4.22.0
  readme.txt
Labels: No Changelog

#7557 Update Action Scheduler load check to use another constant
  sensei-lms.php
Labels: No Changelog

#7549 Show sell with woo tour
  includes/admin/class-sensei-tour.php
  tests/unit-tests/admin/test-class-sensei-tour.php
Labels: No Changelog
